import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import 'dm_tool_colors.dart';

/// Python ThemeManager.DEFAULT_PALETTE birebir karşılığı.
const _dark = DmToolColors(
  canvasBg: Color(0xFF181818),
  gridColor: Color(0xFF2B2B2B),
  nodeBgNote: Color(0xFFFFF9C4),
  nodeBgEntity: Color(0xFF2B2B2B),
  nodeText: Color(0xFF212121),
  lineColor: Color(0xFF787878),
  lineSelected: Color(0xFF42A5F5),
  htmlText: Color(0xFFE0E0E0),
  htmlLink: Color(0xFF42A5F5),
  htmlHeader: Color(0xFFFFB74D),
  htmlCodeBg: Color(0x4D808080),
  uiFloatingBg: Color(0xE6282828),
  uiFloatingBorder: Color(0xFF555555),
  uiFloatingText: Color(0xFFEEEEEE),
  uiFloatingHoverBg: Color(0xFF42A5F5),
  uiFloatingHoverText: Color(0xFFFFFFFF),
  uiAutosaveTextSaved: Color(0xFF81C784),
  uiAutosaveTextEditing: Color(0xFFFFB74D),
  tokenBorderPlayer: Color(0xFF4CAF50),
  tokenBorderHostile: Color(0xFFEF5350),
  tokenBorderFriendly: Color(0xFF42A5F5),
  tokenBorderNeutral: Color(0xFFBDBDBD),
  tokenBorderActive: Color(0xFFFFB74D),
  hpBarHigh: Color(0xFF2E7D32),
  hpBarMed: Color(0xFFFBC02D),
  hpBarLow: Color(0xFFC62828),
  hpWidgetBg: Color(0x4D000000),
  hpBtnDecreaseBg: Color(0xFFC62828),
  hpBtnIncreaseBg: Color(0xFF2E7D32),
  conditionDefaultBg: Color(0xFF5C6BC0),
  conditionText: Color(0xFFFFFFFF),
  fogTempPath: Color(0xFFFFFF00),
  pinNpc: Color(0xFFFF9800),
  pinMonster: Color(0xFFD32F2F),
  pinLocation: Color(0xFF2E7D32),
  pinPlayer: Color(0xFF4CAF50),
  pinDefault: Color(0xFF007ACC),
  dmNoteBorder: Color(0xFFD32F2F),
  dmNoteTitle: Color(0xFFE57373),
  sidebarLabelSecondary: Color(0xFFB8B8B8),
  sidebarDivider: Color(0xFF444444),
  sidebarFilterBg: Color(0xFF3A3A3A),
  tabBg: Color(0xFF2D2D2D),
  tabActiveBg: Color(0xFF1E1E1E),
  tabHoverBg: Color(0xFF3E3E3E),
  tabText: Color(0xFFD0D0D0),
  tabActiveText: Color(0xFFFFFFFF),
  tabIndicator: Color(0xFF007ACC),
  dangerBtnBg: Color(0xFFD32F2F),
  successBtnBg: Color(0xFF388E3C),
  uiPopupBg: Color(0xFF252526),
  uiPopupBorder: Color(0xFF444444),
  uiPopupText: Color(0xFFCCCCCC),
  uiPopupSelected: Color(0xFF094771),
  featureCardBg: Color(0xFF1E1E1E), // dark.qss: #1e1e1e
  featureCardBorder: Color(0xFF3E3E3E), // dark.qss: #3e3e3e
  featureCardAccent: Color(0xFF42A5F5), // dark.qss: #42a5f5
  // Dark theme: cool slate parchment + steel-blue accent (no red).
  srdParchment: Color(0xFF1F1F1F),
  srdInk: Color(0xFFE0E0E0),
  srdHeadingRed: Color(0xFF42A5F5),
  srdRule: Color(0xFF42A5F5),
  srdSubtitle: Color(0xFF9AA0A6),
  mapBg: Color(0xFF000000),
);

final Map<String, DmToolColors> themePalettes = {
  'dark': _dark,

  'light':
      _dark.copyWith(
            borderRadius: 2,
            cardBorderRadius: 4,
            chipBorderRadius: 6,
            buttonDefaultBg: const Color(0xFFEDF2F7),
            buttonDefaultText: const Color(0xFF1A202C),
            buttonHoverBg: const Color(0xFFCBD5E0),
            buttonPressBg: const Color(0xFFA0AEC0),
            primaryBtnBg: const Color(0xFF1565C0),
            primaryBtnText: const Color(0xFFFFFFFF),
            featureCardBg: const Color(0xFFFFFFFF),
            featureCardBorder: const Color(0xFFCBD5E0),
            featureCardAccent: const Color(0xFF2C5282),
            // Light theme: clean white paper + navy heading (no red).
            srdParchment: const Color(0xFFFFFFFF),
            srdInk: const Color(0xFF1A202C),
            srdHeadingRed: const Color(0xFF2C5282),
            srdRule: const Color(0xFFA0AEC0),
            srdSubtitle: const Color(0xFF4A5568),
            canvasBg: const Color(0xFFFBFCFE),
            gridColor: const Color(0xFFCBD5E0),
            nodeBgNote: const Color(0xFFFFFFFF),
            nodeBgEntity: const Color(0xFFFFFFFF),
            nodeText: const Color(0xFF1A202C),
            lineColor: const Color(0xFF718096),
            lineSelected: const Color(0xFF2C5282),
            htmlText: const Color(0xFF1A202C),
            htmlLink: const Color(0xFF2B6CB0),
            htmlHeader: const Color(0xFF1A365D),
            uiFloatingBg: const Color(0xE6FFFFFF),
            uiFloatingBorder: const Color(0xFFA0AEC0),
            uiFloatingText: const Color(0xFF1A202C),
            hpWidgetBg: const Color(0x1A000000),
            sidebarLabelSecondary: const Color(0xFF2D3748),
            sidebarDivider: const Color(0xFFA0AEC0),
            sidebarFilterBg: const Color(0xFFEDF2F7),
            tabBg: const Color(0xFFE2E8F0),
            tabActiveBg: const Color(0xFFFFFFFF),
            tabHoverBg: const Color(0xFFCBD5E0),
            tabText: const Color(0xFF1A202C),
            tabActiveText: const Color(0xFF0B0F19),
            tabIndicator: const Color(0xFF1565C0),
            mapBg: const Color(0xFF222222),
            uiPopupBg: const Color(0xFFFFFFFF),
            uiPopupBorder: const Color(0xFFA0AEC0),
            uiPopupText: const Color(0xFF1A202C),
            uiPopupSelected: const Color(0xFFBEE3F8),
          )
          as DmToolColors,

  'parchment':
      _dark.copyWith(
            borderRadius: 2,
            cardBorderRadius: 2,
            chipBorderRadius: 3,
            useSerif: true,
            primaryBtnBg: const Color(0xFF5D4037),
            primaryBtnText: const Color(0xFFFDFBF7),
            actionBtnBg: const Color(0xFFFF8F00),
            actionBtnText: const Color(0xFF000000),
            buttonDefaultBg: const Color(0xFFF2E5CB),
            buttonDefaultText: const Color(0xFF3E2723),
            buttonHoverBg: const Color(0xFFE5DACE),
            buttonPressBg: const Color(0xFFD7CCC8),
            featureCardBg: const Color(0xFFFDF5E3),
            featureCardBorder: const Color(0xFF8D6E63),
            featureCardAccent: const Color(0xFF5D4037),
            // Parchment theme: aged paper + warm brown heading (no red).
            srdParchment: const Color(0xFFF5EBD0),
            srdInk: const Color(0xFF2B1B14),
            srdHeadingRed: const Color(0xFF5D4037),
            srdRule: const Color(0xFF8D6E63),
            srdSubtitle: const Color(0xFF8D6E63),
            canvasBg: const Color(0xFFF5EBD0),
            gridColor: const Color(0x263E2723),
            nodeBgNote: const Color(0xFFFDFBF7),
            nodeBgEntity: const Color(0xFFFDF5E3),
            nodeText: const Color(0xFF3E2723),
            lineColor: const Color(0xFF6D4C41),
            lineSelected: const Color(0xFF3E2723),
            htmlText: const Color(0xFF2B1B14),
            htmlLink: const Color(0xFF1565C0),
            htmlHeader: const Color(0xFF3E2723),
            uiFloatingBg: const Color(0xE6FDF5E3),
            uiFloatingBorder: const Color(0xFF6D4C41),
            uiFloatingText: const Color(0xFF2B1B14),
            uiFloatingHoverBg: const Color(0xFF6D4C41),
            dmNoteBorder: const Color(0xFF6D4C41),
            dmNoteTitle: const Color(0xFF3E2723),
            tabBg: const Color(0xFFE5DACE),
            tabActiveBg: const Color(0xFFFDF5E3),
            tabHoverBg: const Color(0xFFD7CCC8),
            tabText: const Color(0xFF3E2723),
            tabActiveText: const Color(0xFF2B1B14),
            tabIndicator: const Color(0xFF3E2723),
            sidebarLabelSecondary: const Color(0xFF3E2723),
            sidebarDivider: const Color(0xFF8D6E63),
            sidebarFilterBg: const Color(0xFFE5DACE),
            uiPopupBg: const Color(0xFFFDFBF7),
            uiPopupBorder: const Color(0xFF8D6E63),
            uiPopupText: const Color(0xFF2B1B14),
            uiPopupSelected: const Color(0xFFE5DACE),
          )
          as DmToolColors,

  'ocean':
      _dark.copyWith(
            borderRadius: 4,
            cardBorderRadius: 6,
            chipBorderRadius: 8,
            featureCardBg: const Color(0xFF0A131A),
            featureCardBorder: const Color(0xFF37474F),
            featureCardAccent: const Color(0xFF00BCD4),
            tabIndicator: const Color(0xFF00BCD4),
            canvasBg: const Color(0xFF0F1B26),
            gridColor: const Color(0xFF1C313A),
            nodeBgNote: const Color(0xFFE0F7FA),
            nodeBgEntity: const Color(0xFF162533),
            nodeText: const Color(0xFF006064),
            lineColor: const Color(0xFF4DD0E1),
            lineSelected: const Color(0xFF00BCD4),
            htmlText: const Color(0xFFE0F7FA),
            htmlLink: const Color(0xFF26C6DA),
            htmlHeader: const Color(0xFF00BCD4),
            uiFloatingBg: const Color(0xE6162533),
            uiFloatingBorder: const Color(0xFF37474F),
            uiFloatingText: const Color(0xFFE0F7FA),
            uiFloatingHoverBg: const Color(0xFF00BCD4),
            srdParchment: const Color(0xFF0F1B26),
            srdInk: const Color(0xFFE0F7FA),
            srdHeadingRed: const Color(0xFF26C6DA),
            srdRule: const Color(0xFF26C6DA),
            srdSubtitle: const Color(0xFF7FB5C0),
          )
          as DmToolColors,

  'emerald':
      _dark.copyWith(
            borderRadius: 4,
            cardBorderRadius: 6,
            chipBorderRadius: 8,
            featureCardBg: const Color(0xFF00150A),
            featureCardBorder: const Color(0xFF1B5E20),
            featureCardAccent: const Color(0xFF00E676),
            tabIndicator: const Color(0xFF00E676),
            canvasBg: const Color(0xFF051E12),
            gridColor: const Color(0xFF1B5E20),
            nodeBgNote: const Color(0xFFE8F5E9),
            nodeBgEntity: const Color(0xFF0A2718),
            nodeText: const Color(0xFF1B5E20),
            lineColor: const Color(0xFF2E7D32),
            lineSelected: const Color(0xFF00E676),
            htmlText: const Color(0xFFE8F5E9),
            htmlLink: const Color(0xFF66BB6A),
            htmlHeader: const Color(0xFF00E676),
            uiFloatingBg: const Color(0xE60A2718),
            uiFloatingHoverBg: const Color(0xFF00E676),
            srdParchment: const Color(0xFF051E12),
            srdInk: const Color(0xFFE8F5E9),
            srdHeadingRed: const Color(0xFF66BB6A),
            srdRule: const Color(0xFF66BB6A),
            srdSubtitle: const Color(0xFF8DAB91),
          )
          as DmToolColors,

  'midnight':
      _dark.copyWith(
            borderRadius: 2,
            cardBorderRadius: 4,
            chipBorderRadius: 6,
            featureCardBg: const Color(0xFF1E1E1E),
            featureCardBorder: const Color(0xFF333333),
            featureCardAccent: const Color(0xFF7C4DFF),
            tabIndicator: const Color(0xFF7C4DFF),
            canvasBg: const Color(0xFF000000),
            gridColor: const Color(0xFF1A1A1A),
            nodeBgNote: const Color(0xFFE1BEE7),
            nodeBgEntity: const Color(0xFF121212),
            nodeText: const Color(0xFF4A148C),
            lineColor: const Color(0xFF7C4DFF),
            lineSelected: const Color(0xFFB388FF),
            htmlText: const Color(0xFFB0BEC5),
            htmlLink: const Color(0xFF7C4DFF),
            htmlHeader: const Color(0xFF651FFF),
            uiFloatingBg: const Color(0xE6141414),
            uiFloatingHoverBg: const Color(0xFF651FFF),
            srdParchment: const Color(0xFF0A0A12),
            srdInk: const Color(0xFFCCD0E0),
            srdHeadingRed: const Color(0xFFB388FF),
            srdRule: const Color(0xFF7C4DFF),
            srdSubtitle: const Color(0xFF7E7E92),
            cardHeadingUppercase: true,
          )
          as DmToolColors,

  'soft':
      _dark.copyWith(
            borderRadius: 6,
            cardBorderRadius: 10,
            chipBorderRadius: 999,
            buttonPaddingH: 12,
            buttonPaddingV: 5,
            useBorders: false,
            primaryBtnBg: const Color(0xFF5865F2),
            primaryBtnText: const Color(0xFFFFFFFF),
            actionBtnBg: const Color(0xFFFAA61A),
            actionBtnText: const Color(0xFF000000),
            buttonDefaultBg: const Color(0xFF4F545C),
            buttonDefaultText: const Color(0xFFFFFFFF),
            buttonHoverBg: const Color(0xFF5D6269),
            buttonPressBg: const Color(0xFF40444B),
            featureCardBg: const Color(0xFF2F3136),
            featureCardBorder: Colors.transparent,
            featureCardAccent: const Color(0xFF5865F2),
            tabIndicator: const Color(0xFF5865F2),
            canvasBg: const Color(0xFF202225),
            gridColor: const Color(0xFF2F3136),
            nodeBgNote: const Color(0xFF36393F),
            nodeBgEntity: const Color(0xFF2F3136),
            nodeText: const Color(0xFFDCDDDE),
            lineColor: const Color(0xFF40444B),
            lineSelected: const Color(0xFF5865F2),
            htmlText: const Color(0xFFDCDDDE),
            htmlLink: const Color(0xFF00B0F4),
            htmlHeader: const Color(0xFFFFFFFF),
            uiFloatingBg: const Color(0xFF2F3136),
            uiFloatingHoverBg: const Color(0xFF5865F2),
            // Modern flat: no rule, uppercase headings, blurple accent.
            srdParchment: const Color(0xFF36393F),
            srdInk: const Color(0xFFDCDDDE),
            srdHeadingRed: const Color(0xFFFFFFFF),
            srdRule: const Color(0xFF42464D),
            srdSubtitle: const Color(0xFFB9BBBE),
            cardHeadingUppercase: true,
            cardShowRule: false,
          )
          as DmToolColors,

  'baldur':
      _dark.copyWith(
            borderRadius: 2,
            cardBorderRadius: 2,
            chipBorderRadius: 3,
            useSerif: true,
            primaryBtnBg: const Color(0xFF5D4037),
            primaryBtnText: const Color(0xFFFFD700),
            actionBtnBg: const Color(0xFFB88E4A),
            actionBtnText: const Color(0xFF000000),
            buttonDefaultBg: const Color(0xFF2D241B),
            buttonDefaultText: const Color(0xFFC8B696),
            buttonHoverBg: const Color(0xFF3D2E22),
            buttonPressBg: const Color(0xFF1A120B),
            featureCardBg: const Color(0xFF241B14),
            featureCardBorder: const Color(0xFF3D2E22),
            featureCardAccent: const Color(0xFFB88E4A),
            tabIndicator: const Color(0xFFB88E4A),
            canvasBg: const Color(0xFF110B09),
            gridColor: const Color(0xFF3E2723),
            nodeBgNote: const Color(0xFFE0D8C8),
            nodeBgEntity: const Color(0xFF1A120B),
            nodeText: const Color(0xFF3E2723),
            lineColor: const Color(0xFF8D6E63),
            lineSelected: const Color(0xFFFFD700),
            htmlText: const Color(0xFFC8B696),
            htmlLink: const Color(0xFFFFD700),
            htmlHeader: const Color(0xFFB88E4A),
            uiFloatingBg: const Color(0xE61A120B),
            uiFloatingHoverBg: const Color(0xFFB88E4A),
            uiFloatingHoverText: const Color(0xFF000000),
            // Aged tome: deep brown parchment, gold heading, gold rule.
            srdParchment: const Color(0xFF1A120B),
            srdInk: const Color(0xFFE0CFA8),
            srdHeadingRed: const Color(0xFFD4A24A),
            srdRule: const Color(0xFFB88E4A),
            srdSubtitle: const Color(0xFFA08868),
          )
          as DmToolColors,

  'grim':
      _dark.copyWith(
            borderRadius: 0,
            cardBorderRadius: 0,
            chipBorderRadius: 0,
            useSerif: true,
            primaryBtnBg: const Color(0xFF7F2A1E),
            primaryBtnText: const Color(0xFFFFFFFF),
            actionBtnBg: const Color(0xFFA63A28),
            actionBtnText: const Color(0xFF000000),
            buttonDefaultBg: const Color(0xFF333333),
            buttonDefaultText: const Color(0xFFE6E6E6),
            buttonHoverBg: const Color(0xFF444444),
            buttonPressBg: const Color(0xFF222222),
            featureCardBg: const Color(0xFF3E3B36),
            featureCardBorder: const Color(0xFF111111),
            featureCardAccent: const Color(0xFFA63A28),
            tabIndicator: const Color(0xFFA63A28),
            canvasBg: const Color(0xFF1C1C1C),
            gridColor: const Color(0xFF333333),
            nodeBgNote: const Color(0xFFD7CCC8),
            nodeBgEntity: const Color(0xFF262626),
            nodeText: const Color(0xFF3E2723),
            lineColor: const Color(0xFF555555),
            lineSelected: const Color(0xFFA63A28),
            htmlText: const Color(0xFFD7D7D7),
            htmlLink: const Color(0xFFA63A28),
            htmlHeader: const Color(0xFF8C2323),
            uiFloatingBg: const Color(0xFF333333),
            uiFloatingHoverBg: const Color(0xFFA63A28),
            // Gothic stone: dark slate parchment, blood-rust heading, uppercase carved look.
            srdParchment: const Color(0xFF1C1A18),
            srdInk: const Color(0xFFD7D7D7),
            srdHeadingRed: const Color(0xFFC04030),
            srdRule: const Color(0xFFA63A28),
            srdSubtitle: const Color(0xFF8C8C8C),
            cardHeadingUppercase: true,
          )
          as DmToolColors,

  'obsidian':
      _dark.copyWith(
            borderRadius: 0,
            cardBorderRadius: 0,
            chipBorderRadius: 0,
            primaryBtnBg: const Color(0xFF6B0F18),
            primaryBtnText: const Color(0xFFFFFFFF),
            actionBtnBg: const Color(0xFFA8121C),
            actionBtnText: const Color(0xFFFFFFFF),
            buttonDefaultBg: const Color(0xFF1A1A1A),
            buttonDefaultText: const Color(0xFFE6E6E6),
            buttonHoverBg: const Color(0xFF262626),
            buttonPressBg: const Color(0xFF0E0E0E),
            featureCardBg: const Color(0xFF141414),
            featureCardBorder: const Color(0xFF000000),
            featureCardAccent: const Color(0xFFB0151C),
            tabIndicator: const Color(0xFFB0151C),
            canvasBg: const Color(0xFF080808),
            gridColor: const Color(0xFF1F1F1F),
            nodeBgNote: const Color(0xFFD7CCC8),
            nodeBgEntity: const Color(0xFF101010),
            nodeText: const Color(0xFF3E2723),
            lineColor: const Color(0xFF3A3A3A),
            lineSelected: const Color(0xFFB0151C),
            htmlText: const Color(0xFFD7D7D7),
            htmlLink: const Color(0xFFC8202A),
            htmlHeader: const Color(0xFF7A0E16),
            uiFloatingBg: const Color(0xFF161616),
            uiFloatingHoverBg: const Color(0xFFA8121C),
            // Obsidian: volcanic glass — near-black slate, crimson edge, sans-serif.
            srdParchment: const Color(0xFF0B0B0B),
            srdInk: const Color(0xFFD7D7D7),
            srdHeadingRed: const Color(0xFFC8202A),
            srdRule: const Color(0xFFA8121C),
            srdSubtitle: const Color(0xFF8C8C8C),
            cardHeadingUppercase: true,
          )
          as DmToolColors,

  'frost':
      _dark.copyWith(
            borderRadius: 6,
            cardBorderRadius: 8,
            chipBorderRadius: 999,
            buttonDefaultBg: const Color(0xFFB2F5EA),
            buttonDefaultText: const Color(0xFF234E52),
            buttonHoverBg: const Color(0xFF81E6D9),
            buttonPressBg: const Color(0xFF4FD1C5),
            primaryBtnBg: const Color(0xFF00695C),
            primaryBtnText: const Color(0xFFFFFFFF),
            featureCardBg: const Color(0xFFFFFFFF),
            featureCardBorder: const Color(0xFFB2F5EA),
            featureCardAccent: const Color(0xFF319795),
            canvasBg: const Color(0xFFE6FFFA),
            gridColor: const Color(0xFFB2F5EA),
            nodeBgNote: const Color(0xFFFFFFFF),
            nodeBgEntity: const Color(0xFFF0FFF4),
            nodeText: const Color(0xFF234E52),
            lineColor: const Color(0xFF81E6D9),
            lineSelected: const Color(0xFF319795),
            htmlText: const Color(0xFF234E52),
            htmlLink: const Color(0xFF319795),
            htmlHeader: const Color(0xFF285E61),
            uiFloatingBg: const Color(0xE6E6FFFA),
            uiFloatingBorder: const Color(0xFF81E6D9),
            uiFloatingText: const Color(0xFF234E52),
            uiFloatingHoverBg: const Color(0xFF319795),
            tabBg: const Color(0xFFB2F5EA),
            tabActiveBg: const Color(0xFFE6FFFA),
            tabHoverBg: const Color(0xFF81E6D9),
            tabText: const Color(0xFF4A6E70),
            tabActiveText: const Color(0xFF234E52),
            tabIndicator: const Color(0xFF319795),
            sidebarLabelSecondary: const Color(0xFF5F8A8C),
            sidebarDivider: const Color(0xFF81E6D9),
            sidebarFilterBg: const Color(0xFFB2F5EA),
            uiPopupBg: const Color(0xFFFFFFFF),
            uiPopupBorder: const Color(0xFFB2F5EA),
            uiPopupText: const Color(0xFF234E52),
            uiPopupSelected: const Color(0xFFB2F5EA),
            srdParchment: const Color(0xFFE6FFFA),
            srdInk: const Color(0xFF234E52),
            srdHeadingRed: const Color(0xFF285E61),
            srdRule: const Color(0xFF319795),
            srdSubtitle: const Color(0xFF5F8A8C),
          )
          as DmToolColors,

  'amethyst':
      _dark.copyWith(
            borderRadius: 6,
            cardBorderRadius: 8,
            chipBorderRadius: 10,
            featureCardBg: const Color(0xFF18121C),
            featureCardBorder: const Color(0xFF4A148C),
            featureCardAccent: const Color(0xFFBA68C8),
            tabIndicator: const Color(0xFFBA68C8),
            canvasBg: const Color(0xFF211A26),
            gridColor: const Color(0xFF4A148C),
            nodeBgNote: const Color(0xFFF3E5F5),
            nodeBgEntity: const Color(0xFF2D2436),
            nodeText: const Color(0xFF4A148C),
            lineColor: const Color(0xFF7B1FA2),
            lineSelected: const Color(0xFFEA80FC),
            htmlText: const Color(0xFFF3E5F5),
            htmlLink: const Color(0xFFAB47BC),
            htmlHeader: const Color(0xFFEA80FC),
            uiFloatingBg: const Color(0xE62D2436),
            uiFloatingHoverBg: const Color(0xFFAB47BC),
            srdParchment: const Color(0xFF211A26),
            srdInk: const Color(0xFFF3E5F5),
            srdHeadingRed: const Color(0xFFEA80FC),
            srdRule: const Color(0xFFAB47BC),
            srdSubtitle: const Color(0xFFB0A0BC),
          )
          as DmToolColors,

  'sunset':
      _dark.copyWith(
            borderRadius: 4,
            cardBorderRadius: 8,
            chipBorderRadius: 12,
            primaryBtnBg: const Color(0xFFE65100),
            primaryBtnText: const Color(0xFFFFFFFF),
            actionBtnBg: const Color(0xFFFF8A65),
            actionBtnText: const Color(0xFF1F1118),
            buttonDefaultBg: const Color(0xFF2A1820),
            buttonDefaultText: const Color(0xFFFFCCBC),
            buttonHoverBg: const Color(0xFF3F2A33),
            buttonPressBg: const Color(0xFF15090E),
            featureCardBg: const Color(0xFF2A1820),
            featureCardBorder: const Color(0xFF3F2A33),
            featureCardAccent: const Color(0xFFFF7043),
            tabIndicator: const Color(0xFFFF7043),
            canvasBg: const Color(0xFF1F1118),
            gridColor: const Color(0xFF3F2A33),
            nodeBgNote: const Color(0xFFFFEBE5),
            nodeBgEntity: const Color(0xFF2A1820),
            nodeText: const Color(0xFF4E342E),
            lineColor: const Color(0xFF6D4C41),
            lineSelected: const Color(0xFFFF7043),
            htmlText: const Color(0xFFFFE0CC),
            htmlLink: const Color(0xFFFFAB91),
            htmlHeader: const Color(0xFFFFAB40),
            uiFloatingBg: const Color(0xE62A1820),
            uiFloatingHoverBg: const Color(0xFFFF7043),
            // Sunset: warm dusk — coral+amber on smoky plum.
            srdParchment: const Color(0xFF1F1118),
            srdInk: const Color(0xFFFFE0CC),
            srdHeadingRed: const Color(0xFFFFAB40),
            srdRule: const Color(0xFFFF7043),
            srdSubtitle: const Color(0xFFBC9A8C),
          )
          as DmToolColors,

  'nord':
      _dark.copyWith(
            borderRadius: 3,
            cardBorderRadius: 4,
            chipBorderRadius: 6,
            primaryBtnBg: const Color(0xFF5E81AC),
            primaryBtnText: const Color(0xFFECEFF4),
            actionBtnBg: const Color(0xFF88C0D0),
            actionBtnText: const Color(0xFF2E3440),
            buttonDefaultBg: const Color(0xFF3B4252),
            buttonDefaultText: const Color(0xFFECEFF4),
            buttonHoverBg: const Color(0xFF434C5E),
            buttonPressBg: const Color(0xFF2E3440),
            featureCardBg: const Color(0xFF3B4252),
            featureCardBorder: const Color(0xFF434C5E),
            featureCardAccent: const Color(0xFF88C0D0),
            tabIndicator: const Color(0xFF88C0D0),
            canvasBg: const Color(0xFF2E3440),
            gridColor: const Color(0xFF434C5E),
            nodeBgNote: const Color(0xFFECEFF4),
            nodeBgEntity: const Color(0xFF3B4252),
            nodeText: const Color(0xFF2E3440),
            lineColor: const Color(0xFF4C566A),
            lineSelected: const Color(0xFF88C0D0),
            htmlText: const Color(0xFFECEFF4),
            htmlLink: const Color(0xFF81A1C1),
            htmlHeader: const Color(0xFF8FBCBB),
            uiFloatingBg: const Color(0xE63B4252),
            uiFloatingHoverBg: const Color(0xFF5E81AC),
            // Nord: arctic polar night + frost cyan.
            srdParchment: const Color(0xFF2E3440),
            srdInk: const Color(0xFFECEFF4),
            srdHeadingRed: const Color(0xFF88C0D0),
            srdRule: const Color(0xFF5E81AC),
            srdSubtitle: const Color(0xFFD8DEE9),
          )
          as DmToolColors,

  'rose':
      _dark.copyWith(
            borderRadius: 8,
            cardBorderRadius: 14,
            chipBorderRadius: 999,
            primaryBtnBg: const Color(0xFFC2185B),
            primaryBtnText: const Color(0xFFFFFFFF),
            actionBtnBg: const Color(0xFFF06292),
            actionBtnText: const Color(0xFFFFFFFF),
            buttonDefaultBg: const Color(0xFFFCE4EC),
            buttonDefaultText: const Color(0xFF880E4F),
            buttonHoverBg: const Color(0xFFF8BBD0),
            buttonPressBg: const Color(0xFFF48FB1),
            featureCardBg: const Color(0xFFFFFFFF),
            featureCardBorder: const Color(0xFFF8BBD0),
            featureCardAccent: const Color(0xFFE91E63),
            tabIndicator: const Color(0xFFE91E63),
            canvasBg: const Color(0xFFFFF1F4),
            gridColor: const Color(0xFFF8BBD0),
            nodeBgNote: const Color(0xFFFFFFFF),
            nodeBgEntity: const Color(0xFFFFF8FA),
            nodeText: const Color(0xFF880E4F),
            lineColor: const Color(0xFFF48FB1),
            lineSelected: const Color(0xFFC2185B),
            htmlText: const Color(0xFF4A0E2A),
            htmlLink: const Color(0xFFC2185B),
            htmlHeader: const Color(0xFF880E4F),
            uiFloatingBg: const Color(0xE6FFFFFF),
            uiFloatingBorder: const Color(0xFFF8BBD0),
            uiFloatingText: const Color(0xFF4A0E2A),
            uiFloatingHoverBg: const Color(0xFFC2185B),
            tabBg: const Color(0xFFF8BBD0),
            tabActiveBg: const Color(0xFFFFFFFF),
            tabHoverBg: const Color(0xFFFCE4EC),
            tabText: const Color(0xFF880E4F),
            tabActiveText: const Color(0xFF4A0E2A),
            sidebarLabelSecondary: const Color(0xFFAD1457),
            sidebarDivider: const Color(0xFFF8BBD0),
            sidebarFilterBg: const Color(0xFFFCE4EC),
            uiPopupBg: const Color(0xFFFFFFFF),
            uiPopupBorder: const Color(0xFFF8BBD0),
            uiPopupText: const Color(0xFF4A0E2A),
            uiPopupSelected: const Color(0xFFFCE4EC),
            mapBg: const Color(0xFF2A1A1F),
            // Rose: cream pink + magenta — soft pill chips. LIGHT theme.
            srdParchment: const Color(0xFFFFF1F4),
            srdInk: const Color(0xFF4A0E2A),
            srdHeadingRed: const Color(0xFFC2185B),
            srdRule: const Color(0xFFF48FB1),
            srdSubtitle: const Color(0xFFAD1457),
          )
          as DmToolColors,

  'neon':
      _dark.copyWith(
            borderRadius: 1,
            cardBorderRadius: 2,
            chipBorderRadius: 4,
            primaryBtnBg: const Color(0xFFC2003E),
            primaryBtnText: const Color(0xFFFFFFFF),
            actionBtnBg: const Color(0xFF00E5FF),
            actionBtnText: const Color(0xFF0A0014),
            buttonDefaultBg: const Color(0xFF1A0F26),
            buttonDefaultText: const Color(0xFFE0CCFF),
            buttonHoverBg: const Color(0xFF2A1A3A),
            buttonPressBg: const Color(0xFF0F0518),
            featureCardBg: const Color(0xFF14081E),
            featureCardBorder: const Color(0xFF00E5FF),
            featureCardAccent: const Color(0xFFFF0080),
            tabIndicator: const Color(0xFFFF0080),
            canvasBg: const Color(0xFF0A0014),
            gridColor: const Color(0xFF1F0F30),
            nodeBgNote: const Color(0xFFFFE6F5),
            nodeBgEntity: const Color(0xFF14081E),
            nodeText: const Color(0xFF4A0066),
            lineColor: const Color(0xFF5F2D80),
            lineSelected: const Color(0xFFFF0080),
            htmlText: const Color(0xFFE0CCFF),
            htmlLink: const Color(0xFF00E5FF),
            htmlHeader: const Color(0xFFFF0080),
            uiFloatingBg: const Color(0xE614081E),
            uiFloatingHoverBg: const Color(0xFFFF0080),
            // Neon: cyberpunk — magenta+cyan on near-black, slight-bevel.
            srdParchment: const Color(0xFF0A0014),
            srdInk: const Color(0xFFE0CCFF),
            srdHeadingRed: const Color(0xFFFF0080),
            srdRule: const Color(0xFF00E5FF),
            srdSubtitle: const Color(0xFF9D7BB8),
          )
          as DmToolColors,

  // ─── terminal ─── Matrix/CRT: hacker green on pitch black. Uniform R5. Mono.
  'terminal':
      _dark.copyWith(
            fontFamily: 'JetBrains Mono',
            borderRadius: 5,
            cardBorderRadius: 5,
            chipBorderRadius: 5,
            primaryBtnBg: const Color(0xFF00CC33),
            primaryBtnText: const Color(0xFF050505),
            actionBtnBg: const Color(0xFF00FF41),
            actionBtnText: const Color(0xFF050505),
            buttonDefaultBg: const Color(0xFF0A1F0A),
            buttonDefaultText: const Color(0xFF00FF41),
            buttonHoverBg: const Color(0xFF143A14),
            buttonPressBg: const Color(0xFF050F05),
            featureCardBg: const Color(0xFF0A1F0A),
            featureCardBorder: const Color(0xFF00FF41),
            featureCardAccent: const Color(0xFF00FF41),
            tabIndicator: const Color(0xFF00FF41),
            canvasBg: const Color(0xFF050505),
            gridColor: const Color(0xFF143A14),
            nodeBgNote: const Color(0xFF0A1F0A),
            nodeBgEntity: const Color(0xFF0A1F0A),
            nodeText: const Color(0xFF00FF41),
            lineColor: const Color(0xFF1A661A),
            lineSelected: const Color(0xFF00FF41),
            htmlText: const Color(0xFF00FF41),
            htmlLink: const Color(0xFF7FFF7F),
            htmlHeader: const Color(0xFF00FF41),
            uiFloatingBg: const Color(0xE60A1F0A),
            uiFloatingHoverBg: const Color(0xFF00FF41),
            srdParchment: const Color(0xFF050505),
            srdInk: const Color(0xFF00FF41),
            srdHeadingRed: const Color(0xFF7FFF7F),
            srdRule: const Color(0xFF00FF41),
            srdSubtitle: const Color(0xFF4D8C4D),
          )
          as DmToolColors,

  // ─── scroll ─── burnt sepia grimoire + crimson seal. EB Garamond serif.
  'scroll':
      _dark.copyWith(
            fontFamily: 'EB Garamond',
            useSerif: true,
            borderRadius: 2,
            cardBorderRadius: 3,
            chipBorderRadius: 5,
            primaryBtnBg: const Color(0xFF8B0000),
            primaryBtnText: const Color(0xFFF5E6CA),
            actionBtnBg: const Color(0xFFB5651D),
            actionBtnText: const Color(0xFFF5E6CA),
            buttonDefaultBg: const Color(0xFF3A2818),
            buttonDefaultText: const Color(0xFFE8D9B5),
            buttonHoverBg: const Color(0xFF52382A),
            buttonPressBg: const Color(0xFF22150C),
            featureCardBg: const Color(0xFF3A2818),
            featureCardBorder: const Color(0xFF8B6B3A),
            featureCardAccent: const Color(0xFF8B0000),
            tabIndicator: const Color(0xFF8B0000),
            canvasBg: const Color(0xFF22150C),
            gridColor: const Color(0xFF52382A),
            nodeBgNote: const Color(0xFFE8D9B5),
            nodeBgEntity: const Color(0xFF3A2818),
            nodeText: const Color(0xFF2C1810),
            lineColor: const Color(0xFF8B6B3A),
            lineSelected: const Color(0xFF8B0000),
            htmlText: const Color(0xFFE8D9B5),
            htmlLink: const Color(0xFFB5651D),
            htmlHeader: const Color(0xFFD4A85A),
            uiFloatingBg: const Color(0xE63A2818),
            uiFloatingHoverBg: const Color(0xFF8B0000),
            srdParchment: const Color(0xFF22150C),
            srdInk: const Color(0xFFE8D9B5),
            srdHeadingRed: const Color(0xFFD4A85A),
            srdRule: const Color(0xFF8B0000),
            srdSubtitle: const Color(0xFFB5985A),
          )
          as DmToolColors,

  // ─── terra ─── Mediterranean: terracotta + olive on cream. LIGHT, PT Serif.
  'terra':
      _dark.copyWith(
            fontFamily: 'PT Serif',
            useSerif: true,
            borderRadius: 7,
            cardBorderRadius: 9,
            chipBorderRadius: 12,
            primaryBtnBg: const Color(0xFFC2410C),
            primaryBtnText: const Color(0xFFFFFFFF),
            actionBtnBg: const Color(0xFF65A30D),
            actionBtnText: const Color(0xFFFFFFFF),
            buttonDefaultBg: const Color(0xFFFFF8E7),
            buttonDefaultText: const Color(0xFF7C2D12),
            buttonHoverBg: const Color(0xFFFCE7C8),
            buttonPressBg: const Color(0xFFE7D5A6),
            featureCardBg: const Color(0xFFFFFFFF),
            featureCardBorder: const Color(0xFFE7D5A6),
            featureCardAccent: const Color(0xFFC2410C),
            tabIndicator: const Color(0xFFC2410C),
            canvasBg: const Color(0xFFFFF8E7),
            gridColor: const Color(0xFFE7D5A6),
            nodeBgNote: const Color(0xFFFFFFFF),
            nodeBgEntity: const Color(0xFFFFFAEC),
            nodeText: const Color(0xFF7C2D12),
            lineColor: const Color(0xFFB58A4F),
            lineSelected: const Color(0xFFC2410C),
            htmlText: const Color(0xFF3D2410),
            htmlLink: const Color(0xFFC2410C),
            htmlHeader: const Color(0xFF7C2D12),
            uiFloatingBg: const Color(0xE6FFFFFF),
            uiFloatingBorder: const Color(0xFFE7D5A6),
            uiFloatingText: const Color(0xFF3D2410),
            uiFloatingHoverBg: const Color(0xFFC2410C),
            tabBg: const Color(0xFFE7D5A6),
            tabActiveBg: const Color(0xFFFFFFFF),
            tabHoverBg: const Color(0xFFFCE7C8),
            tabText: const Color(0xFF7C2D12),
            tabActiveText: const Color(0xFF3D2410),
            sidebarLabelSecondary: const Color(0xFF7C2D12),
            sidebarDivider: const Color(0xFFE7D5A6),
            sidebarFilterBg: const Color(0xFFFCE7C8),
            uiPopupBg: const Color(0xFFFFFFFF),
            uiPopupBorder: const Color(0xFFE7D5A6),
            uiPopupText: const Color(0xFF3D2410),
            uiPopupSelected: const Color(0xFFFCE7C8),
            mapBg: const Color(0xFF2A1A0C),
            srdParchment: const Color(0xFFFFF8E7),
            srdInk: const Color(0xFF3D2410),
            srdHeadingRed: const Color(0xFFC2410C),
            srdRule: const Color(0xFFB58A4F),
            srdSubtitle: const Color(0xFF7C2D12),
          )
          as DmToolColors,

  // ─── goldenrod ─── gold on charcoal, Roman capitals. Cinzel display.
  'goldenrod':
      _dark.copyWith(
            fontFamily: 'Cinzel',
            useSerif: true,
            borderRadius: 4,
            cardBorderRadius: 6,
            chipBorderRadius: 9,
            primaryBtnBg: const Color(0xFFB8860B),
            primaryBtnText: const Color(0xFF1A1410),
            actionBtnBg: const Color(0xFFFFD700),
            actionBtnText: const Color(0xFF1A1410),
            buttonDefaultBg: const Color(0xFF2A2218),
            buttonDefaultText: const Color(0xFFFFD700),
            buttonHoverBg: const Color(0xFF3D3324),
            buttonPressBg: const Color(0xFF14100A),
            featureCardBg: const Color(0xFF2A2218),
            featureCardBorder: const Color(0xFFB8860B),
            featureCardAccent: const Color(0xFFFFD700),
            tabIndicator: const Color(0xFFFFD700),
            canvasBg: const Color(0xFF1A1410),
            gridColor: const Color(0xFF3D3324),
            nodeBgNote: const Color(0xFFFFF0C2),
            nodeBgEntity: const Color(0xFF2A2218),
            nodeText: const Color(0xFF3D2410),
            lineColor: const Color(0xFF8B6B1A),
            lineSelected: const Color(0xFFFFD700),
            htmlText: const Color(0xFFFFE6A8),
            htmlLink: const Color(0xFFFFD700),
            htmlHeader: const Color(0xFFFFEA88),
            uiFloatingBg: const Color(0xE62A2218),
            uiFloatingHoverBg: const Color(0xFFFFD700),
            srdParchment: const Color(0xFF1A1410),
            srdInk: const Color(0xFFFFE6A8),
            srdHeadingRed: const Color(0xFFFFD700),
            srdRule: const Color(0xFFB8860B),
            srdSubtitle: const Color(0xFFB89A5A),
          )
          as DmToolColors,

  // ─── jade ─── deep jade green + ivory, oriental tome. Noto Serif.
  'jade':
      _dark.copyWith(
            fontFamily: 'Noto Serif',
            useSerif: true,
            borderRadius: 6,
            cardBorderRadius: 8,
            chipBorderRadius: 11,
            primaryBtnBg: const Color(0xFF00734D),
            primaryBtnText: const Color(0xFFF5F0DC),
            actionBtnBg: const Color(0xFF00A86B),
            actionBtnText: const Color(0xFF0F2A1F),
            buttonDefaultBg: const Color(0xFF15402E),
            buttonDefaultText: const Color(0xFFF5F0DC),
            buttonHoverBg: const Color(0xFF1F5840),
            buttonPressBg: const Color(0xFF08221A),
            featureCardBg: const Color(0xFF15402E),
            featureCardBorder: const Color(0xFF1F5840),
            featureCardAccent: const Color(0xFF00A86B),
            tabIndicator: const Color(0xFF00A86B),
            canvasBg: const Color(0xFF0F2A1F),
            gridColor: const Color(0xFF1F5840),
            nodeBgNote: const Color(0xFFF5F0DC),
            nodeBgEntity: const Color(0xFF15402E),
            nodeText: const Color(0xFF0F2A1F),
            lineColor: const Color(0xFF3A7A5A),
            lineSelected: const Color(0xFF00A86B),
            htmlText: const Color(0xFFF5F0DC),
            htmlLink: const Color(0xFF7AD9A8),
            htmlHeader: const Color(0xFFD4AF37),
            uiFloatingBg: const Color(0xE615402E),
            uiFloatingHoverBg: const Color(0xFF00A86B),
            srdParchment: const Color(0xFF0F2A1F),
            srdInk: const Color(0xFFF5F0DC),
            srdHeadingRed: const Color(0xFFD4AF37),
            srdRule: const Color(0xFF00A86B),
            srdSubtitle: const Color(0xFF9AB89C),
          )
          as DmToolColors,

  // ─── vapor ─── vaporwave: pink+cyan on dark purple. Soft pill. Orbitron.
  'vapor':
      _dark.copyWith(
            fontFamily: 'Orbitron',
            borderRadius: 12,
            cardBorderRadius: 16,
            chipBorderRadius: 999,
            primaryBtnBg: const Color(0xFFFF6EC7),
            primaryBtnText: const Color(0xFF1A0033),
            actionBtnBg: const Color(0xFF00FFFF),
            actionBtnText: const Color(0xFF1A0033),
            buttonDefaultBg: const Color(0xFF3D1A5C),
            buttonDefaultText: const Color(0xFFFFD6F5),
            buttonHoverBg: const Color(0xFF52297A),
            buttonPressBg: const Color(0xFF1F0A33),
            featureCardBg: const Color(0xFF3D1A5C),
            featureCardBorder: const Color(0xFF00FFFF),
            featureCardAccent: const Color(0xFFFF6EC7),
            tabIndicator: const Color(0xFFFF6EC7),
            canvasBg: const Color(0xFF2A0F3D),
            gridColor: const Color(0xFF52297A),
            nodeBgNote: const Color(0xFFFFE0F5),
            nodeBgEntity: const Color(0xFF3D1A5C),
            nodeText: const Color(0xFF4A0066),
            lineColor: const Color(0xFF7A4DA8),
            lineSelected: const Color(0xFFFF6EC7),
            htmlText: const Color(0xFFFFD6F5),
            htmlLink: const Color(0xFF00FFFF),
            htmlHeader: const Color(0xFFFF6EC7),
            uiFloatingBg: const Color(0xE63D1A5C),
            uiFloatingHoverBg: const Color(0xFFFF6EC7),
            srdParchment: const Color(0xFF2A0F3D),
            srdInk: const Color(0xFFFFD6F5),
            srdHeadingRed: const Color(0xFFFF6EC7),
            srdRule: const Color(0xFF00FFFF),
            srdSubtitle: const Color(0xFFB89AC8),
          )
          as DmToolColors,

  // ─── mono ─── brutalist greyscale print. LIGHT. JetBrains Mono.
  'mono':
      _dark.copyWith(
            fontFamily: 'JetBrains Mono',
            borderRadius: 0,
            cardBorderRadius: 2,
            chipBorderRadius: 4,
            primaryBtnBg: const Color(0xFF000000),
            primaryBtnText: const Color(0xFFFFFFFF),
            actionBtnBg: const Color(0xFF333333),
            actionBtnText: const Color(0xFFFFFFFF),
            buttonDefaultBg: const Color(0xFFF5F5F5),
            buttonDefaultText: const Color(0xFF000000),
            buttonHoverBg: const Color(0xFFE0E0E0),
            buttonPressBg: const Color(0xFFC8C8C8),
            featureCardBg: const Color(0xFFFFFFFF),
            featureCardBorder: const Color(0xFF000000),
            featureCardAccent: const Color(0xFF000000),
            tabIndicator: const Color(0xFF000000),
            canvasBg: const Color(0xFFFAFAFA),
            gridColor: const Color(0xFFE0E0E0),
            nodeBgNote: const Color(0xFFFFFFFF),
            nodeBgEntity: const Color(0xFFF5F5F5),
            nodeText: const Color(0xFF000000),
            lineColor: const Color(0xFF666666),
            lineSelected: const Color(0xFF000000),
            htmlText: const Color(0xFF000000),
            htmlLink: const Color(0xFF000000),
            htmlHeader: const Color(0xFF000000),
            uiFloatingBg: const Color(0xE6FFFFFF),
            uiFloatingBorder: const Color(0xFF000000),
            uiFloatingText: const Color(0xFF000000),
            uiFloatingHoverBg: const Color(0xFF000000),
            tabBg: const Color(0xFFF5F5F5),
            tabActiveBg: const Color(0xFFFFFFFF),
            tabHoverBg: const Color(0xFFE0E0E0),
            tabText: const Color(0xFF333333),
            tabActiveText: const Color(0xFF000000),
            sidebarLabelSecondary: const Color(0xFF666666),
            sidebarDivider: const Color(0xFFE0E0E0),
            sidebarFilterBg: const Color(0xFFF5F5F5),
            uiPopupBg: const Color(0xFFFFFFFF),
            uiPopupBorder: const Color(0xFF000000),
            uiPopupText: const Color(0xFF000000),
            uiPopupSelected: const Color(0xFFE0E0E0),
            mapBg: const Color(0xFF1A1A1A),
            srdParchment: const Color(0xFFFAFAFA),
            srdInk: const Color(0xFF000000),
            srdHeadingRed: const Color(0xFF000000),
            srdRule: const Color(0xFF000000),
            srdSubtitle: const Color(0xFF666666),
          )
          as DmToolColors,

  // ─── carmine ─── operatic crimson velvet + cream. Playfair Display.
  'carmine':
      _dark.copyWith(
            fontFamily: 'Playfair Display',
            useSerif: true,
            borderRadius: 5,
            cardBorderRadius: 13,
            chipBorderRadius: 999,
            primaryBtnBg: const Color(0xFFDC143C),
            primaryBtnText: const Color(0xFFF5E6D3),
            actionBtnBg: const Color(0xFFFF6B7A),
            actionBtnText: const Color(0xFF1F0510),
            buttonDefaultBg: const Color(0xFF3D0F1F),
            buttonDefaultText: const Color(0xFFF5E6D3),
            buttonHoverBg: const Color(0xFF52182E),
            buttonPressBg: const Color(0xFF22060F),
            featureCardBg: const Color(0xFF3D0F1F),
            featureCardBorder: const Color(0xFF52182E),
            featureCardAccent: const Color(0xFFDC143C),
            tabIndicator: const Color(0xFFDC143C),
            canvasBg: const Color(0xFF4A0D1A),
            gridColor: const Color(0xFF52182E),
            nodeBgNote: const Color(0xFFF5E6D3),
            nodeBgEntity: const Color(0xFF3D0F1F),
            nodeText: const Color(0xFF4A0D1A),
            lineColor: const Color(0xFF7A2E45),
            lineSelected: const Color(0xFFDC143C),
            htmlText: const Color(0xFFF5E6D3),
            htmlLink: const Color(0xFFFF6B7A),
            htmlHeader: const Color(0xFFFFD700),
            uiFloatingBg: const Color(0xE63D0F1F),
            uiFloatingHoverBg: const Color(0xFFDC143C),
            srdParchment: const Color(0xFF4A0D1A),
            srdInk: const Color(0xFFF5E6D3),
            srdHeadingRed: const Color(0xFFFFD700),
            srdRule: const Color(0xFFDC143C),
            srdSubtitle: const Color(0xFFC4A88A),
          )
          as DmToolColors,
};

/// Tema adından ThemeData oluşturur. Butonlar, card'lar, divider'lar palette'e uyar.
ThemeData buildThemeData(String themeName) {
  final palette = themePalettes[themeName] ?? _dark;
  final isDark = !_lightThemes.contains(themeName);
  final brightness = isDark ? Brightness.dark : Brightness.light;

  final r = BorderRadius.circular(palette.borderRadius);
  final cr = BorderRadius.circular(palette.cardBorderRadius);
  final fontFamily = palette.fontFamily != null
      ? GoogleFonts.getFont(palette.fontFamily!).fontFamily
      : (palette.useSerif ? 'Georgia' : null);
  final borderSide = palette.useBorders
      ? BorderSide(color: palette.sidebarDivider)
      : BorderSide.none;

  // Explicit ColorScheme — colorSchemeSeed yerine manual tanım
  final colorScheme = ColorScheme(
    brightness: brightness,
    primary: palette.primaryBtnBg,
    onPrimary: palette.primaryBtnText,
    secondary: palette.featureCardAccent,
    onSecondary: palette.tabActiveText,
    error: palette.dangerBtnBg,
    onError: palette.dangerBtnText,
    surface: palette.canvasBg,
    onSurface: palette.tabActiveText,
    surfaceContainerHighest: palette.featureCardBg,
    outline: palette.sidebarDivider,
  );

  final base = ThemeData(
    brightness: brightness,
    colorScheme: colorScheme,
    useMaterial3: true,
    fontFamily: fontFamily,
    splashFactory: NoSplash.splashFactory,
  );

  return base.copyWith(
    scaffoldBackgroundColor: palette.canvasBg,
    cardColor: palette.tabActiveBg,
    dividerColor: palette.sidebarDivider,
    extensions: [palette],

    // AppBar
    appBarTheme: base.appBarTheme.copyWith(
      backgroundColor: palette.tabBg,
      foregroundColor: palette.tabActiveText,
      surfaceTintColor: Colors.transparent,
      elevation: 0,
      titleTextStyle: TextStyle(
        fontFamily: fontFamily,
        fontSize: 16,
        fontWeight: FontWeight.bold,
        color: palette.tabActiveText,
      ),
    ),

    // Card
    cardTheme: base.cardTheme.copyWith(
      color: palette.nodeBgEntity,
      surfaceTintColor: Colors.transparent,
      shape: RoundedRectangleBorder(borderRadius: cr),
      elevation: isDark ? 0 : 1,
      margin: const EdgeInsets.symmetric(vertical: 4),
    ),

    // FilledButton — default gri buton, renkli butonlar explicit style ile
    filledButtonTheme: FilledButtonThemeData(
      style: ButtonStyle(
        backgroundColor: WidgetStateProperty.resolveWith((states) {
          if (states.contains(WidgetState.pressed))
            return palette.buttonPressBg;
          if (states.contains(WidgetState.hovered))
            return palette.buttonHoverBg;
          return palette.buttonDefaultBg;
        }),
        foregroundColor: WidgetStatePropertyAll(palette.buttonDefaultText),
        overlayColor: const WidgetStatePropertyAll(Colors.transparent),
        shape: WidgetStatePropertyAll(RoundedRectangleBorder(borderRadius: r)),
        padding: WidgetStatePropertyAll(
          EdgeInsets.symmetric(
            horizontal: palette.buttonPaddingH,
            vertical: palette.buttonPaddingV,
          ),
        ),
        textStyle: WidgetStatePropertyAll(
          TextStyle(
            fontSize: 13,
            fontWeight: FontWeight.w600,
            fontFamily: fontFamily,
          ),
        ),
        side: palette.useBorders
            ? WidgetStatePropertyAll(BorderSide(color: palette.sidebarDivider))
            : null,
        elevation: const WidgetStatePropertyAll(0),
      ),
    ),

    // OutlinedButton — gri kenarlıklı
    outlinedButtonTheme: OutlinedButtonThemeData(
      style: ButtonStyle(
        backgroundColor: WidgetStateProperty.resolveWith((states) {
          if (states.contains(WidgetState.pressed))
            return palette.buttonPressBg;
          if (states.contains(WidgetState.hovered))
            return palette.buttonHoverBg;
          return Colors.transparent;
        }),
        foregroundColor: WidgetStatePropertyAll(palette.buttonDefaultText),
        overlayColor: const WidgetStatePropertyAll(Colors.transparent),
        side: WidgetStatePropertyAll(borderSide),
        shape: WidgetStatePropertyAll(RoundedRectangleBorder(borderRadius: r)),
        padding: WidgetStatePropertyAll(
          EdgeInsets.symmetric(
            horizontal: palette.buttonPaddingH,
            vertical: palette.buttonPaddingV,
          ),
        ),
        textStyle: WidgetStatePropertyAll(
          TextStyle(fontSize: 13, fontFamily: fontFamily),
        ),
      ),
    ),

    // TextButton
    textButtonTheme: TextButtonThemeData(
      style: TextButton.styleFrom(
        foregroundColor: palette.htmlLink,
        shape: RoundedRectangleBorder(borderRadius: r),
        textStyle: TextStyle(fontSize: 13, fontFamily: fontFamily),
        splashFactory: NoSplash.splashFactory,
      ),
    ),

    // IconButton
    iconButtonTheme: IconButtonThemeData(
      style: IconButton.styleFrom(
        foregroundColor: palette.tabText,
        shape: RoundedRectangleBorder(borderRadius: r),
        splashFactory: NoSplash.splashFactory,
      ),
    ),

    // Input fields
    inputDecorationTheme: InputDecorationTheme(
      filled: true,
      fillColor: isDark
          ? palette.canvasBg.withValues(alpha: 0.5)
          : palette.nodeBgNote.withValues(alpha: 0.5),
      border: OutlineInputBorder(borderRadius: r, borderSide: borderSide),
      enabledBorder: OutlineInputBorder(
        borderRadius: r,
        borderSide: borderSide,
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: r,
        borderSide: borderSide,
      ),
      labelStyle: TextStyle(
        color: palette.tabText,
        fontSize: 13,
        fontFamily: fontFamily,
      ),
      hintStyle: TextStyle(
        color: palette.sidebarLabelSecondary,
        fontSize: 13,
        fontFamily: fontFamily,
      ),
      isDense: true,
      contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
    ),

    // Chip
    chipTheme: base.chipTheme.copyWith(
      backgroundColor: palette.sidebarFilterBg,
      labelStyle: TextStyle(
        color: palette.tabText,
        fontSize: 11,
        fontFamily: fontFamily,
      ),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(palette.chipBorderRadius),
      ),
      side: borderSide,
    ),

    // ListTile
    listTileTheme: base.listTileTheme.copyWith(
      shape: RoundedRectangleBorder(borderRadius: r),
      dense: true,
    ),

    // Divider
    dividerTheme: DividerThemeData(
      color: palette.sidebarDivider,
      thickness: 1,
      space: 1,
    ),

    // Dialog
    dialogTheme: base.dialogTheme.copyWith(
      backgroundColor: palette.tabActiveBg,
      surfaceTintColor: Colors.transparent,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(palette.cardBorderRadius + 4),
      ),
      titleTextStyle: TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.bold,
        color: palette.tabActiveText,
        fontFamily: fontFamily,
      ),
    ),

    // NavigationBar (mobile bottom nav)
    navigationBarTheme: NavigationBarThemeData(
      backgroundColor: palette.tabBg,
      indicatorColor: palette.tabIndicator.withValues(alpha: 0.2),
      surfaceTintColor: Colors.transparent,
    ),

    // NavigationRail (tablet)
    navigationRailTheme: NavigationRailThemeData(
      backgroundColor: palette.tabBg,
      indicatorColor: palette.tabIndicator.withValues(alpha: 0.2),
      selectedIconTheme: IconThemeData(color: palette.tabIndicator),
      unselectedIconTheme: IconThemeData(color: palette.tabText),
    ),

    // PopupMenu
    popupMenuTheme: PopupMenuThemeData(
      color: palette.uiPopupBg,
      surfaceTintColor: Colors.transparent,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(palette.cardBorderRadius),
      ),
      textStyle: TextStyle(
        color: palette.uiPopupText,
        fontSize: 13,
        fontFamily: fontFamily,
      ),
    ),

    // SnackBar
    snackBarTheme: SnackBarThemeData(
      backgroundColor: palette.tabBg,
      contentTextStyle: TextStyle(
        color: palette.tabActiveText,
        fontFamily: fontFamily,
      ),
      shape: RoundedRectangleBorder(borderRadius: r),
      behavior: SnackBarBehavior.floating,
    ),

    // TabBar (unused currently but for future)
    tabBarTheme: TabBarThemeData(
      labelColor: palette.tabActiveText,
      unselectedLabelColor: palette.tabText,
      indicatorColor: palette.tabIndicator,
    ),

    // Checkbox
    checkboxTheme: CheckboxThemeData(
      fillColor: WidgetStateProperty.resolveWith(
        (s) => s.contains(WidgetState.selected)
            ? palette.tabIndicator
            : Colors.transparent,
      ),
      checkColor: WidgetStatePropertyAll(palette.primaryBtnText),
      side: BorderSide(color: palette.tabText.withValues(alpha: 0.5)),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(3)),
    ),

    // Switch
    switchTheme: SwitchThemeData(
      thumbColor: WidgetStateProperty.resolveWith(
        (s) => s.contains(WidgetState.selected)
            ? palette.tabIndicator
            : palette.tabText.withValues(alpha: 0.6),
      ),
      trackColor: WidgetStateProperty.resolveWith(
        (s) => s.contains(WidgetState.selected)
            ? palette.tabIndicator.withValues(alpha: 0.4)
            : palette.sidebarDivider,
      ),
      trackOutlineColor: WidgetStatePropertyAll(palette.sidebarDivider),
    ),

    // BottomSheet (mobile battlemap toolbar vs.)
    bottomSheetTheme: BottomSheetThemeData(
      backgroundColor: palette.tabBg,
      surfaceTintColor: Colors.transparent,
      modalBackgroundColor: palette.tabBg,
      modalBarrierColor: Colors.black.withValues(alpha: 0.4),
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(12)),
      ),
    ),
  );
}

const _lightThemes = {'light', 'parchment', 'frost', 'rose', 'terra', 'mono'};

/// Tüm tema isimlerinin listesi.
const themeNames = [
  'dark',
  'light',
  'parchment',
  'ocean',
  'emerald',
  'midnight',
  'soft',
  'baldur',
  'grim',
  'obsidian',
  'frost',
  'amethyst',
  'sunset',
  'nord',
  'rose',
  'neon',
  'terminal',
  'scroll',
  'terra',
  'goldenrod',
  'jade',
  'vapor',
  'mono',
  'carmine',
];
