// SRD 5.2.1 Animals (pp. 344–364). Animals share the monster stat-block
// shape but live under a separate slug so the Beast listing on p. 344
// filters cleanly. Sample shipped here: Wolf, Brown Bear. Full pass over
// the remaining ~75 animals is deferred — see plan.

import '_helpers.dart';

List<Map<String, dynamic>> srdAnimals() => [
      packEntity(
        slug: 'animal',
        name: 'Wolf',
        description:
            'A swift hunter with a haunting howl. Wolves run in packs and use coordination to bring down prey larger than themselves.',
        attributes: {
          'size_ref': lookup('size', 'Medium'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12,
          'initiative_modifier': 2,
          'initiative_score': 12,
          'hp_average': 11,
          'hp_dice': '2d8+2',
          'speed_walk_ft': 40,
          'stat_block': {
            'STR': 12, 'DEX': 15, 'CON': 12, 'INT': 3, 'WIS': 12, 'CHA': 6,
          },
          'cr': '1/4',
          'xp': 50,
          'proficiency_bonus': 2,
          'passive_perception': 13,
          'trait_refs': [
            ref('trait', 'Pack Tactics'),
            ref('trait', 'Keen Smell'),
            ref('trait', 'Keen Hearing'),
          ],
          'action_refs': [
            ref('creature-action', 'Bite (Wolf)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Giant Eagle',
        description:
            'A noble raptor of mountain heights, larger than a horse and intelligent enough to speak in Auran and Common.',
        attributes: {
          'size_ref': lookup('size', 'Large'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Neutral Good'),
          'ac': 13,
          'initiative_modifier': 3,
          'initiative_score': 13,
          'hp_average': 26,
          'hp_dice': '4d10+4',
          'speed_walk_ft': 10,
          'speed_fly_ft': 80,
          'stat_block': {
            'STR': 16, 'DEX': 17, 'CON': 13, 'INT': 8, 'WIS': 14, 'CHA': 10,
          },
          'cr': '1',
          'xp': 200,
          'proficiency_bonus': 2,
          'passive_perception': 16,
          'language_refs': [lookup('language', 'Common')],
          'trait_refs': [ref('trait', 'Keen Sight')],
          'action_refs': [
            ref('creature-action', 'Multiattack'),
            ref('creature-action', 'Talons (Giant Eagle)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Dire Wolf',
        description:
            'A wolf as large as a riding horse, with a shaggy coat and bone-crushing jaws. Dire wolves run in packs and are favored mounts of goblin chiefs.',
        attributes: {
          'size_ref': lookup('size', 'Large'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 14,
          'initiative_modifier': 2,
          'initiative_score': 12,
          'hp_average': 22,
          'hp_dice': '3d10+6',
          'speed_walk_ft': 50,
          'stat_block': {
            'STR': 17, 'DEX': 15, 'CON': 15, 'INT': 3, 'WIS': 12, 'CHA': 7,
          },
          'cr': '1',
          'xp': 200,
          'proficiency_bonus': 2,
          'passive_perception': 13,
          'trait_refs': [
            ref('trait', 'Pack Tactics'),
            ref('trait', 'Keen Smell'),
            ref('trait', 'Keen Hearing'),
          ],
          'action_refs': [
            ref('creature-action', 'Bite (Dire Wolf)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Tiger',
        description:
            'A solitary apex predator of jungles and grasslands. The tiger stalks prey from cover, then pounces with terrible speed.',
        attributes: {
          'size_ref': lookup('size', 'Large'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 13,
          'initiative_modifier': 3,
          'initiative_score': 13,
          'hp_average': 30,
          'hp_dice': '4d10+8',
          'speed_walk_ft': 40,
          'stat_block': {
            'STR': 17, 'DEX': 16, 'CON': 14, 'INT': 3, 'WIS': 12, 'CHA': 8,
          },
          'cr': '1',
          'xp': 200,
          'proficiency_bonus': 2,
          'passive_perception': 13,
          'senses': [
            {'sense': 'Darkvision', 'range_ft': 60},
          ],
          'trait_refs': [ref('trait', 'Pounce')],
          'action_refs': [
            ref('creature-action', 'Bite (Tiger)'),
          ],
          'bonus_action_refs': [
            ref('creature-action', 'Claws (Tiger)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Lion',
        description:
            'The royal predator of the savanna, hunting in coordinated prides. A lion charges from cover and uses its weight to pin prey.',
        attributes: {
          'size_ref': lookup('size', 'Large'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12,
          'initiative_modifier': 2,
          'initiative_score': 12,
          'hp_average': 26,
          'hp_dice': '4d10+4',
          'speed_walk_ft': 50,
          'stat_block': {
            'STR': 17, 'DEX': 15, 'CON': 13, 'INT': 3, 'WIS': 12, 'CHA': 8,
          },
          'cr': '1',
          'xp': 200,
          'proficiency_bonus': 2,
          'passive_perception': 13,
          'trait_refs': [
            ref('trait', 'Pack Tactics'),
            ref('trait', 'Pounce'),
            ref('trait', 'Keen Smell'),
            ref('trait', 'Running Leap'),
          ],
          'action_refs': [
            ref('creature-action', 'Bite (Lion)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Crocodile',
        description:
            'A scaled ambush predator of rivers and swamps, dragging its prey beneath the water to drown.',
        attributes: {
          'size_ref': lookup('size', 'Large'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12,
          'initiative_modifier': 0,
          'initiative_score': 10,
          'hp_average': 19,
          'hp_dice': '3d10+3',
          'speed_walk_ft': 20,
          'speed_swim_ft': 30,
          'stat_block': {
            'STR': 15, 'DEX': 10, 'CON': 13, 'INT': 2, 'WIS': 10, 'CHA': 5,
          },
          'cr': '1/2',
          'xp': 100,
          'proficiency_bonus': 2,
          'passive_perception': 10,
          'trait_refs': [ref('trait', 'Hold Breath')],
          'action_refs': [
            ref('creature-action', 'Bite (Crocodile)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Boar',
        description:
            'A bristly forest pig with sharp tusks. Boars charge straight at threats and gore them with surprising power.',
        attributes: {
          'size_ref': lookup('size', 'Medium'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 11,
          'initiative_modifier': 0,
          'initiative_score': 10,
          'hp_average': 11,
          'hp_dice': '2d8+2',
          'speed_walk_ft': 40,
          'stat_block': {
            'STR': 13, 'DEX': 11, 'CON': 12, 'INT': 2, 'WIS': 9, 'CHA': 5,
          },
          'cr': '1/4',
          'xp': 50,
          'proficiency_bonus': 2,
          'passive_perception': 9,
          'trait_refs': [ref('trait', 'Charge')],
          'action_refs': [
            ref('creature-action', 'Tusk (Boar)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Mastiff',
        description:
            'A large hunting hound, loyal and fierce. Mastiffs are favored as guard dogs and battlefield companions.',
        attributes: {
          'size_ref': lookup('size', 'Medium'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12,
          'initiative_modifier': 2,
          'initiative_score': 12,
          'hp_average': 5,
          'hp_dice': '1d8+1',
          'speed_walk_ft': 40,
          'stat_block': {
            'STR': 13, 'DEX': 14, 'CON': 12, 'INT': 3, 'WIS': 12, 'CHA': 7,
          },
          'cr': '1/8',
          'xp': 25,
          'proficiency_bonus': 2,
          'passive_perception': 13,
          'trait_refs': [ref('trait', 'Keen Hearing'), ref('trait', 'Keen Smell')],
          'action_refs': [
            ref('creature-action', 'Bite (Mastiff)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Riding Horse',
        description:
            'A common steed bred for endurance and steadiness in travel. Most adventurers acquire one for the road.',
        attributes: {
          'size_ref': lookup('size', 'Large'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 10,
          'initiative_modifier': 0,
          'initiative_score': 10,
          'hp_average': 13,
          'hp_dice': '2d10+2',
          'speed_walk_ft': 60,
          'stat_block': {
            'STR': 16, 'DEX': 10, 'CON': 12, 'INT': 2, 'WIS': 11, 'CHA': 7,
          },
          'cr': '1/4',
          'xp': 50,
          'proficiency_bonus': 2,
          'passive_perception': 10,
          'action_refs': [
            ref('creature-action', 'Hooves (Riding Horse)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Cat',
        description: 'A common house cat, swift and aloof.',
        attributes: {
          'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 2, 'hp_dice': '1d4', 'speed_walk_ft': 40, 'speed_climb_ft': 30,
          'stat_block': {'STR': 3, 'DEX': 15, 'CON': 10, 'INT': 3, 'WIS': 12, 'CHA': 7},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 13,
          'trait_refs': [ref('trait', 'Keen Smell')],
          'action_refs': [ref('creature-action', 'Bite (Cat)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Rat',
        description: 'A small disease-carrying rodent of city sewers and old grain stores.',
        attributes: {
          'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 10, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 1, 'hp_dice': '1d4-1', 'speed_walk_ft': 20,
          'stat_block': {'STR': 2, 'DEX': 11, 'CON': 9, 'INT': 2, 'WIS': 10, 'CHA': 4},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 10,
          'senses': [{'sense': 'Darkvision', 'range_ft': 30}],
          'trait_refs': [ref('trait', 'Keen Smell')],
          'action_refs': [ref('creature-action', 'Bite (Rat)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Giant Rat',
        description: 'A wolf-sized rodent with mangy fur and yellowed teeth, found in dungeons and sewers.',
        attributes: {
          'size_ref': lookup('size', 'Small'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 7, 'hp_dice': '2d6', 'speed_walk_ft': 30,
          'stat_block': {'STR': 7, 'DEX': 15, 'CON': 11, 'INT': 2, 'WIS': 10, 'CHA': 4},
          'cr': '1/8', 'xp': 25, 'proficiency_bonus': 2, 'passive_perception': 10,
          'senses': [{'sense': 'Darkvision', 'range_ft': 60}],
          'trait_refs': [ref('trait', 'Keen Smell'), ref('trait', 'Pack Tactics')],
          'action_refs': [ref('creature-action', 'Bite (Giant Rat)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Hawk',
        description: 'A small raptor with keen eyes, common to many lands.',
        attributes: {
          'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 13, 'initiative_modifier': 3, 'initiative_score': 13,
          'hp_average': 1, 'hp_dice': '1d4-1', 'speed_walk_ft': 10, 'speed_fly_ft': 60,
          'stat_block': {'STR': 5, 'DEX': 16, 'CON': 8, 'INT': 2, 'WIS': 14, 'CHA': 6},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 14,
          'trait_refs': [ref('trait', 'Keen Sight')],
          'action_refs': [ref('creature-action', 'Talons (Hawk)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Eagle',
        description: 'A keen-eyed bird of prey of mountains and open lands.',
        attributes: {
          'size_ref': lookup('size', 'Small'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 3, 'hp_dice': '1d6', 'speed_walk_ft': 10, 'speed_fly_ft': 60,
          'stat_block': {'STR': 6, 'DEX': 15, 'CON': 10, 'INT': 2, 'WIS': 14, 'CHA': 7},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 14,
          'trait_refs': [ref('trait', 'Keen Sight')],
          'action_refs': [ref('creature-action', 'Talons (Eagle)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Owl',
        description: 'A nocturnal raptor that hunts in silence.',
        attributes: {
          'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 11, 'initiative_modifier': 1, 'initiative_score': 11,
          'hp_average': 1, 'hp_dice': '1d4-1', 'speed_walk_ft': 5, 'speed_fly_ft': 60,
          'stat_block': {'STR': 3, 'DEX': 13, 'CON': 8, 'INT': 2, 'WIS': 12, 'CHA': 7},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 13,
          'senses': [{'sense': 'Darkvision', 'range_ft': 120}],
          'trait_refs': [ref('trait', 'Flyby'), ref('trait', 'Keen Hearing'), ref('trait', 'Keen Sight')],
          'action_refs': [ref('creature-action', 'Bite (Owl)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Pony',
        description: 'A small horse breed favored by halflings and gnomes.',
        attributes: {
          'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 10, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 11, 'hp_dice': '2d8+2', 'speed_walk_ft': 40,
          'stat_block': {'STR': 15, 'DEX': 10, 'CON': 13, 'INT': 2, 'WIS': 11, 'CHA': 7},
          'cr': '1/8', 'xp': 25, 'proficiency_bonus': 2, 'passive_perception': 10,
          'action_refs': [ref('creature-action', 'Bite (Pony)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Camel',
        description: 'A hardy desert beast of burden capable of many days without water.',
        attributes: {
          'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 9, 'initiative_modifier': -1, 'initiative_score': 9,
          'hp_average': 15, 'hp_dice': '2d10+4', 'speed_walk_ft': 50,
          'stat_block': {'STR': 16, 'DEX': 8, 'CON': 14, 'INT': 2, 'WIS': 8, 'CHA': 5},
          'cr': '1/8', 'xp': 25, 'proficiency_bonus': 2, 'passive_perception': 9,
          'action_refs': [ref('creature-action', 'Bite (Camel)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Elephant',
        description: 'A massive grass-eating mammal that defends its herd with charging tusks.',
        attributes: {
          'size_ref': lookup('size', 'Huge'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 76, 'hp_dice': '8d12+24', 'speed_walk_ft': 40,
          'stat_block': {'STR': 22, 'DEX': 9, 'CON': 17, 'INT': 3, 'WIS': 11, 'CHA': 6},
          'cr': '4', 'xp': 1100, 'proficiency_bonus': 2, 'passive_perception': 10,
          'trait_refs': [ref('trait', 'Charge'), ref('trait', 'Siege Monster')],
          'action_refs': [ref('creature-action', 'Multiattack'), ref('creature-action', 'Stomp (Elephant)'), ref('creature-action', 'Gore (Elephant)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Ape',
        description: 'A great forest ape that lives in family bands and defends its territory with thrown rocks.',
        attributes: {
          'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 19, 'hp_dice': '3d8+6', 'speed_walk_ft': 30, 'speed_climb_ft': 30,
          'stat_block': {'STR': 16, 'DEX': 14, 'CON': 14, 'INT': 6, 'WIS': 12, 'CHA': 7},
          'cr': '1/2', 'xp': 100, 'proficiency_bonus': 2, 'passive_perception': 13,
          'action_refs': [ref('creature-action', 'Multiattack'), ref('creature-action', 'Fist (Ape)'), ref('creature-action', 'Rock (Ape)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Constrictor Snake',
        description: 'A large serpent that subdues prey by squeezing it to death.',
        attributes: {
          'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 13, 'hp_dice': '2d10+2', 'speed_walk_ft': 30, 'speed_swim_ft': 30,
          'stat_block': {'STR': 15, 'DEX': 14, 'CON': 12, 'INT': 1, 'WIS': 10, 'CHA': 3},
          'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 10,
          'senses': [{'sense': 'Blindsight', 'range_ft': 10}],
          'action_refs': [ref('creature-action', 'Bite (Constrictor)'), ref('creature-action', 'Constrict (Constrictor)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Giant Constrictor Snake',
        description: 'An enormous serpent capable of crushing the largest prey.',
        attributes: {
          'size_ref': lookup('size', 'Huge'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 60, 'hp_dice': '8d12+8', 'speed_walk_ft': 30, 'speed_swim_ft': 30,
          'stat_block': {'STR': 19, 'DEX': 14, 'CON': 12, 'INT': 1, 'WIS': 10, 'CHA': 3},
          'cr': '2', 'xp': 450, 'proficiency_bonus': 2, 'passive_perception': 12,
          'senses': [{'sense': 'Blindsight', 'range_ft': 10}],
          'action_refs': [ref('creature-action', 'Bite (Giant Snake)'), ref('creature-action', 'Constrict (Constrictor)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Frog',
        description: 'A small amphibian found in marshes and ponds.',
        attributes: {
          'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 11, 'initiative_modifier': 1, 'initiative_score': 11,
          'hp_average': 1, 'hp_dice': '1d4-1', 'speed_walk_ft': 20, 'speed_swim_ft': 20,
          'stat_block': {'STR': 1, 'DEX': 13, 'CON': 8, 'INT': 1, 'WIS': 8, 'CHA': 3},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 9,
          'senses': [{'sense': 'Darkvision', 'range_ft': 30}],
          'trait_refs': [ref('trait', 'Amphibious'), ref('trait', 'Standing Leap')],
          'action_refs': [ref('creature-action', 'Bite (Frog)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Giant Frog',
        description: 'A horse-sized frog that lurks in fetid pools, swallowing prey whole.',
        attributes: {
          'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 11, 'initiative_modifier': 1, 'initiative_score': 11,
          'hp_average': 18, 'hp_dice': '4d8', 'speed_walk_ft': 30, 'speed_swim_ft': 30,
          'stat_block': {'STR': 12, 'DEX': 13, 'CON': 11, 'INT': 2, 'WIS': 10, 'CHA': 3},
          'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 12,
          'senses': [{'sense': 'Darkvision', 'range_ft': 30}],
          'trait_refs': [ref('trait', 'Amphibious'), ref('trait', 'Standing Leap')],
          'action_refs': [ref('creature-action', 'Bite (Giant Frog)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Giant Centipede',
        description: 'A car-sized arthropod with venomous bite, lurking in dark caves.',
        attributes: {
          'size_ref': lookup('size', 'Small'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 13, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 4, 'hp_dice': '1d6+1', 'speed_walk_ft': 30, 'speed_climb_ft': 30,
          'stat_block': {'STR': 5, 'DEX': 14, 'CON': 12, 'INT': 1, 'WIS': 7, 'CHA': 3},
          'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 8,
          'senses': [{'sense': 'Blindsight', 'range_ft': 30}],
          'action_refs': [ref('creature-action', 'Bite (Giant Centipede)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Giant Lizard',
        description: 'A donkey-sized reptile, often used as a mount or beast of burden in the Underdark.',
        attributes: {
          'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 19, 'hp_dice': '3d10+3', 'speed_walk_ft': 30, 'speed_climb_ft': 30,
          'stat_block': {'STR': 15, 'DEX': 12, 'CON': 13, 'INT': 2, 'WIS': 10, 'CHA': 5},
          'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 10,
          'senses': [{'sense': 'Darkvision', 'range_ft': 30}],
          'action_refs': [ref('creature-action', 'Bite (Giant Lizard)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Polar Bear',
        description: 'A massive white bear of arctic regions, hunting seals and the unwary.',
        attributes: {
          'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 42, 'hp_dice': '5d10+15', 'speed_walk_ft': 40, 'speed_swim_ft': 30,
          'stat_block': {'STR': 20, 'DEX': 10, 'CON': 16, 'INT': 2, 'WIS': 13, 'CHA': 7},
          'cr': '2', 'xp': 450, 'proficiency_bonus': 2, 'passive_perception': 13,
          'trait_refs': [ref('trait', 'Keen Smell'), ref('trait', 'Snow Camouflage')],
          'action_refs': [ref('creature-action', 'Multiattack'), ref('creature-action', 'Bite (Polar Bear)'), ref('creature-action', 'Claws (Polar Bear)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Warhorse',
        description: 'A heavy horse trained for battle, faster and more aggressive than a riding horse.',
        attributes: {
          'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 11, 'initiative_modifier': 1, 'initiative_score': 11,
          'hp_average': 19, 'hp_dice': '3d10+3', 'speed_walk_ft': 60,
          'stat_block': {'STR': 18, 'DEX': 12, 'CON': 13, 'INT': 2, 'WIS': 12, 'CHA': 7},
          'cr': '1/2', 'xp': 100, 'proficiency_bonus': 2, 'passive_perception': 11,
          'trait_refs': [ref('trait', 'Charge')],
          'action_refs': [ref('creature-action', 'Hooves (Warhorse)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Octopus',
        description: 'A small cephalopod with sucker-tipped tentacles, capable of squeezing through the smallest gaps.',
        attributes: {
          'size_ref': lookup('size', 'Small'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 3, 'hp_dice': '1d6', 'speed_walk_ft': 5, 'speed_swim_ft': 30,
          'stat_block': {'STR': 4, 'DEX': 15, 'CON': 11, 'INT': 3, 'WIS': 10, 'CHA': 4},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 12,
          'senses': [{'sense': 'Darkvision', 'range_ft': 30}],
          'trait_refs': [ref('trait', 'Hold Breath')],
          'action_refs': [ref('creature-action', 'Bite (Octopus)')],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Brown Bear',
        description:
            'A massive omnivore that wanders forests and mountain slopes, defending its territory with savage claws and a punishing bite.',
        attributes: {
          'size_ref': lookup('size', 'Large'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 11,
          'initiative_modifier': 1,
          'initiative_score': 11,
          'hp_average': 34,
          'hp_dice': '4d10+12',
          'speed_walk_ft': 40,
          'speed_climb_ft': 30,
          'stat_block': {
            'STR': 19, 'DEX': 10, 'CON': 16, 'INT': 2, 'WIS': 13, 'CHA': 7,
          },
          'cr': '1',
          'xp': 200,
          'proficiency_bonus': 2,
          'passive_perception': 13,
          'trait_refs': [ref('trait', 'Keen Smell')],
          'action_refs': [
            ref('creature-action', 'Multiattack'),
            ref('creature-action', 'Bite (Brown Bear)'),
            ref('creature-action', 'Claws (Brown Bear)'),
          ],
        },
      ),
    ];
