// SRD 5.2.1 Animals (pp. 344–364). Animals share the monster stat-block
// shape but live under a separate slug so the Beast listing on p. 344
// filters cleanly. Sample shipped here: Wolf, Brown Bear. Full pass over
// the remaining ~75 animals is deferred — see plan.

import '_helpers.dart';

List<Map<String, dynamic>> srdAnimals() => [
      packEntity(
        slug: 'animal',
        name: 'Wolf',
        description:
            'A swift hunter with a haunting howl. Wolves run in packs and use coordination to bring down prey larger than themselves.',
        attributes: {
          'size_ref': lookup('size', 'Medium'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12,
          'initiative_modifier': 2,
          'initiative_score': 12,
          'hp_average': 11,
          'hp_dice': '2d8+2',
          'speed_walk_ft': 40,
          'stat_block': {
            'STR': 12, 'DEX': 15, 'CON': 12, 'INT': 3, 'WIS': 12, 'CHA': 6,
          },
          'cr': '1/4',
          'xp': 50,
          'proficiency_bonus': 2,
          'passive_perception': 13,
          'trait_refs': [
            ref('trait', 'Pack Tactics'),
            ref('trait', 'Keen Smell'),
            ref('trait', 'Keen Hearing'),
          ],
          'action_refs': [
            ref('creature-action', 'Bite (Wolf)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Giant Eagle',
        description:
            'A noble raptor of mountain heights, larger than a horse and intelligent enough to speak in Auran and Common.',
        attributes: {
          'size_ref': lookup('size', 'Large'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Neutral Good'),
          'ac': 13,
          'initiative_modifier': 3,
          'initiative_score': 13,
          'hp_average': 26,
          'hp_dice': '4d10+4',
          'speed_walk_ft': 10,
          'speed_fly_ft': 80,
          'stat_block': {
            'STR': 16, 'DEX': 17, 'CON': 13, 'INT': 8, 'WIS': 14, 'CHA': 10,
          },
          'cr': '1',
          'xp': 200,
          'proficiency_bonus': 2,
          'passive_perception': 16,
          'language_refs': [lookup('language', 'Common')],
          'trait_refs': [ref('trait', 'Keen Sight')],
          'action_refs': [
            ref('creature-action', 'Multiattack'),
            ref('creature-action', 'Talons (Giant Eagle)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Dire Wolf',
        description:
            'A wolf as large as a riding horse, with a shaggy coat and bone-crushing jaws. Dire wolves run in packs and are favored mounts of goblin chiefs.',
        attributes: {
          'size_ref': lookup('size', 'Large'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 14,
          'initiative_modifier': 2,
          'initiative_score': 12,
          'hp_average': 22,
          'hp_dice': '3d10+6',
          'speed_walk_ft': 50,
          'stat_block': {
            'STR': 17, 'DEX': 15, 'CON': 15, 'INT': 3, 'WIS': 12, 'CHA': 7,
          },
          'cr': '1',
          'xp': 200,
          'proficiency_bonus': 2,
          'passive_perception': 13,
          'trait_refs': [
            ref('trait', 'Pack Tactics'),
            ref('trait', 'Keen Smell'),
            ref('trait', 'Keen Hearing'),
          ],
          'action_refs': [
            ref('creature-action', 'Bite (Dire Wolf)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Tiger',
        description:
            'A solitary apex predator of jungles and grasslands. The tiger stalks prey from cover, then pounces with terrible speed.',
        attributes: {
          'size_ref': lookup('size', 'Large'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 13,
          'initiative_modifier': 3,
          'initiative_score': 13,
          'hp_average': 30,
          'hp_dice': '4d10+8',
          'speed_walk_ft': 40,
          'stat_block': {
            'STR': 17, 'DEX': 16, 'CON': 14, 'INT': 3, 'WIS': 12, 'CHA': 8,
          },
          'cr': '1',
          'xp': 200,
          'proficiency_bonus': 2,
          'passive_perception': 13,
          'senses': [
            {'sense': 'Darkvision', 'range_ft': 60},
          ],
          'trait_refs': [ref('trait', 'Pounce')],
          'action_refs': [
            ref('creature-action', 'Bite (Tiger)'),
          ],
          'bonus_action_refs': [
            ref('creature-action', 'Claws (Tiger)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Lion',
        description:
            'The royal predator of the savanna, hunting in coordinated prides. A lion charges from cover and uses its weight to pin prey.',
        attributes: {
          'size_ref': lookup('size', 'Large'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12,
          'initiative_modifier': 2,
          'initiative_score': 12,
          'hp_average': 26,
          'hp_dice': '4d10+4',
          'speed_walk_ft': 50,
          'stat_block': {
            'STR': 17, 'DEX': 15, 'CON': 13, 'INT': 3, 'WIS': 12, 'CHA': 8,
          },
          'cr': '1',
          'xp': 200,
          'proficiency_bonus': 2,
          'passive_perception': 13,
          'trait_refs': [
            ref('trait', 'Pack Tactics'),
            ref('trait', 'Pounce'),
            ref('trait', 'Keen Smell'),
            ref('trait', 'Running Leap'),
          ],
          'action_refs': [
            ref('creature-action', 'Bite (Lion)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Crocodile',
        description:
            'A scaled ambush predator of rivers and swamps, dragging its prey beneath the water to drown.',
        attributes: {
          'size_ref': lookup('size', 'Large'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12,
          'initiative_modifier': 0,
          'initiative_score': 10,
          'hp_average': 19,
          'hp_dice': '3d10+3',
          'speed_walk_ft': 20,
          'speed_swim_ft': 30,
          'stat_block': {
            'STR': 15, 'DEX': 10, 'CON': 13, 'INT': 2, 'WIS': 10, 'CHA': 5,
          },
          'cr': '1/2',
          'xp': 100,
          'proficiency_bonus': 2,
          'passive_perception': 10,
          'trait_refs': [ref('trait', 'Hold Breath')],
          'action_refs': [
            ref('creature-action', 'Bite (Crocodile)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Boar',
        description:
            'A bristly forest pig with sharp tusks. Boars charge straight at threats and gore them with surprising power.',
        attributes: {
          'size_ref': lookup('size', 'Medium'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 11,
          'initiative_modifier': 0,
          'initiative_score': 10,
          'hp_average': 11,
          'hp_dice': '2d8+2',
          'speed_walk_ft': 40,
          'stat_block': {
            'STR': 13, 'DEX': 11, 'CON': 12, 'INT': 2, 'WIS': 9, 'CHA': 5,
          },
          'cr': '1/4',
          'xp': 50,
          'proficiency_bonus': 2,
          'passive_perception': 9,
          'trait_refs': [ref('trait', 'Charge')],
          'action_refs': [
            ref('creature-action', 'Tusk (Boar)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Mastiff',
        description:
            'A large hunting hound, loyal and fierce. Mastiffs are favored as guard dogs and battlefield companions.',
        attributes: {
          'size_ref': lookup('size', 'Medium'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12,
          'initiative_modifier': 2,
          'initiative_score': 12,
          'hp_average': 5,
          'hp_dice': '1d8+1',
          'speed_walk_ft': 40,
          'stat_block': {
            'STR': 13, 'DEX': 14, 'CON': 12, 'INT': 3, 'WIS': 12, 'CHA': 7,
          },
          'cr': '1/8',
          'xp': 25,
          'proficiency_bonus': 2,
          'passive_perception': 13,
          'trait_refs': [ref('trait', 'Keen Hearing'), ref('trait', 'Keen Smell')],
          'action_refs': [
            ref('creature-action', 'Bite (Mastiff)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Riding Horse',
        description:
            'A common steed bred for endurance and steadiness in travel. Most adventurers acquire one for the road.',
        attributes: {
          'size_ref': lookup('size', 'Large'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 10,
          'initiative_modifier': 0,
          'initiative_score': 10,
          'hp_average': 13,
          'hp_dice': '2d10+2',
          'speed_walk_ft': 60,
          'stat_block': {
            'STR': 16, 'DEX': 10, 'CON': 12, 'INT': 2, 'WIS': 11, 'CHA': 7,
          },
          'cr': '1/4',
          'xp': 50,
          'proficiency_bonus': 2,
          'passive_perception': 10,
          'action_refs': [
            ref('creature-action', 'Hooves (Riding Horse)'),
          ],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Cat',
        description: 'A common house cat, swift and aloof.',
        attributes: {
          'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 2, 'hp_dice': '1d4', 'speed_walk_ft': 40, 'speed_climb_ft': 30,
          'stat_block': {'STR': 3, 'DEX': 15, 'CON': 10, 'INT': 3, 'WIS': 12, 'CHA': 7},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 13,
          'trait_refs': [ref('trait', 'Keen Smell')],
          'action_refs': [ref('creature-action', 'Bite (Cat)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Rat',
        description: 'A small disease-carrying rodent of city sewers and old grain stores.',
        attributes: {
          'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 10, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 1, 'hp_dice': '1d4-1', 'speed_walk_ft': 20,
          'stat_block': {'STR': 2, 'DEX': 11, 'CON': 9, 'INT': 2, 'WIS': 10, 'CHA': 4},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 10,
          'senses': [{'sense': 'Darkvision', 'range_ft': 30}],
          'trait_refs': [ref('trait', 'Keen Smell')],
          'action_refs': [ref('creature-action', 'Bite (Rat)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Giant Rat',
        description: 'A wolf-sized rodent with mangy fur and yellowed teeth, found in dungeons and sewers.',
        attributes: {
          'size_ref': lookup('size', 'Small'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 7, 'hp_dice': '2d6', 'speed_walk_ft': 30,
          'stat_block': {'STR': 7, 'DEX': 15, 'CON': 11, 'INT': 2, 'WIS': 10, 'CHA': 4},
          'cr': '1/8', 'xp': 25, 'proficiency_bonus': 2, 'passive_perception': 10,
          'senses': [{'sense': 'Darkvision', 'range_ft': 60}],
          'trait_refs': [ref('trait', 'Keen Smell'), ref('trait', 'Pack Tactics')],
          'action_refs': [ref('creature-action', 'Bite (Giant Rat)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Hawk',
        description: 'A small raptor with keen eyes, common to many lands.',
        attributes: {
          'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 13, 'initiative_modifier': 3, 'initiative_score': 13,
          'hp_average': 1, 'hp_dice': '1d4-1', 'speed_walk_ft': 10, 'speed_fly_ft': 60,
          'stat_block': {'STR': 5, 'DEX': 16, 'CON': 8, 'INT': 2, 'WIS': 14, 'CHA': 6},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 14,
          'trait_refs': [ref('trait', 'Keen Sight')],
          'action_refs': [ref('creature-action', 'Talons (Hawk)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Eagle',
        description: 'A keen-eyed bird of prey of mountains and open lands.',
        attributes: {
          'size_ref': lookup('size', 'Small'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 3, 'hp_dice': '1d6', 'speed_walk_ft': 10, 'speed_fly_ft': 60,
          'stat_block': {'STR': 6, 'DEX': 15, 'CON': 10, 'INT': 2, 'WIS': 14, 'CHA': 7},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 14,
          'trait_refs': [ref('trait', 'Keen Sight')],
          'action_refs': [ref('creature-action', 'Talons (Eagle)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Owl',
        description: 'A nocturnal raptor that hunts in silence.',
        attributes: {
          'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 11, 'initiative_modifier': 1, 'initiative_score': 11,
          'hp_average': 1, 'hp_dice': '1d4-1', 'speed_walk_ft': 5, 'speed_fly_ft': 60,
          'stat_block': {'STR': 3, 'DEX': 13, 'CON': 8, 'INT': 2, 'WIS': 12, 'CHA': 7},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 13,
          'senses': [{'sense': 'Darkvision', 'range_ft': 120}],
          'trait_refs': [ref('trait', 'Flyby'), ref('trait', 'Keen Hearing'), ref('trait', 'Keen Sight')],
          'action_refs': [ref('creature-action', 'Bite (Owl)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Pony',
        description: 'A small horse breed favored by halflings and gnomes.',
        attributes: {
          'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 10, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 11, 'hp_dice': '2d8+2', 'speed_walk_ft': 40,
          'stat_block': {'STR': 15, 'DEX': 10, 'CON': 13, 'INT': 2, 'WIS': 11, 'CHA': 7},
          'cr': '1/8', 'xp': 25, 'proficiency_bonus': 2, 'passive_perception': 10,
          'action_refs': [ref('creature-action', 'Bite (Pony)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Camel',
        description: 'A hardy desert beast of burden capable of many days without water.',
        attributes: {
          'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 9, 'initiative_modifier': -1, 'initiative_score': 9,
          'hp_average': 15, 'hp_dice': '2d10+4', 'speed_walk_ft': 50,
          'stat_block': {'STR': 16, 'DEX': 8, 'CON': 14, 'INT': 2, 'WIS': 8, 'CHA': 5},
          'cr': '1/8', 'xp': 25, 'proficiency_bonus': 2, 'passive_perception': 9,
          'action_refs': [ref('creature-action', 'Bite (Camel)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Elephant',
        description: 'A massive grass-eating mammal that defends its herd with charging tusks.',
        attributes: {
          'size_ref': lookup('size', 'Huge'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 76, 'hp_dice': '8d12+24', 'speed_walk_ft': 40,
          'stat_block': {'STR': 22, 'DEX': 9, 'CON': 17, 'INT': 3, 'WIS': 11, 'CHA': 6},
          'cr': '4', 'xp': 1100, 'proficiency_bonus': 2, 'passive_perception': 10,
          'trait_refs': [ref('trait', 'Charge'), ref('trait', 'Siege Monster')],
          'action_refs': [ref('creature-action', 'Multiattack'), ref('creature-action', 'Stomp (Elephant)'), ref('creature-action', 'Gore (Elephant)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Ape',
        description: 'A great forest ape that lives in family bands and defends its territory with thrown rocks.',
        attributes: {
          'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 19, 'hp_dice': '3d8+6', 'speed_walk_ft': 30, 'speed_climb_ft': 30,
          'stat_block': {'STR': 16, 'DEX': 14, 'CON': 14, 'INT': 6, 'WIS': 12, 'CHA': 7},
          'cr': '1/2', 'xp': 100, 'proficiency_bonus': 2, 'passive_perception': 13,
          'action_refs': [ref('creature-action', 'Multiattack'), ref('creature-action', 'Fist (Ape)'), ref('creature-action', 'Rock (Ape)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Constrictor Snake',
        description: 'A large serpent that subdues prey by squeezing it to death.',
        attributes: {
          'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 13, 'hp_dice': '2d10+2', 'speed_walk_ft': 30, 'speed_swim_ft': 30,
          'stat_block': {'STR': 15, 'DEX': 14, 'CON': 12, 'INT': 1, 'WIS': 10, 'CHA': 3},
          'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 10,
          'senses': [{'sense': 'Blindsight', 'range_ft': 10}],
          'action_refs': [ref('creature-action', 'Bite (Constrictor)'), ref('creature-action', 'Constrict (Constrictor)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Giant Constrictor Snake',
        description: 'An enormous serpent capable of crushing the largest prey.',
        attributes: {
          'size_ref': lookup('size', 'Huge'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 60, 'hp_dice': '8d12+8', 'speed_walk_ft': 30, 'speed_swim_ft': 30,
          'stat_block': {'STR': 19, 'DEX': 14, 'CON': 12, 'INT': 1, 'WIS': 10, 'CHA': 3},
          'cr': '2', 'xp': 450, 'proficiency_bonus': 2, 'passive_perception': 12,
          'senses': [{'sense': 'Blindsight', 'range_ft': 10}],
          'action_refs': [ref('creature-action', 'Bite (Giant Snake)'), ref('creature-action', 'Constrict (Constrictor)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Frog',
        description: 'A small amphibian found in marshes and ponds.',
        attributes: {
          'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 11, 'initiative_modifier': 1, 'initiative_score': 11,
          'hp_average': 1, 'hp_dice': '1d4-1', 'speed_walk_ft': 20, 'speed_swim_ft': 20,
          'stat_block': {'STR': 1, 'DEX': 13, 'CON': 8, 'INT': 1, 'WIS': 8, 'CHA': 3},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 9,
          'senses': [{'sense': 'Darkvision', 'range_ft': 30}],
          'trait_refs': [ref('trait', 'Amphibious'), ref('trait', 'Standing Leap')],
          'action_refs': [ref('creature-action', 'Bite (Frog)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Giant Frog',
        description: 'A horse-sized frog that lurks in fetid pools, swallowing prey whole.',
        attributes: {
          'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 11, 'initiative_modifier': 1, 'initiative_score': 11,
          'hp_average': 18, 'hp_dice': '4d8', 'speed_walk_ft': 30, 'speed_swim_ft': 30,
          'stat_block': {'STR': 12, 'DEX': 13, 'CON': 11, 'INT': 2, 'WIS': 10, 'CHA': 3},
          'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 12,
          'senses': [{'sense': 'Darkvision', 'range_ft': 30}],
          'trait_refs': [ref('trait', 'Amphibious'), ref('trait', 'Standing Leap')],
          'action_refs': [ref('creature-action', 'Bite (Giant Frog)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Giant Centipede',
        description: 'A car-sized arthropod with venomous bite, lurking in dark caves.',
        attributes: {
          'size_ref': lookup('size', 'Small'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 13, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 4, 'hp_dice': '1d6+1', 'speed_walk_ft': 30, 'speed_climb_ft': 30,
          'stat_block': {'STR': 5, 'DEX': 14, 'CON': 12, 'INT': 1, 'WIS': 7, 'CHA': 3},
          'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 8,
          'senses': [{'sense': 'Blindsight', 'range_ft': 30}],
          'action_refs': [ref('creature-action', 'Bite (Giant Centipede)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Giant Lizard',
        description: 'A donkey-sized reptile, often used as a mount or beast of burden in the Underdark.',
        attributes: {
          'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 19, 'hp_dice': '3d10+3', 'speed_walk_ft': 30, 'speed_climb_ft': 30,
          'stat_block': {'STR': 15, 'DEX': 12, 'CON': 13, 'INT': 2, 'WIS': 10, 'CHA': 5},
          'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 10,
          'senses': [{'sense': 'Darkvision', 'range_ft': 30}],
          'action_refs': [ref('creature-action', 'Bite (Giant Lizard)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Polar Bear',
        description: 'A massive white bear of arctic regions, hunting seals and the unwary.',
        attributes: {
          'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 42, 'hp_dice': '5d10+15', 'speed_walk_ft': 40, 'speed_swim_ft': 30,
          'stat_block': {'STR': 20, 'DEX': 10, 'CON': 16, 'INT': 2, 'WIS': 13, 'CHA': 7},
          'cr': '2', 'xp': 450, 'proficiency_bonus': 2, 'passive_perception': 13,
          'trait_refs': [ref('trait', 'Keen Smell'), ref('trait', 'Snow Camouflage')],
          'action_refs': [ref('creature-action', 'Multiattack'), ref('creature-action', 'Bite (Polar Bear)'), ref('creature-action', 'Claws (Polar Bear)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Warhorse',
        description: 'A heavy horse trained for battle, faster and more aggressive than a riding horse.',
        attributes: {
          'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 11, 'initiative_modifier': 1, 'initiative_score': 11,
          'hp_average': 19, 'hp_dice': '3d10+3', 'speed_walk_ft': 60,
          'stat_block': {'STR': 18, 'DEX': 12, 'CON': 13, 'INT': 2, 'WIS': 12, 'CHA': 7},
          'cr': '1/2', 'xp': 100, 'proficiency_bonus': 2, 'passive_perception': 11,
          'trait_refs': [ref('trait', 'Charge')],
          'action_refs': [ref('creature-action', 'Hooves (Warhorse)')],
        },
      ),
      packEntity(
        slug: 'animal', name: 'Octopus',
        description: 'A small cephalopod with sucker-tipped tentacles, capable of squeezing through the smallest gaps.',
        attributes: {
          'size_ref': lookup('size', 'Small'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 3, 'hp_dice': '1d6', 'speed_walk_ft': 5, 'speed_swim_ft': 30,
          'stat_block': {'STR': 4, 'DEX': 15, 'CON': 11, 'INT': 3, 'WIS': 10, 'CHA': 4},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 12,
          'senses': [{'sense': 'Darkvision', 'range_ft': 30}],
          'trait_refs': [ref('trait', 'Hold Breath')],
          'action_refs': [ref('creature-action', 'Bite (Octopus)')],
        },
      ),
      packEntity(
        slug: 'animal',
        name: 'Brown Bear',
        description:
            'A massive omnivore that wanders forests and mountain slopes, defending its territory with savage claws and a punishing bite.',
        attributes: {
          'size_ref': lookup('size', 'Large'),
          'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 11,
          'initiative_modifier': 1,
          'initiative_score': 11,
          'hp_average': 34,
          'hp_dice': '4d10+12',
          'speed_walk_ft': 40,
          'speed_climb_ft': 30,
          'stat_block': {
            'STR': 19, 'DEX': 10, 'CON': 16, 'INT': 2, 'WIS': 13, 'CHA': 7,
          },
          'cr': '1',
          'xp': 200,
          'proficiency_bonus': 2,
          'passive_perception': 13,
          'trait_refs': [ref('trait', 'Keen Smell')],
          'action_refs': [
            ref('creature-action', 'Multiattack'),
            ref('creature-action', 'Bite (Brown Bear)'),
            ref('creature-action', 'Claws (Brown Bear)'),
          ],
        },
      ),

      // ─── Tyrannosaurus Rex (CR 8) ────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Tyrannosaurus Rex',
        description: 'A colossal apex predator dinosaur with massive jaws and surprisingly small forelimbs.',
        attributes: {
          'size_ref': lookup('size', 'Huge'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 13, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 136, 'hp_dice': '13d12+52', 'speed_walk_ft': 50,
          'stat_block': {'STR': 25, 'DEX': 10, 'CON': 19, 'INT': 2, 'WIS': 12, 'CHA': 9},
          'cr': '8', 'xp': 3900, 'proficiency_bonus': 3, 'passive_perception': 14,
          'action_refs': [
            ref('creature-action', 'Multiattack'),
            ref('creature-action', 'Bite (T-Rex)'),
            ref('creature-action', 'Tail (T-Rex)'),
          ],
        },
      ),

      // ─── Triceratops (CR 5) ──────────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Triceratops',
        description: 'A heavy-bodied herbivorous dinosaur with three horns and a bony frill protecting its neck.',
        attributes: {
          'size_ref': lookup('size', 'Huge'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 13, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 95, 'hp_dice': '10d12+30', 'speed_walk_ft': 50,
          'stat_block': {'STR': 22, 'DEX': 9, 'CON': 17, 'INT': 2, 'WIS': 11, 'CHA': 5},
          'cr': '5', 'xp': 1800, 'proficiency_bonus': 3, 'passive_perception': 10,
          'trait_refs': [ref('trait', 'Trampling Charge')],
          'action_refs': [
            ref('creature-action', 'Multiattack'),
            ref('creature-action', 'Gore (Triceratops)'),
            ref('creature-action', 'Stomp (Triceratops)'),
          ],
        },
      ),

      // ─── Allosaurus (CR 2) ───────────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Allosaurus',
        description: 'A swift bipedal predator dinosaur, smaller than a tyrannosaurus but no less savage.',
        attributes: {
          'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 13, 'initiative_modifier': 1, 'initiative_score': 11,
          'hp_average': 51, 'hp_dice': '6d10+18', 'speed_walk_ft': 60,
          'stat_block': {'STR': 19, 'DEX': 13, 'CON': 17, 'INT': 2, 'WIS': 12, 'CHA': 5},
          'cr': '2', 'xp': 450, 'proficiency_bonus': 2, 'passive_perception': 15,
          'trait_refs': [ref('trait', 'Pounce')],
          'action_refs': [
            ref('creature-action', 'Multiattack'),
            ref('creature-action', 'Bite (Allosaurus)'),
          ],
        },
      ),

      // ─── Pteranodon (CR 1/4) ─────────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Pteranodon',
        description: 'A flying reptile with a long beak and a wingspan greater than a Medium humanoid is tall.',
        attributes: {
          'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 13, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 13, 'hp_dice': '3d8', 'speed_walk_ft': 10, 'speed_fly_ft': 60,
          'stat_block': {'STR': 12, 'DEX': 15, 'CON': 10, 'INT': 2, 'WIS': 9, 'CHA': 5},
          'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 9,
          'trait_refs': [ref('trait', 'Flyby')],
          'action_refs': [
            ref('creature-action', 'Bite (Pteranodon)'),
          ],
        },
      ),

      // ─── Plesiosaurus (CR 2) ─────────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Plesiosaurus',
        description: 'A long-necked aquatic reptile that hunts the deep waters of prehistoric seas.',
        attributes: {
          'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 13, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 68, 'hp_dice': '8d10+24', 'speed_walk_ft': 20, 'speed_swim_ft': 40,
          'stat_block': {'STR': 18, 'DEX': 15, 'CON': 16, 'INT': 2, 'WIS': 12, 'CHA': 5},
          'cr': '2', 'xp': 450, 'proficiency_bonus': 2, 'passive_perception': 15,
          'trait_refs': [ref('trait', 'Hold Breath (Crocodile)')],
          'action_refs': [
            ref('creature-action', 'Bite (Plesiosaurus)'),
          ],
        },
      ),

      // ─── Mammoth (CR 6) ──────────────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Mammoth',
        description: 'A great shaggy elephant of cold climates, with massive curved tusks.',
        attributes: {
          'size_ref': lookup('size', 'Huge'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 13, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 126, 'hp_dice': '11d12+55', 'speed_walk_ft': 40,
          'stat_block': {'STR': 24, 'DEX': 9, 'CON': 21, 'INT': 3, 'WIS': 11, 'CHA': 6},
          'cr': '6', 'xp': 2300, 'proficiency_bonus': 3, 'passive_perception': 10,
          'trait_refs': [ref('trait', 'Trampling Charge')],
          'action_refs': [
            ref('creature-action', 'Gore (Mammoth)'),
            ref('creature-action', 'Stomp (Mammoth)'),
          ],
        },
      ),

      // ─── Rhinoceros (CR 2) ───────────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Rhinoceros',
        description: 'A great herbivore with a single horn, known for an aggressive charge.',
        attributes: {
          'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 11, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 45, 'hp_dice': '6d10+12', 'speed_walk_ft': 40,
          'stat_block': {'STR': 21, 'DEX': 8, 'CON': 15, 'INT': 2, 'WIS': 12, 'CHA': 6},
          'cr': '2', 'xp': 450, 'proficiency_bonus': 2, 'passive_perception': 11,
          'trait_refs': [ref('trait', 'Charge')],
          'action_refs': [ref('creature-action', 'Gore (Rhinoceros)')],
        },
      ),

      // ─── Killer Whale (CR 3) ─────────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Killer Whale',
        description: 'A large oceanic apex predator. Despite the name, killer whales are intelligent and social.',
        attributes: {
          'size_ref': lookup('size', 'Huge'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 90, 'hp_dice': '12d12+12', 'speed_walk_ft': 0, 'speed_swim_ft': 60,
          'stat_block': {'STR': 19, 'DEX': 10, 'CON': 13, 'INT': 3, 'WIS': 12, 'CHA': 7},
          'cr': '3', 'xp': 700, 'proficiency_bonus': 2, 'passive_perception': 14,
          'senses': [{'sense': 'Blindsight', 'range_ft': 120}],
          'trait_refs': [
            ref('trait', 'Echolocation'),
            ref('trait', 'Hold Breath (Crocodile)'),
            ref('trait', 'Keen Hearing'),
          ],
          'action_refs': [ref('creature-action', 'Bite (Killer Whale)')],
        },
      ),

      // ─── Stirge (CR 1/8) ─────────────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Stirge',
        description: 'A bat-winged blood-drinking parasite the size of a small bird.',
        attributes: {
          'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 14, 'initiative_modifier': 3, 'initiative_score': 13,
          'hp_average': 5, 'hp_dice': '2d4', 'speed_walk_ft': 10, 'speed_fly_ft': 40,
          'stat_block': {'STR': 4, 'DEX': 16, 'CON': 11, 'INT': 2, 'WIS': 8, 'CHA': 6},
          'cr': '1/8', 'xp': 25, 'proficiency_bonus': 2, 'passive_perception': 9,
          'senses': [{'sense': 'Darkvision', 'range_ft': 60}],
          'action_refs': [ref('creature-action', 'Proboscis (Stirge)')],
        },
      ),

      // ─── Giant Crab (CR 1/8) ─────────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Giant Crab',
        description: 'A crab the size of a large dog, with massive crushing claws.',
        attributes: {
          'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 15, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 13, 'hp_dice': '3d8', 'speed_walk_ft': 30, 'speed_swim_ft': 30,
          'stat_block': {'STR': 13, 'DEX': 11, 'CON': 11, 'INT': 1, 'WIS': 9, 'CHA': 3},
          'cr': '1/8', 'xp': 25, 'proficiency_bonus': 2, 'passive_perception': 9,
          'senses': [{'sense': 'Blindsight', 'range_ft': 30}],
          'trait_refs': [ref('trait', 'Amphibious')],
          'action_refs': [ref('creature-action', 'Claw (Giant Crab)')],
        },
      ),

      // ─── Giant Octopus (CR 1) ────────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Giant Octopus',
        description: 'A massive cephalopod hunting in coastal seas.',
        attributes: {
          'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 11, 'initiative_modifier': 1, 'initiative_score': 11,
          'hp_average': 52, 'hp_dice': '8d10+8', 'speed_walk_ft': 10, 'speed_swim_ft': 60,
          'stat_block': {'STR': 17, 'DEX': 13, 'CON': 13, 'INT': 4, 'WIS': 10, 'CHA': 4},
          'cr': '1', 'xp': 200, 'proficiency_bonus': 2, 'passive_perception': 14,
          'senses': [{'sense': 'Darkvision', 'range_ft': 60}],
          'trait_refs': [
            ref('trait', 'Hold Breath (Crocodile)'),
            ref('trait', 'Water Breathing'),
          ],
          'action_refs': [ref('creature-action', 'Tentacles (Giant Octopus)')],
        },
      ),

      // ─── Giant Shark (CR 5) ──────────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Giant Shark',
        description: 'A 30-foot apex predator of the deep, scenting prey miles away.',
        attributes: {
          'size_ref': lookup('size', 'Huge'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 13, 'initiative_modifier': 1, 'initiative_score': 11,
          'hp_average': 126, 'hp_dice': '11d12+55', 'speed_walk_ft': 0, 'speed_swim_ft': 50,
          'stat_block': {'STR': 23, 'DEX': 11, 'CON': 21, 'INT': 1, 'WIS': 10, 'CHA': 5},
          'cr': '5', 'xp': 1800, 'proficiency_bonus': 3, 'passive_perception': 13,
          'senses': [{'sense': 'Blindsight', 'range_ft': 60}],
          'trait_refs': [
            ref('trait', 'Blood Frenzy'),
            ref('trait', 'Water Breathing'),
          ],
          'action_refs': [ref('creature-action', 'Bite (Giant Shark)')],
        },
      ),

      // ─── Hunter Shark (CR 2) ─────────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Hunter Shark',
        description: 'A solitary deep-water shark, dangerous and aggressive.',
        attributes: {
          'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 1, 'initiative_score': 11,
          'hp_average': 45, 'hp_dice': '6d10+12', 'speed_walk_ft': 0, 'speed_swim_ft': 40,
          'stat_block': {'STR': 18, 'DEX': 13, 'CON': 15, 'INT': 1, 'WIS': 10, 'CHA': 4},
          'cr': '2', 'xp': 450, 'proficiency_bonus': 2, 'passive_perception': 12,
          'senses': [{'sense': 'Blindsight', 'range_ft': 30}],
          'trait_refs': [
            ref('trait', 'Blood Frenzy'),
            ref('trait', 'Water Breathing'),
          ],
          'action_refs': [ref('creature-action', 'Bite (Hunter Shark)')],
        },
      ),

      // ─── Reef Shark (CR 1/2) ─────────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Reef Shark',
        description: 'A smaller predatory shark of warm coastal waters, often hunting in groups.',
        attributes: {
          'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 22, 'hp_dice': '4d8+4', 'speed_walk_ft': 0, 'speed_swim_ft': 40,
          'stat_block': {'STR': 14, 'DEX': 13, 'CON': 13, 'INT': 1, 'WIS': 10, 'CHA': 4},
          'cr': '1/2', 'xp': 100, 'proficiency_bonus': 2, 'passive_perception': 12,
          'senses': [{'sense': 'Blindsight', 'range_ft': 30}],
          'trait_refs': [
            ref('trait', 'Pack Tactics'),
            ref('trait', 'Water Breathing'),
          ],
          'action_refs': [ref('creature-action', 'Bite (Reef Shark)')],
        },
      ),

      // ─── Quipper (CR 0) ──────────────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Quipper',
        description: 'A small carnivorous fish that hunts in vicious swarms.',
        attributes: {
          'size_ref': lookup('size', 'Small'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 13, 'initiative_modifier': 3, 'initiative_score': 13,
          'hp_average': 1, 'hp_dice': '1d4', 'speed_walk_ft': 0, 'speed_swim_ft': 40,
          'stat_block': {'STR': 2, 'DEX': 16, 'CON': 9, 'INT': 1, 'WIS': 7, 'CHA': 2},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 8,
          'senses': [{'sense': 'Darkvision', 'range_ft': 60}],
          'trait_refs': [
            ref('trait', 'Blood Frenzy'),
            ref('trait', 'Water Breathing'),
          ],
          'action_refs': [ref('creature-action', 'Bite (Quipper)')],
        },
      ),

      // ─── Swarm of Bats (CR 1/4) ─────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Swarm of Bats',
        description: 'A cloud of fluttering bats moves and attacks as a single creature.',
        attributes: {
          'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 22, 'hp_dice': '5d8', 'speed_walk_ft': 0, 'speed_fly_ft': 30,
          'stat_block': {'STR': 5, 'DEX': 15, 'CON': 10, 'INT': 2, 'WIS': 12, 'CHA': 4},
          'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 11,
          'senses': [{'sense': 'Blindsight', 'range_ft': 60}],
          'resistance_refs': [
            lookup('damage-type', 'Bludgeoning'),
            lookup('damage-type', 'Piercing'),
            lookup('damage-type', 'Slashing'),
          ],
          'condition_immunity_refs': [
            lookup('condition', 'Charmed'),
            lookup('condition', 'Frightened'),
            lookup('condition', 'Grappled'),
            lookup('condition', 'Paralyzed'),
            lookup('condition', 'Petrified'),
            lookup('condition', 'Prone'),
            lookup('condition', 'Restrained'),
            lookup('condition', 'Stunned'),
          ],
          'trait_refs': [
            ref('trait', 'Echolocation'),
            ref('trait', 'Keen Hearing'),
            ref('trait', 'Swarm'),
          ],
          'action_refs': [ref('creature-action', 'Bites (Swarm of Bats)')],
        },
      ),

      // ─── Swarm of Insects (CR 1/2) ──────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Swarm of Insects',
        description: 'A horde of biting, stinging, or burrowing insects acts as one creature.',
        attributes: {
          'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12,
          'hp_average': 22, 'hp_dice': '5d8', 'speed_walk_ft': 20, 'speed_climb_ft': 20,
          'stat_block': {'STR': 3, 'DEX': 13, 'CON': 10, 'INT': 1, 'WIS': 7, 'CHA': 1},
          'cr': '1/2', 'xp': 100, 'proficiency_bonus': 2, 'passive_perception': 8,
          'senses': [{'sense': 'Blindsight', 'range_ft': 10}],
          'resistance_refs': [
            lookup('damage-type', 'Bludgeoning'),
            lookup('damage-type', 'Piercing'),
            lookup('damage-type', 'Slashing'),
          ],
          'condition_immunity_refs': [
            lookup('condition', 'Charmed'),
            lookup('condition', 'Frightened'),
            lookup('condition', 'Grappled'),
            lookup('condition', 'Paralyzed'),
            lookup('condition', 'Petrified'),
            lookup('condition', 'Prone'),
            lookup('condition', 'Restrained'),
            lookup('condition', 'Stunned'),
          ],
          'trait_refs': [ref('trait', 'Swarm')],
          'action_refs': [ref('creature-action', 'Bites (Swarm of Insects)')],
        },
      ),

      // ─── Swarm of Rats (CR 1/4) ─────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Swarm of Rats',
        description: 'A boiling mass of rats — small, fast, and dangerous in numbers.',
        attributes: {
          'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 10, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 24, 'hp_dice': '7d8-7', 'speed_walk_ft': 30,
          'stat_block': {'STR': 9, 'DEX': 11, 'CON': 9, 'INT': 2, 'WIS': 10, 'CHA': 3},
          'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 10,
          'senses': [{'sense': 'Darkvision', 'range_ft': 30}],
          'resistance_refs': [
            lookup('damage-type', 'Bludgeoning'),
            lookup('damage-type', 'Piercing'),
            lookup('damage-type', 'Slashing'),
          ],
          'condition_immunity_refs': [
            lookup('condition', 'Charmed'),
            lookup('condition', 'Frightened'),
            lookup('condition', 'Grappled'),
            lookup('condition', 'Paralyzed'),
            lookup('condition', 'Petrified'),
            lookup('condition', 'Prone'),
            lookup('condition', 'Restrained'),
            lookup('condition', 'Stunned'),
          ],
          'trait_refs': [
            ref('trait', 'Keen Smell'),
            ref('trait', 'Swarm'),
          ],
          'action_refs': [ref('creature-action', 'Bites (Swarm of Rats)')],
        },
      ),

      // ─── Swarm of Quippers (CR 1) ───────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Swarm of Quippers',
        description: 'A school of carnivorous fish that strips prey to bone in moments.',
        attributes: {
          'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 13, 'initiative_modifier': 3, 'initiative_score': 13,
          'hp_average': 28, 'hp_dice': '8d8-8', 'speed_walk_ft': 0, 'speed_swim_ft': 40,
          'stat_block': {'STR': 13, 'DEX': 16, 'CON': 9, 'INT': 1, 'WIS': 7, 'CHA': 2},
          'cr': '1', 'xp': 200, 'proficiency_bonus': 2, 'passive_perception': 8,
          'senses': [{'sense': 'Darkvision', 'range_ft': 60}],
          'resistance_refs': [
            lookup('damage-type', 'Bludgeoning'),
            lookup('damage-type', 'Piercing'),
            lookup('damage-type', 'Slashing'),
          ],
          'condition_immunity_refs': [
            lookup('condition', 'Charmed'),
            lookup('condition', 'Frightened'),
            lookup('condition', 'Grappled'),
            lookup('condition', 'Paralyzed'),
            lookup('condition', 'Petrified'),
            lookup('condition', 'Prone'),
            lookup('condition', 'Restrained'),
            lookup('condition', 'Stunned'),
          ],
          'trait_refs': [
            ref('trait', 'Blood Frenzy'),
            ref('trait', 'Swarm'),
            ref('trait', 'Water Breathing'),
          ],
          'action_refs': [ref('creature-action', 'Bites (Swarm of Quippers)')],
        },
      ),

      // ─── Vulture (CR 0) ──────────────────────────────────────────────────
      packEntity(
        slug: 'animal',
        name: 'Vulture',
        description: 'A scavenging bird with keen eyes and a strong beak.',
        attributes: {
          'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'),
          'alignment_ref': lookup('alignment', 'Unaligned'),
          'ac': 10, 'initiative_modifier': 0, 'initiative_score': 10,
          'hp_average': 5, 'hp_dice': '1d8+1', 'speed_walk_ft': 10, 'speed_fly_ft': 50,
          'stat_block': {'STR': 7, 'DEX': 10, 'CON': 13, 'INT': 2, 'WIS': 12, 'CHA': 4},
          'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 13,
          'trait_refs': [
            ref('trait', 'Keen Sight and Smell'),
            ref('trait', 'Pack Tactics'),
          ],
          'action_refs': [ref('creature-action', 'Talons (Hawk)')],
        },
      ),

      // ─── Animal roster — batch 1 (compact entries) ───────────────────────
      packEntity(slug: 'animal', name: 'Ankylosaurus', description: 'A massive armored herbivorous dinosaur with a heavy clubbed tail.', attributes: {'size_ref': lookup('size', 'Huge'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 15, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 68, 'hp_dice': '8d12+16', 'speed_walk_ft': 30, 'stat_block': {'STR': 19, 'DEX': 11, 'CON': 15, 'INT': 2, 'WIS': 12, 'CHA': 5}, 'cr': '3', 'xp': 700, 'proficiency_bonus': 2, 'passive_perception': 11, 'action_refs': [ref('creature-action', 'Tail (Ankylosaurus)')]}),
      packEntity(slug: 'animal', name: 'Archelon', description: 'An immense prehistoric sea turtle with a hardened shell.', attributes: {'size_ref': lookup('size', 'Huge'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 17, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 90, 'hp_dice': '12d12+12', 'speed_walk_ft': 20, 'speed_swim_ft': 40, 'stat_block': {'STR': 19, 'DEX': 10, 'CON': 13, 'INT': 2, 'WIS': 11, 'CHA': 4}, 'cr': '4', 'xp': 1100, 'proficiency_bonus': 2, 'passive_perception': 10, 'trait_refs': [ref('trait', 'Hold Breath (Crocodile)')], 'action_refs': [ref('creature-action', 'Bite (Archelon)')]}),
      packEntity(slug: 'animal', name: 'Baboon', description: 'A medium primate with sharp teeth and quick reflexes that travels in troops.', attributes: {'size_ref': lookup('size', 'Small'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 12, 'initiative_modifier': 1, 'initiative_score': 11, 'hp_average': 3, 'hp_dice': '1d6', 'speed_walk_ft': 30, 'speed_climb_ft': 30, 'stat_block': {'STR': 8, 'DEX': 14, 'CON': 11, 'INT': 4, 'WIS': 12, 'CHA': 6}, 'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 11, 'trait_refs': [ref('trait', 'Pack Tactics')], 'action_refs': [ref('creature-action', 'Bite (Baboon)')]}),
      packEntity(slug: 'animal', name: 'Badger', description: 'A small burrowing mammal with strong claws and a tenacious bite.', attributes: {'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 10, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 3, 'hp_dice': '1d4+1', 'speed_walk_ft': 20, 'stat_block': {'STR': 4, 'DEX': 11, 'CON': 12, 'INT': 2, 'WIS': 12, 'CHA': 5}, 'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 13, 'senses': [{'sense': 'Darkvision', 'range_ft': 30}], 'trait_refs': [ref('trait', 'Keen Smell')], 'action_refs': [ref('creature-action', 'Bite (Badger)')]}),
      packEntity(slug: 'animal', name: 'Bat', description: 'A flying mammal that navigates using echolocation.', attributes: {'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12, 'hp_average': 1, 'hp_dice': '1d4-1', 'speed_walk_ft': 5, 'speed_fly_ft': 30, 'stat_block': {'STR': 2, 'DEX': 15, 'CON': 8, 'INT': 2, 'WIS': 12, 'CHA': 4}, 'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 11, 'senses': [{'sense': 'Blindsight', 'range_ft': 60}], 'trait_refs': [ref('trait', 'Echolocation'), ref('trait', 'Keen Hearing')], 'action_refs': [ref('creature-action', 'Bite (Bat)')]}),
      packEntity(slug: 'animal', name: 'Black Bear', description: 'A medium-sized bear common in forested regions, fierce when threatened.', attributes: {'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 11, 'initiative_modifier': 1, 'initiative_score': 11, 'hp_average': 19, 'hp_dice': '3d8+6', 'speed_walk_ft': 40, 'speed_climb_ft': 30, 'stat_block': {'STR': 15, 'DEX': 10, 'CON': 14, 'INT': 2, 'WIS': 12, 'CHA': 7}, 'cr': '1/2', 'xp': 100, 'proficiency_bonus': 2, 'passive_perception': 13, 'trait_refs': [ref('trait', 'Keen Smell')], 'action_refs': [ref('creature-action', 'Multiattack'), ref('creature-action', 'Bite (Black Bear)'), ref('creature-action', 'Claws (Black Bear)')]}),
      packEntity(slug: 'animal', name: 'Blood Hawk', description: 'A predatory bird that hunts in flocks for prey larger than itself.', attributes: {'size_ref': lookup('size', 'Small'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12, 'hp_average': 7, 'hp_dice': '2d6', 'speed_walk_ft': 10, 'speed_fly_ft': 60, 'stat_block': {'STR': 6, 'DEX': 14, 'CON': 10, 'INT': 3, 'WIS': 14, 'CHA': 5}, 'cr': '1/8', 'xp': 25, 'proficiency_bonus': 2, 'passive_perception': 14, 'trait_refs': [ref('trait', 'Keen Sight'), ref('trait', 'Pack Tactics')], 'action_refs': [ref('creature-action', 'Beak (Blood Hawk)')]}),
      packEntity(slug: 'animal', name: 'Crab', description: 'A small crustacean common in coastal areas.', attributes: {'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 11, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 2, 'hp_dice': '1d4', 'speed_walk_ft': 20, 'speed_swim_ft': 20, 'stat_block': {'STR': 2, 'DEX': 11, 'CON': 10, 'INT': 1, 'WIS': 8, 'CHA': 2}, 'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 9, 'senses': [{'sense': 'Blindsight', 'range_ft': 30}], 'trait_refs': [ref('trait', 'Amphibious')], 'action_refs': [ref('creature-action', 'Claws (Crab)')]}),
      packEntity(slug: 'animal', name: 'Deer', description: 'A graceful hoofed mammal common in woodlands.', attributes: {'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 13, 'initiative_modifier': 3, 'initiative_score': 13, 'hp_average': 4, 'hp_dice': '1d8', 'speed_walk_ft': 50, 'stat_block': {'STR': 11, 'DEX': 16, 'CON': 11, 'INT': 2, 'WIS': 14, 'CHA': 5}, 'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 12, 'action_refs': [ref('creature-action', 'Ram (Deer)')]}),
      packEntity(slug: 'animal', name: 'Draft Horse', description: 'A large working horse bred for hauling.', attributes: {'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 10, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 19, 'hp_dice': '3d10+3', 'speed_walk_ft': 40, 'stat_block': {'STR': 18, 'DEX': 10, 'CON': 12, 'INT': 2, 'WIS': 11, 'CHA': 7}, 'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 10, 'trait_refs': [ref('trait', 'Beast of Burden')], 'action_refs': [ref('creature-action', 'Hooves (Draft Horse)')]}),
      packEntity(slug: 'animal', name: 'Elk', description: 'A large deer with imposing antlers, capable of charging foes.', attributes: {'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 10, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 13, 'hp_dice': '2d10+2', 'speed_walk_ft': 50, 'stat_block': {'STR': 16, 'DEX': 10, 'CON': 12, 'INT': 2, 'WIS': 10, 'CHA': 6}, 'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 12, 'action_refs': [ref('creature-action', 'Ram (Elk)'), ref('creature-action', 'Hooves (Elk)')]}),
      packEntity(slug: 'animal', name: 'Flying Snake', description: 'A small winged serpent with venomous fangs.', attributes: {'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 14, 'initiative_modifier': 4, 'initiative_score': 14, 'hp_average': 5, 'hp_dice': '2d4', 'speed_walk_ft': 30, 'speed_fly_ft': 60, 'speed_swim_ft': 30, 'stat_block': {'STR': 4, 'DEX': 18, 'CON': 11, 'INT': 2, 'WIS': 12, 'CHA': 5}, 'cr': '1/8', 'xp': 25, 'proficiency_bonus': 2, 'passive_perception': 11, 'senses': [{'sense': 'Blindsight', 'range_ft': 10}], 'trait_refs': [ref('trait', 'Flyby')], 'action_refs': [ref('creature-action', 'Bite (Flying Snake)')]}),
      packEntity(slug: 'animal', name: 'Giant Ape', description: 'A massive primate of jungle and mountain, capable of hurling boulders.', attributes: {'size_ref': lookup('size', 'Huge'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12, 'hp_average': 157, 'hp_dice': '15d12+60', 'speed_walk_ft': 40, 'speed_climb_ft': 40, 'stat_block': {'STR': 23, 'DEX': 14, 'CON': 18, 'INT': 7, 'WIS': 12, 'CHA': 7}, 'cr': '7', 'xp': 2900, 'proficiency_bonus': 3, 'passive_perception': 14, 'action_refs': [ref('creature-action', 'Multiattack'), ref('creature-action', 'Fist (Giant Ape)'), ref('creature-action', 'Rock (Giant Ape)')]}),
      packEntity(slug: 'animal', name: 'Giant Badger', description: 'An oversized badger that burrows aggressively.', attributes: {'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 10, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 13, 'hp_dice': '2d8+4', 'speed_walk_ft': 30, 'speed_burrow_ft': 10, 'stat_block': {'STR': 13, 'DEX': 10, 'CON': 15, 'INT': 2, 'WIS': 12, 'CHA': 5}, 'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 13, 'senses': [{'sense': 'Darkvision', 'range_ft': 30}], 'trait_refs': [ref('trait', 'Keen Smell')], 'action_refs': [ref('creature-action', 'Multiattack'), ref('creature-action', 'Bite (Badger)'), ref('creature-action', 'Claw (Giant Badger)')]}),
      packEntity(slug: 'animal', name: 'Giant Bat', description: 'A bat the size of a large dog, hunting in caves.', attributes: {'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 13, 'initiative_modifier': 3, 'initiative_score': 13, 'hp_average': 22, 'hp_dice': '4d10', 'speed_walk_ft': 10, 'speed_fly_ft': 60, 'stat_block': {'STR': 15, 'DEX': 16, 'CON': 11, 'INT': 2, 'WIS': 12, 'CHA': 6}, 'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 11, 'senses': [{'sense': 'Blindsight', 'range_ft': 60}], 'trait_refs': [ref('trait', 'Echolocation'), ref('trait', 'Keen Hearing')], 'action_refs': [ref('creature-action', 'Bite (Giant Bat)')]}),
      packEntity(slug: 'animal', name: 'Giant Boar', description: 'A massive wild pig with razor-sharp tusks and a savage charge.', attributes: {'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 12, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 42, 'hp_dice': '5d10+15', 'speed_walk_ft': 40, 'stat_block': {'STR': 17, 'DEX': 10, 'CON': 16, 'INT': 2, 'WIS': 7, 'CHA': 5}, 'cr': '2', 'xp': 450, 'proficiency_bonus': 2, 'passive_perception': 8, 'trait_refs': [ref('trait', 'Charge')], 'action_refs': [ref('creature-action', 'Tusk (Giant Boar)')]}),
      packEntity(slug: 'animal', name: 'Giant Crocodile', description: 'A monstrous reptile of riverbeds and swamps.', attributes: {'size_ref': lookup('size', 'Huge'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 14, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 85, 'hp_dice': '9d12+27', 'speed_walk_ft': 30, 'speed_swim_ft': 50, 'stat_block': {'STR': 21, 'DEX': 9, 'CON': 17, 'INT': 2, 'WIS': 10, 'CHA': 7}, 'cr': '5', 'xp': 1800, 'proficiency_bonus': 3, 'passive_perception': 10, 'trait_refs': [ref('trait', 'Hold Breath (Crocodile)')], 'action_refs': [ref('creature-action', 'Multiattack'), ref('creature-action', 'Bite (Giant Crocodile)'), ref('creature-action', 'Tail (Giant Crocodile)')]}),
      packEntity(slug: 'animal', name: 'Giant Elk', description: 'An enormous elk with majestic antlers and incredible speed.', attributes: {'size_ref': lookup('size', 'Huge'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 14, 'initiative_modifier': 2, 'initiative_score': 12, 'hp_average': 42, 'hp_dice': '5d12+10', 'speed_walk_ft': 60, 'stat_block': {'STR': 19, 'DEX': 16, 'CON': 14, 'INT': 7, 'WIS': 14, 'CHA': 10}, 'cr': '2', 'xp': 450, 'proficiency_bonus': 2, 'passive_perception': 14, 'action_refs': [ref('creature-action', 'Ram (Giant Elk)'), ref('creature-action', 'Hooves (Giant Elk)')]}),
      packEntity(slug: 'animal', name: 'Giant Fire Beetle', description: 'A glowing beetle that sheds light from luminescent glands.', attributes: {'size_ref': lookup('size', 'Small'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 13, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 4, 'hp_dice': '1d6+1', 'speed_walk_ft': 30, 'stat_block': {'STR': 8, 'DEX': 10, 'CON': 12, 'INT': 1, 'WIS': 7, 'CHA': 3}, 'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 8, 'senses': [{'sense': 'Darkvision', 'range_ft': 30}], 'trait_refs': [ref('trait', 'Light (Fire Beetle)')], 'action_refs': [ref('creature-action', 'Bite (Giant Fire Beetle)')]}),
      packEntity(slug: 'animal', name: 'Giant Goat', description: 'A massive goat capable of charging foes.', attributes: {'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 11, 'initiative_modifier': 1, 'initiative_score': 11, 'hp_average': 19, 'hp_dice': '3d10+3', 'speed_walk_ft': 40, 'stat_block': {'STR': 17, 'DEX': 11, 'CON': 12, 'INT': 3, 'WIS': 12, 'CHA': 6}, 'cr': '1/2', 'xp': 100, 'proficiency_bonus': 2, 'passive_perception': 11, 'trait_refs': [ref('trait', 'Charge'), ref('trait', 'Sure-Footed')], 'action_refs': [ref('creature-action', 'Ram (Giant Goat)')]}),
      packEntity(slug: 'animal', name: 'Giant Hyena', description: 'A monstrous hyena with bone-crushing jaws.', attributes: {'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12, 'hp_average': 45, 'hp_dice': '6d10+12', 'speed_walk_ft': 50, 'stat_block': {'STR': 16, 'DEX': 14, 'CON': 14, 'INT': 2, 'WIS': 12, 'CHA': 7}, 'cr': '1', 'xp': 200, 'proficiency_bonus': 2, 'passive_perception': 13, 'trait_refs': [ref('trait', 'Reckless')], 'action_refs': [ref('creature-action', 'Bite (Giant Hyena)')]}),
      packEntity(slug: 'animal', name: 'Giant Owl', description: 'A wise giant owl that speaks Common, Elvish, and Sylvan.', attributes: {'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Neutral'), 'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12, 'hp_average': 19, 'hp_dice': '3d10+3', 'speed_walk_ft': 5, 'speed_fly_ft': 60, 'stat_block': {'STR': 13, 'DEX': 15, 'CON': 12, 'INT': 8, 'WIS': 13, 'CHA': 10}, 'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 15, 'senses': [{'sense': 'Darkvision', 'range_ft': 120}], 'trait_refs': [ref('trait', 'Flyby'), ref('trait', 'Keen Hearing'), ref('trait', 'Keen Sight')], 'action_refs': [ref('creature-action', 'Talons (Giant Owl)')]}),
      packEntity(slug: 'animal', name: 'Giant Scorpion', description: 'A massive armored arachnid with deadly venom in its tail.', attributes: {'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 15, 'initiative_modifier': 1, 'initiative_score': 11, 'hp_average': 52, 'hp_dice': '7d10+14', 'speed_walk_ft': 40, 'stat_block': {'STR': 15, 'DEX': 13, 'CON': 15, 'INT': 1, 'WIS': 9, 'CHA': 3}, 'cr': '3', 'xp': 700, 'proficiency_bonus': 2, 'passive_perception': 9, 'senses': [{'sense': 'Blindsight', 'range_ft': 60}], 'action_refs': [ref('creature-action', 'Multiattack'), ref('creature-action', 'Sting (Giant Scorpion)'), ref('creature-action', 'Claw (Giant Scorpion)')]}),
      packEntity(slug: 'animal', name: 'Giant Seahorse', description: 'An enormous seahorse capable of charging through water.', attributes: {'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 13, 'initiative_modifier': 2, 'initiative_score': 12, 'hp_average': 16, 'hp_dice': '3d10', 'speed_walk_ft': 0, 'speed_swim_ft': 40, 'stat_block': {'STR': 12, 'DEX': 15, 'CON': 11, 'INT': 2, 'WIS': 12, 'CHA': 5}, 'cr': '1/2', 'xp': 100, 'proficiency_bonus': 2, 'passive_perception': 11, 'trait_refs': [ref('trait', 'Water Breathing (Animal)'), ref('trait', 'Charge')], 'action_refs': [ref('creature-action', 'Bite (Giant Seahorse)')]}),
      packEntity(slug: 'animal', name: 'Giant Spider', description: 'A horse-sized arachnid that spins enormous webs and ambushes prey.', attributes: {'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 14, 'initiative_modifier': 3, 'initiative_score': 13, 'hp_average': 26, 'hp_dice': '4d10+4', 'speed_walk_ft': 30, 'speed_climb_ft': 30, 'stat_block': {'STR': 14, 'DEX': 16, 'CON': 12, 'INT': 2, 'WIS': 11, 'CHA': 4}, 'cr': '1', 'xp': 200, 'proficiency_bonus': 2, 'passive_perception': 10, 'senses': [{'sense': 'Blindsight', 'range_ft': 10}, {'sense': 'Darkvision', 'range_ft': 60}], 'trait_refs': [ref('trait', 'Spider Climb'), ref('trait', 'Web Sense'), ref('trait', 'Web Walker')], 'action_refs': [ref('creature-action', 'Bite (Giant Spider)'), ref('creature-action', 'Web (Giant Spider)')]}),
      packEntity(slug: 'animal', name: 'Giant Toad', description: 'A massive toad that swallows prey whole.', attributes: {'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 11, 'initiative_modifier': 1, 'initiative_score': 11, 'hp_average': 39, 'hp_dice': '6d10+6', 'speed_walk_ft': 20, 'speed_swim_ft': 40, 'stat_block': {'STR': 15, 'DEX': 13, 'CON': 13, 'INT': 2, 'WIS': 10, 'CHA': 3}, 'cr': '1', 'xp': 200, 'proficiency_bonus': 2, 'passive_perception': 10, 'senses': [{'sense': 'Darkvision', 'range_ft': 30}], 'trait_refs': [ref('trait', 'Amphibious'), ref('trait', 'Standing Leap')], 'action_refs': [ref('creature-action', 'Bite (Giant Toad)')]}),
      packEntity(slug: 'animal', name: 'Giant Venomous Snake', description: 'A constrictor-sized serpent with deadly venom.', attributes: {'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 14, 'initiative_modifier': 4, 'initiative_score': 14, 'hp_average': 11, 'hp_dice': '2d8+2', 'speed_walk_ft': 30, 'speed_swim_ft': 30, 'stat_block': {'STR': 10, 'DEX': 18, 'CON': 13, 'INT': 2, 'WIS': 10, 'CHA': 3}, 'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 12, 'senses': [{'sense': 'Blindsight', 'range_ft': 10}], 'action_refs': [ref('creature-action', 'Bite (Giant Venomous Snake)')]}),
      packEntity(slug: 'animal', name: 'Giant Vulture', description: 'An enormous scavenger bird with limited intelligence.', attributes: {'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Neutral Evil'), 'ac': 10, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 22, 'hp_dice': '3d10+6', 'speed_walk_ft': 10, 'speed_fly_ft': 60, 'stat_block': {'STR': 15, 'DEX': 10, 'CON': 15, 'INT': 6, 'WIS': 12, 'CHA': 7}, 'cr': '1', 'xp': 200, 'proficiency_bonus': 2, 'passive_perception': 13, 'trait_refs': [ref('trait', 'Keen Sight and Smell'), ref('trait', 'Pack Tactics')], 'action_refs': [ref('creature-action', 'Multiattack'), ref('creature-action', 'Beak (Blood Hawk)'), ref('creature-action', 'Talons (Giant Vulture)')]}),
      packEntity(slug: 'animal', name: 'Giant Wasp', description: 'A horse-sized wasp with a paralyzing sting.', attributes: {'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12, 'hp_average': 13, 'hp_dice': '3d8', 'speed_walk_ft': 10, 'speed_fly_ft': 50, 'stat_block': {'STR': 10, 'DEX': 14, 'CON': 10, 'INT': 1, 'WIS': 10, 'CHA': 3}, 'cr': '1/2', 'xp': 100, 'proficiency_bonus': 2, 'passive_perception': 10, 'action_refs': [ref('creature-action', 'Sting (Giant Wasp)')]}),
      packEntity(slug: 'animal', name: 'Giant Weasel', description: 'A wolf-sized weasel with a quick bite.', attributes: {'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 13, 'initiative_modifier': 3, 'initiative_score': 13, 'hp_average': 9, 'hp_dice': '2d8', 'speed_walk_ft': 40, 'stat_block': {'STR': 11, 'DEX': 16, 'CON': 10, 'INT': 4, 'WIS': 12, 'CHA': 5}, 'cr': '1/8', 'xp': 25, 'proficiency_bonus': 2, 'passive_perception': 13, 'senses': [{'sense': 'Darkvision', 'range_ft': 60}], 'trait_refs': [ref('trait', 'Keen Hearing'), ref('trait', 'Keen Smell')], 'action_refs': [ref('creature-action', 'Bite (Giant Weasel)')]}),
      packEntity(slug: 'animal', name: 'Giant Wolf Spider', description: 'A wolf-sized hunting spider with venomous fangs.', attributes: {'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 13, 'initiative_modifier': 3, 'initiative_score': 13, 'hp_average': 11, 'hp_dice': '2d8+2', 'speed_walk_ft': 40, 'speed_climb_ft': 40, 'stat_block': {'STR': 12, 'DEX': 16, 'CON': 13, 'INT': 3, 'WIS': 12, 'CHA': 4}, 'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 13, 'senses': [{'sense': 'Blindsight', 'range_ft': 10}, {'sense': 'Darkvision', 'range_ft': 60}], 'trait_refs': [ref('trait', 'Spider Climb'), ref('trait', 'Web Sense'), ref('trait', 'Web Walker')], 'action_refs': [ref('creature-action', 'Bite (Giant Wolf Spider)')]}),
      packEntity(slug: 'animal', name: 'Goat', description: 'A common domesticated goat.', attributes: {'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 10, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 4, 'hp_dice': '1d8', 'speed_walk_ft': 40, 'stat_block': {'STR': 12, 'DEX': 10, 'CON': 11, 'INT': 2, 'WIS': 10, 'CHA': 5}, 'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 10, 'trait_refs': [ref('trait', 'Charge'), ref('trait', 'Sure-Footed')], 'action_refs': [ref('creature-action', 'Ram (Goat)')]}),
      packEntity(slug: 'animal', name: 'Hippopotamus', description: 'A massive semi-aquatic mammal with bone-crushing jaws.', attributes: {'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 12, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 76, 'hp_dice': '8d10+32', 'speed_walk_ft': 40, 'speed_swim_ft': 30, 'stat_block': {'STR': 21, 'DEX': 10, 'CON': 19, 'INT': 2, 'WIS': 10, 'CHA': 5}, 'cr': '4', 'xp': 1100, 'proficiency_bonus': 2, 'passive_perception': 10, 'trait_refs': [ref('trait', 'Hold Breath (Crocodile)')], 'action_refs': [ref('creature-action', 'Bite (Hippopotamus)')]}),
      packEntity(slug: 'animal', name: 'Hyena', description: 'A scavenging carnivore that hunts in cackling packs.', attributes: {'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 11, 'initiative_modifier': 1, 'initiative_score': 11, 'hp_average': 5, 'hp_dice': '1d8+1', 'speed_walk_ft': 50, 'stat_block': {'STR': 11, 'DEX': 13, 'CON': 12, 'INT': 2, 'WIS': 12, 'CHA': 5}, 'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 13, 'trait_refs': [ref('trait', 'Pack Tactics')], 'action_refs': [ref('creature-action', 'Bite (Hyena)')]}),
      packEntity(slug: 'animal', name: 'Jackal', description: 'A small wild canine that scavenges in groups.', attributes: {'size_ref': lookup('size', 'Small'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12, 'hp_average': 3, 'hp_dice': '1d6', 'speed_walk_ft': 40, 'stat_block': {'STR': 8, 'DEX': 15, 'CON': 11, 'INT': 3, 'WIS': 12, 'CHA': 6}, 'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 13, 'trait_refs': [ref('trait', 'Keen Hearing'), ref('trait', 'Keen Smell'), ref('trait', 'Pack Tactics')], 'action_refs': [ref('creature-action', 'Bite (Jackal)')]}),
      packEntity(slug: 'animal', name: 'Lizard', description: 'A small reptile common in warm climates.', attributes: {'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 10, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 2, 'hp_dice': '1d4', 'speed_walk_ft': 20, 'speed_climb_ft': 20, 'stat_block': {'STR': 2, 'DEX': 11, 'CON': 10, 'INT': 1, 'WIS': 8, 'CHA': 3}, 'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 9, 'senses': [{'sense': 'Darkvision', 'range_ft': 30}], 'action_refs': [ref('creature-action', 'Bite (Lizard)')]}),
      packEntity(slug: 'animal', name: 'Mule', description: 'A sturdy hybrid pack animal, common as a beast of burden.', attributes: {'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 10, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 11, 'hp_dice': '2d8+2', 'speed_walk_ft': 40, 'stat_block': {'STR': 14, 'DEX': 10, 'CON': 13, 'INT': 2, 'WIS': 10, 'CHA': 5}, 'cr': '1/8', 'xp': 25, 'proficiency_bonus': 2, 'passive_perception': 10, 'trait_refs': [ref('trait', 'Beast of Burden'), ref('trait', 'Sure-Footed')], 'action_refs': [ref('creature-action', 'Hooves (Mule)')]}),
      packEntity(slug: 'animal', name: 'Panther', description: 'A sleek black predator that ambushes prey from above.', attributes: {'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12, 'hp_average': 13, 'hp_dice': '3d8', 'speed_walk_ft': 50, 'speed_climb_ft': 40, 'stat_block': {'STR': 14, 'DEX': 15, 'CON': 10, 'INT': 3, 'WIS': 14, 'CHA': 7}, 'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 14, 'trait_refs': [ref('trait', 'Keen Smell')], 'action_refs': [ref('creature-action', 'Bite (Panther)'), ref('creature-action', 'Pounce (Panther)')]}),
      packEntity(slug: 'animal', name: 'Piranha', description: 'A toothy fish notorious for swarming prey.', attributes: {'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 13, 'initiative_modifier': 3, 'initiative_score': 13, 'hp_average': 1, 'hp_dice': '1d4-1', 'speed_walk_ft': 0, 'speed_swim_ft': 40, 'stat_block': {'STR': 2, 'DEX': 16, 'CON': 9, 'INT': 1, 'WIS': 7, 'CHA': 2}, 'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 8, 'senses': [{'sense': 'Darkvision', 'range_ft': 60}], 'trait_refs': [ref('trait', 'Blood Frenzy'), ref('trait', 'Water Breathing (Animal)')], 'action_refs': [ref('creature-action', 'Bite (Piranha)')]}),
      packEntity(slug: 'animal', name: 'Raven', description: 'A clever black bird capable of mimicking sounds.', attributes: {'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12, 'hp_average': 1, 'hp_dice': '1d4-1', 'speed_walk_ft': 10, 'speed_fly_ft': 50, 'stat_block': {'STR': 2, 'DEX': 14, 'CON': 8, 'INT': 4, 'WIS': 12, 'CHA': 6}, 'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 13, 'trait_refs': [ref('trait', 'Mimicry')], 'action_refs': [ref('creature-action', 'Beak (Raven)')]}),
      packEntity(slug: 'animal', name: 'Saber-Toothed Tiger', description: 'A prehistoric cat with massive saber-like fangs.', attributes: {'size_ref': lookup('size', 'Large'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12, 'hp_average': 52, 'hp_dice': '7d10+14', 'speed_walk_ft': 40, 'stat_block': {'STR': 18, 'DEX': 14, 'CON': 15, 'INT': 3, 'WIS': 12, 'CHA': 8}, 'cr': '2', 'xp': 450, 'proficiency_bonus': 2, 'passive_perception': 15, 'trait_refs': [ref('trait', 'Keen Smell')], 'action_refs': [ref('creature-action', 'Bite (Saber-Toothed Tiger)'), ref('creature-action', 'Claw (Saber-Toothed Tiger)')]}),
      packEntity(slug: 'animal', name: 'Scorpion', description: 'A small venomous arachnid with pincer claws and a stinger.', attributes: {'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 11, 'initiative_modifier': 0, 'initiative_score': 10, 'hp_average': 1, 'hp_dice': '1d4-1', 'speed_walk_ft': 10, 'stat_block': {'STR': 2, 'DEX': 11, 'CON': 8, 'INT': 1, 'WIS': 8, 'CHA': 2}, 'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 9, 'senses': [{'sense': 'Blindsight', 'range_ft': 10}], 'action_refs': [ref('creature-action', 'Sting (Scorpion)')]}),
      packEntity(slug: 'animal', name: 'Spider', description: 'A small spider with a weak venomous bite.', attributes: {'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12, 'hp_average': 1, 'hp_dice': '1d4-1', 'speed_walk_ft': 20, 'speed_climb_ft': 20, 'stat_block': {'STR': 2, 'DEX': 14, 'CON': 8, 'INT': 1, 'WIS': 10, 'CHA': 2}, 'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 12, 'senses': [{'sense': 'Darkvision', 'range_ft': 30}], 'trait_refs': [ref('trait', 'Spider Climb'), ref('trait', 'Web Walker')], 'action_refs': [ref('creature-action', 'Bite (Spider)')]}),
      packEntity(slug: 'animal', name: 'Venomous Snake', description: 'A small biting serpent with potent venom.', attributes: {'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12, 'hp_average': 5, 'hp_dice': '2d4', 'speed_walk_ft': 30, 'speed_swim_ft': 30, 'stat_block': {'STR': 2, 'DEX': 15, 'CON': 11, 'INT': 1, 'WIS': 10, 'CHA': 3}, 'cr': '1/8', 'xp': 25, 'proficiency_bonus': 2, 'passive_perception': 10, 'senses': [{'sense': 'Blindsight', 'range_ft': 10}], 'action_refs': [ref('creature-action', 'Bite (Venomous Snake)')]}),
      packEntity(slug: 'animal', name: 'Weasel', description: 'A small ferret-like predator.', attributes: {'size_ref': lookup('size', 'Tiny'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 13, 'initiative_modifier': 3, 'initiative_score': 13, 'hp_average': 1, 'hp_dice': '1d4-1', 'speed_walk_ft': 30, 'speed_climb_ft': 30, 'stat_block': {'STR': 3, 'DEX': 16, 'CON': 8, 'INT': 2, 'WIS': 12, 'CHA': 3}, 'cr': '0', 'xp': 10, 'proficiency_bonus': 2, 'passive_perception': 13, 'senses': [{'sense': 'Darkvision', 'range_ft': 60}], 'action_refs': [ref('creature-action', 'Bite (Weasel)')]}),
      packEntity(slug: 'animal', name: 'Swarm of Piranhas', description: 'A frenzied school of piranhas that strips prey to bones in seconds.', attributes: {'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 13, 'initiative_modifier': 3, 'initiative_score': 13, 'hp_average': 28, 'hp_dice': '8d8-8', 'speed_walk_ft': 0, 'speed_swim_ft': 40, 'stat_block': {'STR': 13, 'DEX': 16, 'CON': 9, 'INT': 1, 'WIS': 7, 'CHA': 2}, 'cr': '1', 'xp': 200, 'proficiency_bonus': 2, 'passive_perception': 8, 'senses': [{'sense': 'Darkvision', 'range_ft': 60}], 'resistance_refs': [lookup('damage-type', 'Bludgeoning'), lookup('damage-type', 'Piercing'), lookup('damage-type', 'Slashing')], 'condition_immunity_refs': [lookup('condition', 'Charmed'), lookup('condition', 'Frightened'), lookup('condition', 'Grappled'), lookup('condition', 'Paralyzed'), lookup('condition', 'Petrified'), lookup('condition', 'Prone'), lookup('condition', 'Restrained'), lookup('condition', 'Stunned')], 'trait_refs': [ref('trait', 'Blood Frenzy'), ref('trait', 'Swarm'), ref('trait', 'Water Breathing (Animal)')], 'action_refs': [ref('creature-action', 'Bites (Swarm of Piranhas)')]}),
      packEntity(slug: 'animal', name: 'Swarm of Ravens', description: 'A flock of mimicking ravens that descends in a deafening cloud.', attributes: {'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 12, 'initiative_modifier': 2, 'initiative_score': 12, 'hp_average': 24, 'hp_dice': '7d8-7', 'speed_walk_ft': 10, 'speed_fly_ft': 50, 'stat_block': {'STR': 6, 'DEX': 14, 'CON': 8, 'INT': 4, 'WIS': 12, 'CHA': 6}, 'cr': '1/4', 'xp': 50, 'proficiency_bonus': 2, 'passive_perception': 15, 'resistance_refs': [lookup('damage-type', 'Bludgeoning'), lookup('damage-type', 'Piercing'), lookup('damage-type', 'Slashing')], 'condition_immunity_refs': [lookup('condition', 'Charmed'), lookup('condition', 'Frightened'), lookup('condition', 'Grappled'), lookup('condition', 'Paralyzed'), lookup('condition', 'Petrified'), lookup('condition', 'Prone'), lookup('condition', 'Restrained'), lookup('condition', 'Stunned')], 'trait_refs': [ref('trait', 'Swarm')], 'action_refs': [ref('creature-action', 'Beaks (Swarm of Ravens)')]}),
      packEntity(slug: 'animal', name: 'Swarm of Venomous Snakes', description: 'A writhing knot of venomous snakes that surges across the ground.', attributes: {'size_ref': lookup('size', 'Medium'), 'creature_type_ref': lookup('creature-type', 'Beast'), 'alignment_ref': lookup('alignment', 'Unaligned'), 'ac': 14, 'initiative_modifier': 4, 'initiative_score': 14, 'hp_average': 36, 'hp_dice': '8d8', 'speed_walk_ft': 30, 'speed_swim_ft': 30, 'stat_block': {'STR': 8, 'DEX': 18, 'CON': 11, 'INT': 1, 'WIS': 10, 'CHA': 3}, 'cr': '2', 'xp': 450, 'proficiency_bonus': 2, 'passive_perception': 10, 'senses': [{'sense': 'Blindsight', 'range_ft': 10}], 'resistance_refs': [lookup('damage-type', 'Bludgeoning'), lookup('damage-type', 'Piercing'), lookup('damage-type', 'Slashing')], 'condition_immunity_refs': [lookup('condition', 'Charmed'), lookup('condition', 'Frightened'), lookup('condition', 'Grappled'), lookup('condition', 'Paralyzed'), lookup('condition', 'Petrified'), lookup('condition', 'Prone'), lookup('condition', 'Restrained'), lookup('condition', 'Stunned')], 'trait_refs': [ref('trait', 'Swarm')], 'action_refs': [ref('creature-action', 'Bites (Swarm of Venomous Snakes)')]}),
    ];
