// SRD kartlarının tag'leri — `buildSrdCorePack` satırlara basar.
//
// Tag'ler seçicinin (`entity_search.dart`) iki işine yarar:
//  * Sınıf / tür / geçmiş adı ("wizard", "elf", "criminal") → kartta o
//    sınıf varsa satır "Önerilen"e düşer. Kaynak: sınıfın başlangıç
//    ekipmanı, eğitim/ön koşul, geçmişin origin feat'i.
//  * Geri kalanı ("heavy", "finesse", "healing", "undead", "forest")
//    aramada bulunur — lookup ref'ler (Light/Heavy, okul, hasar tipi,
//    yaratık tipi) uuid olduğu için aramaya düşmez, o yüzden burada.
// Satır başına 2–5. Büyüde: rol + hasar tipi + ritual + okul; canavarda:
// tip + alt tip + yaşam alanı/aile + legendary/wild shape. Ön koşul metni
// zaten sınıf adı geçiren kartlara aynı adı tekrar yazmıyoruz; büyüler
// sınıfa `class_refs` ile bağlı, o yüzden sınıf tag'i yok.
// Bilerek kaçınılan kelimeler: geçmiş/alt sınıf adları ("guard", "guide",
// "hunter", "sage"…) yalnızca o bağlamda önerilmesi gerekiyorsa.

const _arcane = ['focus', 'arcane', 'sorcerer', 'warlock', 'wizard'];
const _druidic = ['focus', 'druidic', 'druid', 'ranger'];
const _holy = ['focus', 'holy symbol', 'cleric', 'paladin'];
const _caster = ['spellcasting', 'wizard', 'sorcerer', 'cleric', 'druid'];
const _blaster = ['spellcasting', 'wizard', 'sorcerer', 'warlock'];
const _martial = ['fighter', 'paladin', 'barbarian', 'ranger', 'rogue'];
const _knight = ['fighter', 'paladin'];
const _heavyMagic = ['heavy', 'defense', 'fighter', 'paladin'];
const _armorMagic = ['defense', 'fighter', 'paladin', 'cleric'];
const _archer = ['ranger', 'fighter'];
const _strength = ['strength', 'barbarian', 'fighter'];
const _beasts = ['druid', 'ranger'];
const _elementals = ['elemental', 'druid', 'wizard'];
const _camp = ['camping', 'travel'];
const _climb = ['climbing', 'exploration'];
const _box = ['container', 'storage'];
const _lightSource = ['illumination', 'light source'];
const _mount = ['mount', 'riding'];
const _scribe = ['writing', 'scribe'];
const _instrument = ['instrument', 'bard'];
const _gaming = ['gaming', 'guard', 'noble', 'wayfarer'];

const srdTags = <String, Map<String, List<String>>>{
  'armor': {
    'Padded Armor': ['light', 'cheap'],
    'Leather Armor': ['light', 'rogue', 'bard', 'warlock', 'druid'],
    'Studded Leather Armor': ['light', 'rogue', 'ranger', 'fighter', 'bard'],
    'Hide Armor': ['medium', 'barbarian', 'druid'],
    'Chain Shirt': ['medium', 'cleric', 'ranger'],
    'Scale Mail': ['medium', 'cleric', 'barbarian'],
    'Breastplate': ['medium', 'cleric', 'ranger', 'barbarian'],
    'Half Plate Armor': ['medium', 'cleric', 'barbarian'],
    'Ring Mail': ['heavy', 'cheap'],
    'Chain Mail': ['heavy', 'fighter', 'paladin'],
    'Splint Armor': ['heavy', 'fighter', 'paladin'],
    'Plate Armor': ['heavy', 'fighter', 'paladin'],
    'Shield': ['defense', 'fighter', 'paladin', 'cleric', 'druid'],
  },
  'weapon': {
    'Club': ['simple', 'druid'],
    'Dagger': ['simple', 'finesse', 'thrown', 'rogue', 'wizard'],
    'Greatclub': ['simple', 'two-handed'],
    'Handaxe': ['simple', 'thrown', 'barbarian'],
    'Javelin': ['simple', 'thrown', 'fighter', 'paladin'],
    'Light Hammer': ['simple', 'thrown'],
    'Mace': ['simple', 'cleric'],
    'Quarterstaff': ['simple', 'wizard', 'druid', 'monk'],
    'Sickle': ['simple', 'druid', 'warlock'],
    'Spear': ['simple', 'thrown', 'monk', 'sorcerer'],
    'Dart': ['simple', 'ranged', 'finesse', 'thrown'],
    'Light Crossbow': ['simple', 'ranged'],
    'Shortbow': ['simple', 'ranged', 'rogue', 'ranger'],
    'Sling': ['simple', 'ranged'],
    'Battleaxe': ['martial', 'versatile'],
    'Flail': ['martial', 'fighter'],
    'Glaive': ['martial', 'two-handed', 'reach'],
    'Greataxe': ['martial', 'two-handed', 'barbarian'],
    'Greatsword': ['martial', 'two-handed', 'fighter', 'paladin'],
    'Halberd': ['martial', 'two-handed', 'reach'],
    'Lance': ['martial', 'reach', 'mount'],
    'Longsword': ['martial', 'versatile', 'fighter', 'paladin'],
    'Maul': ['martial', 'two-handed', 'barbarian'],
    'Morningstar': ['martial', 'piercing'],
    'Pike': ['martial', 'two-handed', 'reach'],
    'Rapier': ['martial', 'finesse', 'rogue', 'bard'],
    'Scimitar': ['martial', 'finesse', 'ranger', 'rogue'],
    'Shortsword': ['martial', 'finesse', 'rogue', 'ranger', 'monk'],
    'Trident': ['martial', 'thrown'],
    'Warhammer': ['martial', 'versatile'],
    'War Pick': ['martial', 'piercing'],
    'Whip': ['martial', 'finesse', 'reach'],
    'Blowgun': ['martial', 'ranged'],
    'Hand Crossbow': ['martial', 'ranged', 'rogue'],
    'Heavy Crossbow': ['martial', 'ranged', 'two-handed'],
    'Longbow': ['martial', 'ranged', 'ranger', 'fighter'],
    'Musket': ['martial', 'ranged', 'firearm'],
    'Pistol': ['martial', 'ranged', 'firearm'],
  },
  'ammunition': {
    'Arrows': ['bow', 'ranger'],
    'Bolts': ['crossbow', 'ranged'],
    'Bullets, Firearm': ['firearm', 'ranged'],
    'Bullets, Sling': ['sling', 'ranged'],
    'Needles': ['blowgun', 'ranged'],
  },
  'adventuring-gear': {
    'Acid': ['thrown', 'alchemy'],
    "Alchemist's Fire": ['thrown', 'fire', 'alchemy'],
    'Antitoxin': ['poison', 'cure'],
    'Backpack': _box,
    'Ball Bearings': ['traps', 'rogue'],
    'Barrel': _box,
    'Basket': _box,
    'Bedroll': _camp,
    'Bell': ['alarm', 'signal'],
    'Blanket': _camp,
    'Block and Tackle': ['lifting', 'utility'],
    'Book': ['sage', 'acolyte', 'warlock'],
    'Bottle, Glass': _box,
    'Bucket': _box,
    'Caltrops': ['traps', 'rogue'],
    'Candle': _lightSource,
    'Case, Crossbow Bolt': ['container', 'crossbow'],
    'Case, Map or Scroll': _box,
    'Chain': ['restraint', 'climbing'],
    'Chalk': ['marking', 'exploration'],
    'Chest': _box,
    "Climber's Kit": _climb,
    'Clothes, Fine': ['clothing', 'noble'],
    "Clothes, Traveler's": ['clothing', 'travel'],
    'Component Pouch': ['spellcasting', 'wizard', 'sorcerer', 'warlock', 'bard'],
    'Costume': ['clothing', 'disguise', 'entertainer', 'charlatan'],
    'Crowbar': ['rogue', 'criminal'],
    "Burglar's Pack": ['rogue', 'thief'],
    "Diplomat's Pack": ['noble', 'social'],
    "Dungeoneer's Pack": ['fighter', 'sorcerer'],
    "Entertainer's Pack": ['bard', 'entertainer'],
    "Explorer's Pack": ['barbarian', 'druid', 'monk', 'ranger'],
    'Fishing Tackle': ['food', 'camping'],
    'Flask': _box,
    'Grappling Hook': _climb,
    'Hammer': ['tools', 'climbing'],
    "Healer's Kit": ['healing', 'medicine'],
    'Holy Water': ['thrown', 'undead', 'cleric', 'paladin'],
    'Hourglass': ['timekeeping', 'utility'],
    'Hunting Trap': ['traps', 'ranger'],
    'Ink': _scribe,
    'Ink Pen': _scribe,
    'Jug': _box,
    'Ladder': _climb,
    'Lamp': _lightSource,
    'Lantern, Bullseye': _lightSource,
    'Lantern, Hooded': _lightSource,
    'Lock': ['security', 'door'],
    'Magnifying Glass': ['investigation', 'fire'],
    'Manacles': ['restraint', 'guard'],
    'Map': ['navigation', 'guide'],
    'Mess Kit': _camp,
    'Mirror': ['utility', 'signal'],
    'Net': ['thrown', 'restraint'],
    'Oil': ['illumination', 'fire'],
    'Paper': _scribe,
    'Parchment': _scribe,
    'Perfume': ['noble', 'social'],
    "Pick, Miner's": ['digging', 'mining'],
    'Piton': _climb,
    'Poison, Basic': ['poison', 'rogue'],
    'Pole': ['utility', 'exploration'],
    'Pot, Iron': _camp,
    'Potion of Healing': ['healing', 'potion'],
    'Pouch': _box,
    "Priest's Pack": ['cleric', 'paladin', 'acolyte'],
    'Quiver': ['container', 'bow', 'ranger'],
    'Ram, Portable': ['breaching', 'strength'],
    'Rations': ['food', 'camping'],
    'Robe': ['clothing', 'wizard', 'acolyte', 'sage', 'hermit'],
    'Rope': _climb,
    'Sack': _box,
    "Scale, Merchant's": ['merchant', 'trade'],
    "Scholar's Pack": ['wizard', 'warlock', 'sage'],
    'Sealing Wax': _scribe,
    'Shovel': ['digging', 'camping'],
    'Signal Whistle': ['alarm', 'signal'],
    'Signet Ring': ['noble', 'seal'],
    'Soap': ['hygiene', 'utility'],
    'Spell Scroll (Cantrip)': ['spellcasting', 'scroll'],
    'Spell Scroll (Level 1)': ['spellcasting', 'scroll'],
    'Spellbook': ['spellcasting', 'wizard'],
    'Spikes, Iron': ['climbing', 'utility'],
    'Spyglass': ['navigation', 'vision'],
    'String': ['utility', 'traps'],
    'Tent': _camp,
    'Tinderbox': ['fire', 'camping'],
    'Torch': _lightSource,
    'Vial': _box,
    'Waterskin': _camp,
    'Whetstone': ['maintenance', 'weapons'],
    'Saddle, Exotic': _mount,
    'Saddle, Military': _mount,
    'Saddle, Riding': _mount,
    'Feed': _mount,
    'Stabling': _mount,
    'Crystal': _arcane,
    'Orb': _arcane,
    'Rod': _arcane,
    'Staff (Arcane Focus)': _arcane,
    'Wand (Arcane Focus)': _arcane,
    'Sprig of Mistletoe': _druidic,
    'Wooden Staff (Druidic Focus)': _druidic,
    'Yew Wand': _druidic,
    'Amulet (Holy Symbol)': _holy,
    'Emblem (Holy Symbol)': _holy,
    'Reliquary': _holy,
  },
  'pack': {
    "Burglar's Pack": ['rogue', 'thief'],
    "Diplomat's Pack": ['noble', 'social'],
    "Dungeoneer's Pack": ['fighter', 'sorcerer'],
    "Entertainer's Pack": ['bard', 'entertainer'],
    "Explorer's Pack": ['barbarian', 'druid', 'monk', 'ranger'],
    "Priest's Pack": ['cleric', 'paladin', 'acolyte'],
    "Scholar's Pack": ['wizard', 'warlock', 'sage'],
  },
  'tool': {
    // "artisan" → Artisan geçmişi bir zanaat aleti seçer.
    "Alchemist's Supplies": ['artisan', 'alchemy'],
    "Brewer's Supplies": ['artisan', 'brewing'],
    "Calligrapher's Supplies": ['writing', 'acolyte', 'sage', 'scribe'],
    "Carpenter's Tools": ['artisan', 'farmer'],
    "Cartographer's Tools": ['navigation', 'guide'],
    "Cobbler's Tools": ['artisan', 'leather'],
    "Cook's Utensils": ['artisan', 'food'],
    "Glassblower's Tools": ['artisan', 'glass'],
    "Jeweler's Tools": ['artisan', 'gems'],
    "Leatherworker's Tools": ['artisan', 'leather'],
    "Mason's Tools": ['artisan', 'stone'],
    "Painter's Supplies": ['artisan', 'art'],
    "Potter's Tools": ['artisan', 'clay'],
    "Smith's Tools": ['artisan', 'metal', 'repair'],
    "Tinker's Tools": ['artisan', 'repair'],
    "Weaver's Tools": ['artisan', 'cloth'],
    "Woodcarver's Tools": ['artisan', 'wood'],
    'Disguise Kit': ['disguise', 'charlatan', 'rogue'],
    'Forgery Kit': ['charlatan', 'criminal'],
    'Herbalism Kit': ['healing', 'druid', 'hermit'],
    "Navigator's Tools": ['navigation', 'sailor', 'merchant'],
    "Poisoner's Kit": ['poison', 'rogue'],
    "Thieves' Tools": ['lockpicking', 'rogue', 'thief', 'criminal', 'wayfarer'],
    'Gaming Set': _gaming,
    'Dice Set': _gaming,
    'Dragonchess Set': _gaming,
    'Playing Card Set': _gaming,
    'Three-Dragon Ante Set': _gaming,
    'Bagpipes': _instrument,
    'Drum': _instrument,
    'Dulcimer': _instrument,
    'Flute': ['instrument', 'bard', 'entertainer'],
    'Horn': _instrument,
    'Lute': _instrument,
    'Lyre': _instrument,
    'Pan Flute': _instrument,
    'Shawm': _instrument,
    'Viol': _instrument,
  },
  'mount': {
    'Camel': ['riding', 'desert'],
    'Elephant': ['riding', 'war'],
    'Draft Horse': ['riding', 'hauling'],
    'Riding Horse': ['riding', 'travel'],
    // Küçük boylar için binek.
    'Mastiff': ['riding', 'halfling', 'gnome'],
    'Mule': ['riding', 'hauling'],
    'Pony': ['riding', 'halfling', 'gnome'],
    'Warhorse': ['riding', 'war', 'paladin'],
  },
  'vehicle': {
    'Carriage': ['land', 'travel'],
    'Cart': ['land', 'hauling'],
    'Chariot': ['land', 'war'],
    'Sled': ['land', 'arctic'],
    'Wagon': ['land', 'hauling'],
    'Galley': ['water', 'ship'],
    'Keelboat': ['water', 'river'],
    'Longship': ['water', 'ship'],
    'Rowboat': ['water', 'boat'],
    'Sailing Ship': ['water', 'ship', 'sailor'],
    'Warship': ['water', 'ship', 'war'],
    'Airship': ['air', 'flight'],
  },
  'magic-item': {
    // Defense
    'Cloak of Protection': ['defense', 'saving throw'],
    'Ring of Protection': ['defense', 'saving throw'],
    'Bracers of Defense': ['defense', 'monk', 'wizard', 'sorcerer'],
    'Brooch of Shielding': ['defense', 'force'],
    'Cloak of Displacement': ['defense', 'illusion'],
    'Cloak of Resistance': ['defense', 'resistance'],
    'Ring of Resistance': ['defense', 'resistance'],
    'Ring of Spell Turning': ['defense', 'anti-magic'],
    'Mantle of Spell Resistance': ['defense', 'anti-magic'],
    'Periapt of Proof against Poison': ['defense', 'poison'],
    'Periapt of Proof Against Poison': ['defense', 'poison'],
    'Scarab of Protection': ['defense', 'undead'],
    'Stone of Good Luck (Luckstone)': ['luck', 'saving throw'],
    'Robe of the Archmagi': ['defense', 'spellcasting'],
    'Cube of Force': ['defense', 'force'],
    'Necklace of Adaptation': ['defense', 'breathing'],
    'Ring of Mind Shielding': ['defense', 'telepathy'],
    'Instant Fortress': ['shelter', 'defense'],
    // Armor & shields
    'Armor, +1': _armorMagic,
    'Armor, +2': _armorMagic,
    'Armor, +3': _armorMagic,
    'Shield, +1': _armorMagic,
    'Shield, +2': _armorMagic,
    'Shield, +3': _armorMagic,
    'Plate Armor of Etherealness': _heavyMagic,
    'Adamantine Armor': _heavyMagic,
    'Armor of Resistance': _heavyMagic,
    'Armor of Invulnerability': _heavyMagic,
    'Dwarven Plate': ['heavy', 'defense', 'dwarf', 'fighter', 'paladin'],
    'Demon Armor': ['heavy', 'cursed', 'fighter', 'paladin'],
    'Armor of Vulnerability': ['heavy', 'cursed'],
    'Mithral Armor': ['medium', 'defense', 'cleric', 'ranger'],
    'Dragon Scale Mail': ['medium', 'defense', 'dragonborn', 'cleric'],
    'Glamoured Studded Leather': ['light', 'disguise', 'rogue', 'bard'],
    // 2024: any wearer counts as proficient, so arcane casters can wear it.
    'Elven Chain': ['defense', 'elf', 'wizard', 'sorcerer', 'rogue'],
    "Mariner's Armor": ['swimming', 'sailor'],
    'Animated Shield': _armorMagic,
    'Arrow-Catching Shield': ['defense', 'fighter', 'paladin'],
    'Sentinel Shield': ['defense', 'initiative', 'fighter', 'paladin', 'cleric'],
    'Spellguard Shield': ['defense', 'anti-magic', 'fighter', 'paladin', 'cleric'],
    'Shield of Missile Attraction': ['cursed', 'defense'],
    'Shield of the Cavalier': ['defense', 'mount', 'paladin', 'fighter'],
    // Healing
    'Potion of Healing': ['healing', 'potion'],
    'Potion of Greater Healing': ['healing', 'potion'],
    'Potion of Superior Healing': ['healing', 'potion'],
    'Potion of Supreme Healing': ['healing', 'potion'],
    'Potion of Vitality': ['healing', 'cure', 'potion'],
    'Elixir of Health': ['healing', 'cure', 'potion'],
    'Periapt of Wound Closure': ['healing', 'stabilize'],
    'Periapt of Health': ['cure', 'disease'],
    'Restorative Ointment': ['healing', 'cure'],
    'Ring of Regeneration': ['healing', 'regeneration'],
    'Staff of Healing': ['healing', 'staff'],
    'Rod of Resurrection': ['healing', 'revive'],
    'Necklace of Prayer Beads': ['healing', 'prayer'],
    // Stealth / roguery
    'Boots of Elvenkind': ['stealth', 'elf', 'rogue', 'ranger'],
    'Cloak of Elvenkind': ['stealth', 'elf', 'rogue', 'ranger'],
    'Cloak of Invisibility': ['stealth', 'invisibility', 'rogue'],
    'Ring of Invisibility': ['stealth', 'invisibility', 'rogue'],
    'Potion of Invisibility': ['stealth', 'invisibility', 'potion'],
    'Dust of Disappearance': ['stealth', 'invisibility'],
    'Amulet of Proof against Detection and Location':
        ['stealth', 'nondetection'],
    'Eversmoking Bottle': ['stealth', 'smoke'],
    'Hat of Disguise': ['disguise', 'rogue', 'charlatan'],
    'Gloves of Thievery': ['stealth', 'rogue', 'thief', 'criminal'],
    'Ring of Evasion': ['defense', 'rogue', 'monk'],
    'Chime of Opening': ['lockpicking', 'rogue'],
    'Goggles of Night': ['darkvision', 'rogue', 'ranger'],
    'Dagger of Venom': ['poison', 'rogue'],
    'Wand of Secrets': ['detection', 'traps', 'rogue'],
    // Movement
    'Boots of Speed': ['movement', 'speed'],
    'Boots of Striding and Springing': ['movement', 'jumping'],
    'Boots of Levitation': ['movement', 'levitation'],
    'Boots of the Winterlands': ['cold', 'arctic'],
    'Ring of Jumping': ['movement', 'jumping'],
    'Ring of Free Action': ['movement', 'freedom'],
    'Ring of Feather Falling': ['movement', 'falling'],
    'Ring of Water Walking': ['movement', 'water'],
    'Slippers of Spider Climbing': ['movement', 'climbing'],
    'Gloves of Swimming and Climbing': ['swimming', 'climbing'],
    'Cloak of Arachnida': ['climbing', 'spider'],
    'Winged Boots': ['flight', 'movement'],
    'Wings of Flying': ['flight', 'movement'],
    'Broom of Flying': ['flight', 'travel'],
    'Carpet of Flying': ['flight', 'travel'],
    'Potion of Flying': ['flight', 'potion'],
    'Cloak of the Bat': ['flight', 'stealth'],
    'Ring of Swimming': ['swimming', 'movement'],
    'Cloak of the Manta Ray': ['swimming', 'water breathing'],
    'Potion of Water Breathing': ['swimming', 'water breathing', 'potion'],
    'Horseshoes of Speed': ['mount', 'speed'],
    'Horseshoes of a Zephyr': ['mount', 'movement'],
    'Apparatus of the Crab': ['vehicle', 'underwater'],
    'Folding Boat': ['vehicle', 'boat'],
    'Helm of Teleportation': ['teleport', 'travel'],
    'Amulet of the Planes': ['planar', 'travel'],
    'Cubic Gate': ['planar', 'teleport'],
    'Well of Many Worlds': ['planar', 'travel'],
    // Strength / martial
    'Gauntlets of Ogre Power': _strength,
    'Belt of Giant Strength (Hill)': _strength,
    'Belt of Giant Strength (Stone)': _strength,
    'Belt of Giant Strength (Frost/Fire)': _strength,
    'Belt of Giant Strength (Cloud)': _strength,
    'Belt of Giant Strength (Storm)': _strength,
    'Potion of Giant Strength (Hill)': ['strength', 'potion', 'barbarian', 'fighter'],
    'Potion of Heroism': ['potion', 'barbarian', 'fighter'],
    'Manual of Gainful Exercise': ['strength', 'tome'],
    'Manual of Bodily Health': ['constitution', 'tome'],
    'Amulet of Health': ['constitution', 'health'],
    'Belt of Dwarvenkind': ['dwarf', 'constitution'],
    'Mantle of the Champion': _knight,
    'Weapon, +1': _martial,
    'Weapon, +2': _martial,
    'Weapon, +3': _martial,
    'Vicious Weapon': _martial,
    'Weapon of Warning': _martial,
    'Sword of Sharpness': _knight,
    'Vorpal Sword': _knight,
    'Dragon Slayer': _knight,
    'Flame Tongue': _knight,
    'Frost Brand': _knight,
    'Giant Slayer': _knight,
    'Sun Blade': ['undead', 'paladin', 'fighter'],
    'Luck Blade': _knight,
    'Defender': _knight,
    'Dancing Sword': _knight,
    'Nine Lives Stealer': _knight,
    'Sword of Life Stealing': _knight,
    'Sword of Wounding': _knight,
    'Rod of Lordly Might': _knight,
    'Holy Avenger': ['radiant', 'holy'],
    'Berserker Axe': ['cursed', 'barbarian'],
    'Hammer of Thunderbolts': ['strength', 'barbarian', 'fighter'],
    'Javelin of Lightning': ['thrown', 'fighter', 'barbarian'],
    'Dwarven Thrower': ['thrown', 'dwarf'],
    'Thunderous Greatclub': ['strength', 'thunder', 'barbarian'],
    'Mace of Disruption': ['undead', 'cleric', 'paladin'],
    'Mace of Smiting': ['cleric', 'paladin'],
    'Mace of Terror': ['cleric', 'paladin'],
    'Talisman of Pure Good': ['cleric', 'paladin'],
    'Talisman of Ultimate Evil': ['evil', 'holy symbol'],
    'Quarterstaff of the Acrobat': ['acrobatics', 'monk'],
    'Staff of Striking': ['monk', 'druid'],
    'Gloves of Missile Snaring': ['defense', 'monk'],
    'Scimitar of Speed': ['finesse', 'ranger', 'rogue'],
    'Trident of Fish Command': ['swimming', 'sailor'],
    'Oil of Sharpness': ['weapons', 'potion'],
    // Archery
    'Oathbow': _archer,
    'Bracers of Archery': _archer,
    'Quiver of Ehlonna': _archer,
    'Efficient Quiver': _archer,
    'Ammunition, +1': _archer,
    'Ammunition, +2': _archer,
    'Ammunition, +3': _archer,
    'Ammunition of Slaying': _archer,
    'Eyes of the Eagle': ['perception', 'vision', 'ranger'],
    // Spellcasting
    'Spell Scroll': ['spellcasting', 'scroll'],
    'Wand of Magic Missiles': ['wizard', 'sorcerer'],
    'Wand of Fireballs': _blaster,
    'Wand of Lightning Bolts': _blaster,
    'Wand of Web': _blaster,
    'Wand of the War Mage, +1': _blaster,
    'Wand of the War Mage, +2': _blaster,
    'Wand of the War Mage, +3': _blaster,
    'Wand of Binding': _blaster,
    'Wand of Paralysis': _blaster,
    'Wand of Polymorph': _blaster,
    'Wand of Wonder': _blaster,
    'Wand of Fear': ['control', 'frightened'],
    'Wand of Magic Detection': ['detection', 'wizard'],
    'Wand of Enemy Detection': ['detection', 'wand'],
    'Pearl of Power': _caster,
    'Ring of Spell Storing': _caster,
    'Ring of Three Wishes': ['wish', 'spellcasting'],
    'Hat of Many Spells': ['spellcasting', 'wizard'],
    'Talisman of the Sphere': ['spellcasting', 'control'],
    'Staff of Charming': ['spellcasting', 'bard', 'warlock', 'sorcerer'],
    'Staff of Thunder and Lightning': ['wizard', 'sorcerer', 'druid'],
    'Staff of Fire': ['fire', 'staff'],
    'Staff of Frost': ['cold', 'staff'],
    'Staff of Power': ['force', 'staff'],
    'Staff of the Magi': ['spellcasting', 'staff'],
    'Staff of Swarming Insects': ['summon', 'staff'],
    'Staff of the Python': ['summon', 'staff'],
    'Staff of the Woodlands': ['nature', 'staff'],
    'Staff of Withering': ['necrotic', 'staff'],
    'Rod of Absorption': _blaster,
    'Robe of Stars': ['wizard', 'sorcerer', 'warlock'],
    'Robe of Scintillating Colors': ['wizard', 'sorcerer'],
    'Robe of Eyes': ['vision', 'perception', 'wizard'],
    'Robe of the Magi': ['spellcasting', 'wizard'],
    'Robe of Useful Items': ['utility', 'wizard'],
    'Circlet of Blasting': ['wizard', 'sorcerer'],
    'Necklace of Fireballs': ['wizard', 'sorcerer'],
    'Crystal Ball': ['scrying', 'wizard'],
    'Crystal Ball of Mind Reading': ['scrying', 'telepathy'],
    'Crystal Ball of Telepathy': ['scrying', 'telepathy'],
    'Mirror of Mental Prowess': ['scrying', 'telepathy'],
    'Helm of Telepathy': ['telepathy', 'communication'],
    'Medallion of Thoughts': ['telepathy', 'detection'],
    'Gem of Seeing': ['vision', 'truesight'],
    'Eyes of Minute Seeing': ['investigation', 'vision'],
    'Rod of Alertness': ['initiative', 'detection'],
    'Helm of Brilliance': ['fire', 'radiant'],
    'Ring of Shooting Stars': ['lightning', 'illumination'],
    'Ring of Telekinesis': ['telekinesis', 'utility'],
    'Ring of the Ram': ['force', 'push'],
    'Headband of Intellect': ['intelligence', 'wizard'],
    'Tome of Clear Thought': ['intelligence', 'wizard'],
    'Tome of Understanding': ['wisdom', 'cleric', 'druid'],
    'Tome of Leadership and Influence':
        ['charisma', 'bard', 'sorcerer', 'warlock', 'paladin'],
    'Manual of Quickness of Action': ['dexterity', 'rogue', 'monk'],
    'Ioun Stone': ['buff', 'ability score'],
    // Bard / charm
    'Eyes of Charming': ['bard', 'warlock'],
    'Pipes of Haunting': ['instrument', 'bard'],
    'Pipes of the Sewers': ['instrument', 'bard'],
    'Horn of Blasting': ['instrument', 'bard'],
    'Horn of Valhalla': ['instrument', 'summon'],
    'Cape of the Mountebank': ['bard', 'rogue'],
    'Deck of Illusions': ['illusion', 'deception'],
    'Philter of Love': ['charm', 'potion'],
    'Rod of Rulership': ['charm', 'control'],
    // Beasts & elementals
    'Bag of Tricks (Gray)': _beasts,
    'Bag of Tricks (Rust)': _beasts,
    'Bag of Tricks (Tan)': _beasts,
    'Ring of Animal Influence': _beasts,
    'Potion of Animal Friendship': _beasts,
    'Figurine of Wondrous Power (Bronze Griffon)': _beasts,
    'Bowl of Commanding Water Elementals': _elementals,
    'Brazier of Commanding Fire Elementals': _elementals,
    'Censer of Controlling Air Elementals': _elementals,
    'Stone of Controlling Earth Elementals': _elementals,
    'Ring of Elemental Command': _elementals,
    'Elemental Gem': ['summon', 'elemental'],
    'Efreeti Bottle': ['summon', 'genie'],
    'Ring of Djinni Summoning': ['summon', 'genie'],
    'Iron Flask': ['capture', 'summon'],
    'Manual of Golems': ['construct', 'crafting'],
    // Potions
    'Potion of Climbing': ['climbing', 'potion'],
    'Potion of Fire Breath': ['fire', 'potion'],
    'Potion of Diminution': ['shrinking', 'potion'],
    'Potion of Growth': ['enlarge', 'potion'],
    'Potion of Gaseous Form': ['movement', 'potion'],
    'Potion of Mind Reading': ['telepathy', 'potion'],
    'Potion of Speed': ['speed', 'potion'],
    'Potion of Clairvoyance': ['scrying', 'potion'],
    'Potion of Longevity': ['age', 'potion'],
    'Potion of Resistance': ['resistance', 'potion'],
    'Oil of Slipperiness': ['escape', 'potion'],
    'Oil of Etherealness': ['planar', 'potion'],
    // Utility
    'Bag of Holding': ['container', 'utility'],
    'Handy Haversack': ['container', 'utility'],
    'Portable Hole': ['container', 'utility'],
    'Bag of Devouring': ['container', 'cursed'],
    'Bag of Beans': ['random', 'plants'],
    'Bead of Force': ['force', 'capture'],
    'Bead of Nourishment': ['food', 'camping'],
    'Decanter of Endless Water': ['utility', 'water'],
    'Dust of Dryness': ['utility', 'water'],
    'Immovable Rod': ['utility', 'rod'],
    'Rope of Climbing': ['climbing', 'utility'],
    'Rope of Entanglement': ['restraint', 'climbing'],
    'Iron Bands of Bilarro': ['restraint', 'capture'],
    'Dimensional Shackles': ['restraint', 'capture'],
    'Mirror of Life Trapping': ['traps', 'capture'],
    'Rod of Security': ['shelter', 'planar'],
    'Sending Stones': ['communication', 'message'],
    'Helm of Comprehending Languages': ['language', 'communication'],
    'Driftglobe': _lightSource,
    'Gem of Brightness': ['illumination', 'blinding'],
    'Lantern of Revealing': ['illumination', 'invisibility'],
    'Candle of Invocation': ['holy', 'planar'],
    'Feather Token': ['utility', 'feather fall'],
    'Wind Fan': ['wind', 'utility'],
    'Ring of Warmth': ['cold', 'resistance'],
    'Marvelous Pigments': ['crafting', 'art'],
    'Sovereign Glue': ['utility', 'adhesive'],
    'Universal Solvent': ['utility', 'adhesive'],
    'Dragon Orb': ['dragon', 'control'],
    'Deck of Many Things': ['random', 'fate'],
    'Sphere of Annihilation': ['destruction', 'force'],
    'Potion of Poison': ['poison', 'cursed'],
    'Dust of Sneezing and Choking': ['cursed', 'poison'],
    'Eye of Vecna': ['artifact', 'cursed'],
    'Hand of Vecna': ['artifact', 'cursed'],
  },
  'spell': {
    'Acid Splash': ['damage', 'aoe', 'acid', 'evocation'],
    'Chill Touch': ['damage', 'necrotic', 'necromancy'],
    'Dancing Lights': ['light source', 'utility', 'illusion'],
    'Fire Bolt': ['damage', 'fire', 'evocation'],
    'Light': ['light source', 'utility', 'evocation'],
    'Mage Hand': ['utility', 'conjuration'],
    'Mending': ['utility', 'repair', 'ritual', 'transmutation'],
    'Minor Illusion': ['utility', 'deception', 'illusion'],
    'Poison Spray': ['damage', 'poison', 'necromancy'],
    'Prestidigitation': ['utility', 'transmutation'],
    'Ray of Frost': ['damage', 'slow', 'cold', 'evocation'],
    'Sacred Flame': ['damage', 'radiant', 'evocation'],
    'Shocking Grasp': ['damage', 'lightning', 'evocation'],
    'Spare the Dying': ['healing', 'stabilize', 'necromancy'],
    'Thaumaturgy': ['utility', 'social', 'transmutation'],
    'Burning Hands': ['damage', 'aoe', 'fire', 'evocation'],
    'Charm Person': ['social', 'control', 'enchantment'],
    'Cure Wounds': ['healing', 'abjuration'],
    'Detect Magic': ['detection', 'ritual', 'divination'],
    'Healing Word': ['healing', 'bonus action', 'abjuration'],
    'Hellish Rebuke': ['damage', 'reaction', 'fire', 'evocation'],
    'Mage Armor': ['defense', 'armor', 'abjuration'],
    'Magic Missile': ['damage', 'force', 'evocation'],
    'Shield': ['defense', 'reaction', 'abjuration'],
    'Sleep': ['control', 'aoe', 'enchantment'],
    'Thunderwave': ['damage', 'aoe', 'thunder', 'evocation'],
    'Aid': ['buff', 'healing', 'abjuration'],
    'Hold Person': ['control', 'enchantment'],
    'Misty Step': ['teleport', 'bonus action', 'conjuration'],
    'Scorching Ray': ['damage', 'fire', 'evocation'],
    'Web': ['control', 'aoe', 'conjuration'],
    'Counterspell': ['anti-magic', 'reaction', 'abjuration'],
    'Dispel Magic': ['anti-magic', 'utility', 'abjuration'],
    'Fireball': ['damage', 'aoe', 'fire', 'evocation'],
    'Fly': ['flight', 'buff', 'transmutation'],
    'Lightning Bolt': ['damage', 'aoe', 'lightning', 'evocation'],
    'Revivify': ['revive', 'healing', 'necromancy'],
    'Greater Invisibility': ['stealth', 'invisibility', 'illusion'],
    'Polymorph': ['transformation', 'control', 'transmutation'],
    'Cone of Cold': ['damage', 'aoe', 'cold', 'evocation'],
    'Hold Monster': ['control', 'enchantment'],
    'Raise Dead': ['revive', 'necromancy'],
    'Disintegrate': ['damage', 'force', 'transmutation'],
    'Heal': ['healing', 'cure', 'abjuration'],
    'Finger of Death': ['damage', 'undead', 'necrotic', 'necromancy'],
    'Teleport': ['teleport', 'travel', 'conjuration'],
    'Power Word Stun': ['control', 'enchantment'],
    'Sunburst': ['damage', 'aoe', 'radiant', 'evocation'],
    'Meteor Swarm': ['damage', 'aoe', 'fire', 'bludgeoning', 'evocation'],
    'Power Word Kill': ['damage', 'death', 'enchantment'],
    'Time Stop': ['utility', 'time', 'transmutation'],
    'Wish': ['utility', 'wish', 'conjuration'],
    'Bless': ['buff', 'enchantment'],
    'Bane': ['debuff', 'enchantment'],
    'Command': ['control', 'enchantment'],
    'Faerie Fire': ['debuff', 'light source', 'evocation'],
    'Guiding Bolt': ['damage', 'radiant', 'evocation'],
    'Identify': ['detection', 'utility', 'ritual', 'divination'],
    'Protection from Evil and Good': ['defense', 'abjuration'],
    'Sanctuary': ['defense', 'bonus action', 'abjuration'],
    'Detect Evil and Good': ['detection', 'divination'],
    'Detect Poison and Disease': ['detection', 'ritual', 'divination'],
    'Disguise Self': ['deception', 'disguise', 'illusion'],
    'Speak with Animals': ['communication', 'beasts', 'ritual', 'divination'],
    'Spiritual Weapon': ['damage', 'bonus action', 'force', 'evocation'],
    'Silence': ['control', 'ritual', 'illusion'],
    'Mirror Image': ['defense', 'illusion'],
    'Invisibility': ['stealth', 'invisibility', 'illusion'],
    'See Invisibility': ['detection', 'invisibility', 'divination'],
    'Suggestion': ['social', 'control', 'enchantment'],
    'Levitate': ['control', 'movement', 'transmutation'],
    'Spike Growth': ['damage', 'control', 'piercing', 'transmutation'],
    'Pass Without Trace': ['stealth', 'buff', 'abjuration'],
    'Lesser Restoration': ['healing', 'cure', 'abjuration'],
    'Moonbeam': ['damage', 'radiant', 'evocation'],
    'Acid Arrow': ['damage', 'acid', 'evocation'],
    'Hypnotic Pattern': ['control', 'aoe', 'illusion'],
    'Slow': ['debuff', 'control', 'transmutation'],
    'Haste': ['buff', 'transmutation'],
    'Animate Dead': ['summon', 'undead', 'necromancy'],
    'Daylight': ['light source', 'evocation'],
    'Major Image': ['deception', 'illusion'],
    'Sleet Storm': ['control', 'aoe', 'conjuration'],
    'Banishment': ['control', 'abjuration'],
    'Wall of Fire': ['damage', 'wall', 'fire', 'evocation'],
    'Confusion': ['control', 'aoe', 'enchantment'],
    'Stoneskin': ['defense', 'transmutation'],
    'Wall of Force': ['wall', 'defense', 'evocation'],
    'Greater Restoration': ['healing', 'cure', 'abjuration'],
    'Mass Cure Wounds': ['healing', 'aoe', 'abjuration'],
    'Scrying': ['scrying', 'detection', 'divination'],
    'Telekinesis': ['control', 'utility', 'transmutation'],
    'Cloudkill': ['damage', 'aoe', 'poison', 'conjuration'],
    'Druidcraft': ['utility', 'nature', 'transmutation'],
    'Eldritch Blast': ['damage', 'force', 'evocation'],
    'Guidance': ['buff', 'skills', 'divination'],
    'Message': ['communication', 'transmutation'],
    'Produce Flame': ['damage', 'light source', 'fire', 'conjuration'],
    'Resistance': ['defense', 'buff', 'abjuration'],
    'Shillelagh': ['buff', 'melee', 'force', 'transmutation'],
    'True Strike': ['damage', 'melee', 'divination'],
    'Vicious Mockery': ['damage', 'debuff', 'psychic', 'enchantment'],
    'Animal Friendship': ['beasts', 'social', 'enchantment'],
    'Color Spray': ['control', 'aoe', 'illusion'],
    'Divine Favor': ['buff', 'damage', 'radiant', 'enchantment'],
    'Goodberry': ['healing', 'food', 'conjuration'],
    'Grease': ['control', 'conjuration'],
    "Hunter's Mark": ['damage', 'tracking', 'divination'],
    'Jump': ['movement', 'transmutation'],
    'Longstrider': ['movement', 'buff', 'transmutation'],
    'Purify Food and Drink': ['utility', 'food', 'ritual', 'transmutation'],
    'Silent Image': ['deception', 'illusion'],
    'Hideous Laughter': ['control', 'enchantment'],
    'Alter Self': ['transformation', 'disguise', 'transmutation'],
    'Animal Messenger': ['communication', 'beasts', 'ritual', 'enchantment'],
    'Arcane Lock': ['utility', 'security', 'abjuration'],
    'Augury': ['prophecy', 'ritual', 'divination'],
    'Blindness/Deafness': ['debuff', 'transmutation'],
    'Calm Emotions': ['social', 'control', 'enchantment'],
    'Continual Flame': ['light source', 'evocation'],
    'Darkness': ['control', 'darkness', 'evocation'],
    'Detect Thoughts': ['detection', 'telepathy', 'divination'],
    'Enhance Ability': ['buff', 'skills', 'transmutation'],
    'Find Traps': ['detection', 'traps', 'divination'],
    'Gust of Wind': ['control', 'evocation'],
    'Knock': ['utility', 'unlock', 'transmutation'],
    'Locate Object': ['detection', 'divination'],
    'Magic Weapon': ['buff', 'weapons', 'transmutation'],
    'Protection from Poison': ['defense', 'cure', 'abjuration'],
    'Ray of Enfeeblement': ['debuff', 'necrotic', 'necromancy'],
    'Rope Trick': ['shelter', 'utility', 'transmutation'],
    'Shatter': ['damage', 'aoe', 'thunder', 'evocation'],
    'Bestow Curse': ['debuff', 'curse', 'necrotic', 'necromancy'],
    'Clairvoyance': ['scrying', 'detection', 'divination'],
    'Create Food and Water': ['food', 'utility', 'conjuration'],
    'Fear': ['control', 'aoe', 'illusion'],
    'Gaseous Form': ['transformation', 'movement', 'transmutation'],
    'Glyph of Warding': ['traps', 'defense', 'abjuration'],
    'Magic Circle': ['defense', 'abjuration'],
    'Mass Healing Word': ['healing', 'bonus action', 'abjuration'],
    'Phantom Steed': ['travel', 'mount', 'ritual', 'illusion'],
    'Plant Growth': ['control', 'nature', 'transmutation'],
    'Protection from Energy': ['defense', 'abjuration'],
    'Remove Curse': ['cure', 'curse', 'abjuration'],
    'Sending': ['communication', 'divination'],
    'Speak with Dead': ['communication', 'undead', 'necromancy'],
    'Stinking Cloud': ['control', 'aoe', 'conjuration'],
    'Tongues': ['communication', 'language', 'divination'],
    'Water Breathing': ['underwater', 'buff', 'ritual', 'transmutation'],
    'Wind Wall': ['defense', 'wall', 'bludgeoning', 'evocation'],
    'Arcane Eye': ['scrying', 'divination'],
    'Black Tentacles': ['control', 'aoe', 'bludgeoning', 'conjuration'],
    'Death Ward': ['defense', 'abjuration'],
    'Dimension Door': ['teleport', 'conjuration'],
    'Divination': ['prophecy', 'ritual', 'divination'],
    'Faithful Hound': ['sentry', 'summon', 'conjuration'],
    'Fire Shield': ['defense', 'damage', 'fire', 'cold', 'evocation'],
    'Freedom of Movement': ['buff', 'movement', 'abjuration'],
    'Guardian of Faith': ['sentry', 'damage', 'radiant', 'conjuration'],
    'Ice Storm': ['damage', 'aoe', 'bludgeoning', 'cold', 'evocation'],
    'Locate Creature': ['detection', 'tracking', 'divination'],
    'Phantasmal Killer': ['damage', 'control', 'psychic', 'illusion'],
    'Resilient Sphere': ['control', 'defense', 'evocation'],
    'Animate Objects': ['summon', 'transmutation'],
    'Commune': ['prophecy', 'ritual', 'divination'],
    'Conjure Elemental': ['summon', 'elementals', 'conjuration'],
    'Contact Other Plane': ['prophecy', 'planar', 'ritual', 'divination'],
    'Dispel Evil and Good': ['defense', 'abjuration'],
    'Flame Strike': ['damage', 'aoe', 'fire', 'radiant', 'evocation'],
    'Geas': ['control', 'social', 'psychic', 'enchantment'],
    'Insect Plague': ['damage', 'aoe', 'piercing', 'conjuration'],
    'Legend Lore': ['lore', 'divination'],
    'Modify Memory': ['control', 'social', 'enchantment'],
    'Passwall': ['utility', 'movement', 'transmutation'],
    'Planar Binding': ['summon', 'control', 'abjuration'],
    'Seeming': ['deception', 'disguise', 'illusion'],
    'Tree Stride': ['teleport', 'nature', 'conjuration'],
    'Wall of Stone': ['wall', 'evocation'],
    'Chain Lightning': ['damage', 'lightning', 'evocation'],
    'Circle of Death': ['damage', 'aoe', 'necrotic', 'necromancy'],
    'Eyebite': ['control', 'necromancy'],
    'Globe of Invulnerability': ['defense', 'anti-magic', 'abjuration'],
    'Harm': ['damage', 'necrotic', 'necromancy'],
    "Heroes' Feast": ['buff', 'healing', 'conjuration'],
    'Magic Jar': ['control', 'possession', 'necromancy'],
    'Mass Suggestion': ['social', 'control', 'enchantment'],
    'Move Earth': ['terrain', 'utility', 'transmutation'],
    'Sunbeam': ['damage', 'radiant', 'evocation'],
    'True Seeing': ['detection', 'truesight', 'divination'],
    'Wall of Ice': ['wall', 'damage', 'cold', 'evocation'],
    'Conjure Celestial': ['summon', 'conjuration'],
    'Delayed Blast Fireball': ['damage', 'aoe', 'fire', 'evocation'],
    'Etherealness': ['movement', 'planar', 'conjuration'],
    'Forcecage': ['control', 'evocation'],
    'Plane Shift': ['travel', 'planar', 'conjuration'],
    'Prismatic Spray': ['damage', 'aoe', 'evocation'],
    'Regenerate': ['healing', 'transmutation'],
    'Resurrection': ['revive', 'necromancy'],
    'Reverse Gravity': ['control', 'transmutation'],
    'Symbol': ['traps', 'abjuration'],
    'Antimagic Field': ['anti-magic', 'abjuration'],
    'Animal Shapes': ['transformation', 'beasts', 'transmutation'],
    'Control Weather': ['weather', 'transmutation'],
    'Demiplane': ['planar', 'shelter', 'conjuration'],
    'Dominate Monster': ['control', 'enchantment'],
    'Earthquake': ['damage', 'terrain', 'bludgeoning', 'evocation'],
    'Holy Aura': ['defense', 'buff', 'abjuration'],
    'Incendiary Cloud': ['damage', 'aoe', 'fire', 'conjuration'],
    'Maze': ['control', 'conjuration'],
    'Mind Blank': ['defense', 'telepathy', 'abjuration'],
    'Telepathy': ['communication', 'telepathy', 'evocation'],
    'Astral Projection': ['planar', 'travel', 'necromancy'],
    'Foresight': ['buff', 'divination'],
    'Gate': ['planar', 'summon', 'conjuration'],
    'Imprisonment': ['control', 'abjuration'],
    'Mass Heal': ['healing', 'abjuration'],
    'Prismatic Wall': ['wall', 'defense', 'abjuration'],
    'Shapechange': ['transformation', 'transmutation'],
    'Storm of Vengeance': ['damage', 'weather', 'elemental', 'conjuration'],
    'True Polymorph': ['transformation', 'transmutation'],
    'True Resurrection': ['revive', 'necromancy'],
    'Weird': ['damage', 'control', 'psychic', 'illusion'],
    'Find Familiar': ['summon', 'familiar', 'ritual', 'conjuration'],
    'Find Steed': ['summon', 'mount', 'conjuration'],
    'Find the Path': ['travel', 'detection', 'divination'],
    'Antilife Shell': ['defense', 'abjuration'],
    'Antipathy/Sympathy': ['control', 'enchantment'],
    'Conjure Animals': ['summon', 'beasts', 'conjuration'],
    'Conjure Minor Elementals': ['damage', 'elementals', 'elemental', 'conjuration'],
    'Conjure Woodland Beings': ['damage', 'fey', 'conjuration'],
    'Conjure Fey': ['summon', 'fey', 'conjuration'],
    'Divine Word': ['control', 'evocation'],
    'Dominate Beast': ['control', 'beasts', 'enchantment'],
    'Dominate Person': ['control', 'enchantment'],
    'Fire Storm': ['damage', 'aoe', 'fire', 'evocation'],
    'Flaming Sphere': ['damage', 'fire', 'evocation'],
    'Flesh to Stone': ['control', 'petrify', 'transmutation'],
    'Forbiddance': ['defense', 'radiant', 'ritual', 'abjuration'],
    'Guards and Wards': ['defense', 'abjuration'],
    'Hallow': ['defense', 'abjuration'],
    'Heat Metal': ['damage', 'fire', 'transmutation'],
    'Hex': ['damage', 'curse', 'necrotic', 'enchantment'],
    'Magic Mouth': ['utility', 'communication', 'ritual', 'illusion'],
    'Mind Spike': ['damage', 'tracking', 'psychic', 'divination'],
    'Arcane Sword': ['damage', 'force', 'evocation'],
    'Pass without Trace': ['stealth', 'buff', 'abjuration'],
    'Planar Ally': ['summon', 'planar', 'conjuration'],
    'Power Word Heal': ['healing', 'evocation'],
    'Prayer of Healing': ['healing', 'abjuration'],
    'Programmed Illusion': ['deception', 'illusion'],
    'Project Image': ['deception', 'scrying', 'illusion'],
    'Reincarnate': ['revive', 'necromancy'],
    'Spirit Guardians': ['damage', 'aoe', 'radiant', 'necrotic', 'conjuration'],
    'Wall of Thorns': ['damage', 'wall', 'slashing', 'piercing', 'conjuration'],
    'Water Walk': ['movement', 'ritual', 'transmutation'],
    'Word of Recall': ['teleport', 'conjuration'],
    'Zone of Truth': ['social', 'enchantment'],
    'Alarm': ['sentry', 'ritual', 'abjuration'],
    'Barkskin': ['defense', 'transmutation'],
    'Beacon of Hope': ['buff', 'healing', 'abjuration'],
    'Befuddlement': ['damage', 'debuff', 'psychic', 'enchantment'],
    'Blight': ['damage', 'necrotic', 'necromancy'],
    'Blink': ['defense', 'transmutation'],
    'Blur': ['defense', 'illusion'],
    'Charm Monster': ['social', 'control', 'enchantment'],
    'Chromatic Orb': ['damage', 'elemental', 'evocation'],
    'Clone': ['revive', 'necromancy'],
    'Commune with Nature': ['lore', 'nature', 'ritual', 'divination'],
    'Comprehend Languages': ['communication', 'language', 'ritual', 'divination'],
    'Compulsion': ['control', 'enchantment'],
    'Contagion': ['debuff', 'disease', 'necromancy'],
    'Control Water': ['terrain', 'control', 'transmutation'],
    'Create or Destroy Water': ['utility', 'transmutation'],
    'Creation': ['utility', 'illusion'],
    'Darkvision': ['buff', 'darkvision', 'transmutation'],
    'Dream': ['communication', 'illusion'],
    'Elementalism': ['utility', 'transmutation'],
    'Enlarge/Reduce': ['buff', 'debuff', 'transmutation'],
    'Ensnaring Strike': ['control', 'damage', 'piercing', 'conjuration'],
    'Entangle': ['control', 'aoe', 'conjuration'],
    'Enthrall': ['social', 'control', 'enchantment'],
    'Expeditious Retreat': ['movement', 'bonus action', 'transmutation'],
    'Fabricate': ['crafting', 'utility', 'transmutation'],
    'False Life': ['defense', 'necromancy'],
    'Feather Fall': ['reaction', 'movement', 'transmutation'],
    'Flame Blade': ['damage', 'melee', 'fire', 'evocation'],
    'Fog Cloud': ['control', 'stealth', 'conjuration'],
    'Freezing Sphere': ['damage', 'aoe', 'cold', 'evocation'],
    'Gentle Repose': ['undead', 'utility', 'ritual', 'necromancy'],
    'Giant Insect': ['summon', 'transmutation'],
    'Glibness': ['social', 'transmutation'],
    'Hallucinatory Terrain': ['deception', 'terrain', 'illusion'],
    'Heroism': ['buff', 'enchantment'],
    'Ice Knife': ['damage', 'piercing', 'cold', 'conjuration'],
    'Illusory Script': ['communication', 'deception', 'ritual', 'illusion'],
    'Locate Animals or Plants': ['detection', 'nature', 'ritual', 'divination'],
    'Meld into Stone': ['stealth', 'ritual', 'transmutation'],
    'Mirage Arcane': ['deception', 'terrain', 'illusion'],
    'Mislead': ['stealth', 'deception', 'illusion'],
    'Nondetection': ['stealth', 'defense', 'abjuration'],
    'Private Sanctum': ['defense', 'shelter', 'abjuration'],
    'Ray of Sickness': ['damage', 'poison', 'necromancy'],
    'Secret Chest': ['storage', 'utility', 'conjuration'],
    'Shield of Faith': ['defense', 'bonus action', 'abjuration'],
    'Simulacrum': ['summon', 'illusion'],
    'Speak with Plants': ['communication', 'nature', 'transmutation'],
    'Spider Climb': ['movement', 'climbing', 'transmutation'],
    'Starry Wisp': ['damage', 'light source', 'radiant', 'evocation'],
    'Stone Shape': ['terrain', 'utility', 'transmutation'],
    'Telepathic Bond': ['communication', 'telepathy', 'ritual', 'divination'],
    'Teleportation Circle': ['teleport', 'travel', 'conjuration'],
    'Tiny Hut': ['shelter', 'defense', 'ritual', 'evocation'],
    'Tsunami': ['damage', 'aoe', 'bludgeoning', 'conjuration'],
    'Unseen Servant': ['summon', 'utility', 'ritual', 'conjuration'],
    'Vitriolic Sphere': ['damage', 'aoe', 'acid', 'evocation'],
    'Warding Bond': ['defense', 'abjuration'],
    'Arcane Hand': ['damage', 'control', 'evocation'],
    'Aura of Life': ['healing', 'defense', 'abjuration'],
    'Awaken': ['nature', 'utility', 'transmutation'],
    'Divine Smite': ['damage', 'smite', 'radiant', 'evocation'],
    'Searing Smite': ['damage', 'smite', 'fire', 'evocation'],
    'Shining Smite': ['damage', 'smite', 'radiant', 'evocation'],
    'Summon Dragon': ['summon', 'dragon', 'conjuration'],
    'Sorcerous Burst': ['damage', 'elemental', 'evocation'],
    'Floating Disk': ['utility', 'storage', 'ritual', 'conjuration'],
    'Inflict Wounds': ['damage', 'necrotic', 'necromancy'],
    "Arcanist's Magic Aura": ['deception', 'illusion'],
    'Call Lightning': ['damage', 'aoe', 'lightning', 'conjuration'],
    'Vampiric Touch': ['damage', 'healing', 'necrotic', 'necromancy'],
    'Blade Barrier': ['damage', 'wall', 'force', 'evocation'],
    'Create Undead': ['summon', 'undead', 'necromancy'],
    'Irresistible Dance': ['control', 'enchantment'],
    'Wind Walk': ['travel', 'transformation', 'transmutation'],
    'Magnificent Mansion': ['shelter', 'conjuration'],
    'Contingency': ['utility', 'abjuration'],
    'Dissonant Whispers': ['damage', 'control', 'psychic', 'enchantment'],
    "Dragon's Breath": ['damage', 'buff', 'transmutation'],
    'Instant Summons': ['utility', 'ritual', 'conjuration'],
    'Phantasmal Force': ['damage', 'deception', 'illusion'],
    'Sequester': ['stealth', 'transmutation'],
    'Transport via Plants': ['teleport', 'nature', 'conjuration'],
  },
  'feat': {
    'Alert': ['origin', 'initiative', 'criminal', 'guard'],
    'Magic Initiate': ['origin', 'spellcasting', 'acolyte', 'guide', 'sage'],
    'Savage Attacker': ['origin', 'melee', 'soldier'],
    'Skilled': ['origin', 'skills', 'charlatan', 'noble', 'scribe'],
    'Ability Score Improvement': ['general', 'ability score'],
    'Grappler': ['general', 'grapple', 'melee'],
    'Archery': ['fighting style', 'ranged', 'fighter', 'ranger'],
    'Defense': ['fighting style', 'armor', 'fighter', 'paladin', 'ranger'],
    'Great Weapon Fighting': ['fighting style', 'two-handed', 'fighter', 'paladin'],
    'Two-Weapon Fighting': ['fighting style', 'dual wield', 'fighter', 'ranger'],
    'Boon of Combat Prowess': ['epic boon', 'attack', 'martial'],
    'Boon of Dimensional Travel': ['epic boon', 'teleport'],
    'Boon of Fate': ['epic boon', 'luck'],
    'Boon of Irresistible Offense': ['epic boon', 'damage', 'martial'],
    'Boon of Spell Recall': ['epic boon', 'spellcasting'],
    'Boon of the Night Spirit': ['epic boon', 'stealth', 'darkness'],
    'Boon of Truesight': ['epic boon', 'truesight'],
    'Crafter': ['origin', 'crafting', 'artisan'],
    'Healer': ['origin', 'healing', 'hermit'],
    'Lucky': ['origin', 'luck', 'merchant', 'wayfarer'],
    'Musician': ['origin', 'instrument', 'entertainer', 'bard'],
    'Tavern Brawler': ['origin', 'unarmed', 'sailor'],
    'Tough': ['origin', 'hit points', 'farmer'],
    'Athlete': ['general', 'movement', 'climbing'],
    'Charger': ['general', 'melee', 'movement'],
    'Crossbow Expert': ['general', 'crossbow', 'ranged', 'fighter', 'ranger'],
    'Defensive Duelist': ['general', 'finesse', 'reaction', 'rogue'],
    'Dual Wielder': ['general', 'dual wield', 'melee', 'ranger'],
    'Durable': ['general', 'hit points', 'healing'],
    'Elemental Adept': ['general', 'spellcasting', 'damage', 'sorcerer'],
    'Fey-Touched': ['general', 'spellcasting', 'teleport'],
    'Great Weapon Master': ['general', 'two-handed', 'barbarian', 'fighter'],
    'Heavy Armor Master': ['general', 'heavy', 'fighter', 'paladin'],
    'Inspiring Leader': ['general', 'support', 'bard', 'paladin'],
    'Keen Mind': ['general', 'knowledge', 'investigation'],
    'Lightly Armored': ['general', 'armor', 'light'],
    'Mage Slayer': ['general', 'anti-magic', 'melee'],
    'Martial Adept': ['general', 'maneuvers', 'fighter'],
    'Medium Armor Master': ['general', 'armor', 'medium'],
    'Mobile': ['general', 'movement', 'speed', 'monk'],
    'Moderately Armored': ['general', 'armor', 'medium'],
    'Mounted Combatant': ['general', 'mount', 'paladin'],
    'Observant': ['general', 'perception', 'investigation'],
    'Polearm Master': ['general', 'reach', 'polearm', 'fighter'],
    'Resilient': ['general', 'saving throw', 'defense'],
    'Ritual Caster': ['general', 'ritual', 'spellcasting'],
    'Sentinel': ['general', 'reaction', 'fighter', 'paladin'],
    'Shadow-Touched': ['general', 'spellcasting', 'invisibility'],
    'Sharpshooter': ['general', 'ranged', 'fighter', 'ranger'],
    'Shield Master': ['general', 'shield', 'defense', 'fighter'],
    'Skill Expert': ['general', 'skills', 'expertise', 'rogue'],
    'Spell Sniper': ['general', 'spellcasting', 'ranged'],
    'Telekinetic': ['general', 'telekinesis', 'bonus action'],
    'Telepathic': ['general', 'telepathy', 'communication'],
    'War Caster': ['general', 'concentration', 'spellcasting', 'cleric'],
    'Weapon Master': ['general', 'weapons', 'martial'],
    'Blind Fighting': ['fighting style', 'blindsight', 'fighter', 'paladin'],
    'Dueling': ['fighting style', 'one-handed', 'fighter', 'paladin', 'ranger'],
    'Interception': ['fighting style', 'reaction', 'fighter', 'paladin'],
    'Protection': ['fighting style', 'reaction', 'fighter', 'paladin'],
    'Thrown Weapon Fighting': ['fighting style', 'thrown', 'fighter', 'ranger'],
    'Unarmed Fighting': ['fighting style', 'unarmed', 'fighter'],
  },
  'monster': {
    'Aboleth': ['aberration', 'underdark', 'aquatic', 'legendary'],
    'Goblin Warrior': ['humanoid', 'goblinoid', 'forest', 'underdark'],
    'Skeleton': ['undead', 'crypt'],
    'Zombie': ['undead', 'crypt'],
    'Adult Red Dragon': ['dragon', 'chromatic', 'mountain', 'legendary'],
    'Lich': ['undead', 'spellcaster', 'crypt', 'legendary'],
    'Beholder': ['aberration', 'underdark', 'legendary'],
    'Mind Flayer': ['aberration', 'underdark', 'psionic'],
    'Ogre': ['giant', 'hill', 'brute'],
    'Owlbear': ['monstrosity', 'forest'],
    'Hobgoblin Warrior': ['humanoid', 'goblinoid', 'army'],
    'Bandit': ['humanoid', 'outlaw'],
    'Giant Spider': ['beast', 'forest', 'underdark', 'wild shape'],
    'Kobold Warrior': ['humanoid', 'kobold', 'mountain', 'traps'],
    'Orc': ['humanoid', 'raider', 'mountain'],
    'Gnoll': ['fiend', 'gnoll', 'grassland', 'raider'],
    'Bugbear Warrior': ['humanoid', 'goblinoid', 'forest', 'ambusher'],
    'Drow': ['humanoid', 'underdark'],
    'Werewolf': ['humanoid', 'shapechanger', 'lycanthrope', 'forest'],
    'Troll': ['giant', 'regeneration', 'brute'],
    'Hydra': ['monstrosity', 'swamp'],
    'Vampire': ['undead', 'crypt', 'urban', 'legendary'],
    'Balor': ['fiend', 'demon', 'abyss'],
    'Pit Fiend': ['fiend', 'devil', 'hell'],
    'Air Elemental': ['elemental', 'planar', 'air'],
    'Earth Elemental': ['elemental', 'planar', 'earth'],
    'Fire Elemental': ['elemental', 'planar', 'fire'],
    'Water Elemental': ['elemental', 'planar', 'water'],
    'Ghoul': ['undead', 'crypt'],
    'Wight': ['undead', 'crypt'],
    'Specter': ['undead', 'crypt', 'incorporeal'],
    'Animated Armor': ['construct', 'animated', 'sentry'],
    'Stone Giant': ['giant', 'mountain', 'underdark'],
    'Hill Giant': ['giant', 'hill', 'brute'],
    'Manticore': ['monstrosity', 'mountain'],
    'Minotaur': ['monstrosity', 'labyrinth'],
    'Basilisk': ['monstrosity', 'mountain', 'petrify'],
    'Cockatrice': ['monstrosity', 'grassland', 'petrify'],
    'Ettin': ['giant', 'hill', 'brute'],
    'Harpy': ['monstrosity', 'coastal', 'mountain'],
    "Will-o'-Wisp": ['undead', 'swamp', 'forest'],
    'Mummy': ['undead', 'desert', 'crypt'],
    'Treant': ['plant', 'forest'],
    'Adult Black Dragon': ['dragon', 'chromatic', 'swamp', 'legendary'],
    'Adult Blue Dragon': ['dragon', 'chromatic', 'desert', 'legendary'],
    'Adult Green Dragon': ['dragon', 'chromatic', 'forest', 'legendary'],
    'Adult White Dragon': ['dragon', 'chromatic', 'arctic', 'legendary'],
    'Chuul': ['aberration', 'underdark', 'aquatic'],
    'Otyugh': ['aberration', 'underdark', 'urban'],
    'Roper': ['aberration', 'underdark'],
    'Nothic': ['aberration', 'underdark'],
    'Dryad': ['fey', 'forest'],
    'Gargoyle': ['elemental', 'urban', 'sentry'],
    'Couatl': ['celestial', 'forest'],
    'Sphinx': ['celestial', 'desert', 'sentry'],
    'Death Dog': ['monstrosity', 'desert'],
    'Knight': ['humanoid', 'warrior', 'leader'],
    'Veteran': ['humanoid', 'warrior'],
    'Gladiator': ['humanoid', 'warrior', 'arena'],
    'Mage': ['humanoid', 'spellcaster', 'urban'],
    'Priest': ['humanoid', 'spellcaster', 'healer'],
    'Cult Fanatic': ['humanoid', 'cultist', 'spellcaster'],
    'Spy': ['humanoid', 'urban', 'stealth'],
    'Assassin': ['humanoid', 'urban', 'stealth'],
    'Black Dragon Wyrmling': ['dragon', 'chromatic', 'swamp'],
    'Blue Dragon Wyrmling': ['dragon', 'chromatic', 'desert'],
    'Brass Dragon Wyrmling': ['dragon', 'metallic', 'desert'],
    'Bronze Dragon Wyrmling': ['dragon', 'metallic', 'coastal'],
    'Copper Dragon Wyrmling': ['dragon', 'metallic', 'hill'],
    'Gold Dragon Wyrmling': ['dragon', 'metallic', 'grassland'],
    'Green Dragon Wyrmling': ['dragon', 'chromatic', 'forest'],
    'Red Dragon Wyrmling': ['dragon', 'chromatic', 'mountain'],
    'Silver Dragon Wyrmling': ['dragon', 'metallic', 'mountain'],
    'White Dragon Wyrmling': ['dragon', 'chromatic', 'arctic'],
    'Young Black Dragon': ['dragon', 'chromatic', 'swamp'],
    'Young Blue Dragon': ['dragon', 'chromatic', 'desert'],
    'Young Brass Dragon': ['dragon', 'metallic', 'desert'],
    'Young Bronze Dragon': ['dragon', 'metallic', 'coastal'],
    'Young Copper Dragon': ['dragon', 'metallic', 'hill'],
    'Young Gold Dragon': ['dragon', 'metallic', 'grassland'],
    'Young Green Dragon': ['dragon', 'chromatic', 'forest'],
    'Young Red Dragon': ['dragon', 'chromatic', 'mountain'],
    'Young Silver Dragon': ['dragon', 'metallic', 'mountain'],
    'Young White Dragon': ['dragon', 'chromatic', 'arctic'],
    'Adult Brass Dragon': ['dragon', 'metallic', 'desert', 'legendary'],
    'Adult Bronze Dragon': ['dragon', 'metallic', 'coastal', 'legendary'],
    'Adult Copper Dragon': ['dragon', 'metallic', 'hill', 'legendary'],
    'Adult Gold Dragon': ['dragon', 'metallic', 'grassland', 'legendary'],
    'Adult Silver Dragon': ['dragon', 'metallic', 'mountain', 'legendary'],
    'Ancient Black Dragon': ['dragon', 'chromatic', 'swamp', 'legendary'],
    'Ancient Blue Dragon': ['dragon', 'chromatic', 'desert', 'legendary'],
    'Ancient Brass Dragon': ['dragon', 'metallic', 'desert', 'legendary'],
    'Ancient Bronze Dragon': ['dragon', 'metallic', 'coastal', 'legendary'],
    'Ancient Copper Dragon': ['dragon', 'metallic', 'hill', 'legendary'],
    'Ancient Gold Dragon': ['dragon', 'metallic', 'grassland', 'legendary'],
    'Ancient Green Dragon': ['dragon', 'chromatic', 'forest', 'legendary'],
    'Ancient Red Dragon': ['dragon', 'chromatic', 'mountain', 'legendary'],
    'Ancient Silver Dragon': ['dragon', 'metallic', 'mountain', 'legendary'],
    'Ancient White Dragon': ['dragon', 'chromatic', 'arctic', 'legendary'],
    'Archmage': ['humanoid', 'spellcaster', 'urban'],
    'Bandit Captain': ['humanoid', 'outlaw', 'leader'],
    'Berserker': ['humanoid', 'warrior', 'raider'],
    'Commoner': ['humanoid', 'urban', 'villager'],
    'Cultist': ['humanoid', 'cultist', 'urban'],
    'Cultist Fanatic': ['humanoid', 'cultist', 'spellcaster'],
    'Druid': ['humanoid', 'spellcaster', 'forest'],
    'Guard': ['humanoid', 'urban', 'warrior'],
    'Guard Captain': ['humanoid', 'urban', 'leader'],
    'Hobgoblin Captain': ['humanoid', 'goblinoid', 'army', 'leader'],
    'Noble': ['humanoid', 'urban', 'aristocrat'],
    'Pirate': ['humanoid', 'coastal', 'outlaw'],
    'Pirate Captain': ['humanoid', 'coastal', 'leader'],
    'Priest Acolyte': ['humanoid', 'spellcaster', 'healer'],
    'Sahuagin Warrior': ['humanoid', 'sahuagin', 'aquatic', 'coastal'],
    'Scout': ['humanoid', 'forest', 'archer'],
    'Warrior Infantry': ['humanoid', 'army', 'warrior'],
    'Warrior Veteran': ['humanoid', 'army', 'warrior'],
    'Tough': ['humanoid', 'urban', 'thug'],
    'Tough Boss': ['humanoid', 'urban', 'leader'],
    'Bugbear Stalker': ['humanoid', 'goblinoid', 'forest', 'ambusher'],
    'Centaur Trooper': ['fey', 'grassland', 'archer'],
    'Goblin Boss': ['humanoid', 'goblinoid', 'forest', 'leader'],
    'Goblin Minion': ['humanoid', 'goblinoid', 'forest', 'minion'],
    'Gnoll Warrior': ['fiend', 'gnoll', 'grassland', 'raider'],
    'Merfolk Skirmisher': ['humanoid', 'merfolk', 'aquatic', 'coastal'],
    'Merrow': ['monstrosity', 'aquatic', 'coastal'],
    'Lemure': ['fiend', 'devil', 'hell'],
    'Imp': ['fiend', 'devil', 'hell', 'familiar'],
    'Bearded Devil': ['fiend', 'devil', 'hell'],
    'Barbed Devil': ['fiend', 'devil', 'hell'],
    'Chain Devil': ['fiend', 'devil', 'hell'],
    'Bone Devil': ['fiend', 'devil', 'hell'],
    'Horned Devil': ['fiend', 'devil', 'hell'],
    'Ice Devil': ['fiend', 'devil', 'hell'],
    'Erinyes': ['fiend', 'devil', 'hell'],
    'Quasit': ['fiend', 'demon', 'abyss', 'familiar'],
    'Dretch': ['fiend', 'demon', 'abyss'],
    'Vrock': ['fiend', 'demon', 'abyss'],
    'Hezrou': ['fiend', 'demon', 'abyss'],
    'Glabrezu': ['fiend', 'demon', 'abyss'],
    'Nalfeshnee': ['fiend', 'demon', 'abyss'],
    'Marilith': ['fiend', 'demon', 'abyss'],
    'Incubus': ['fiend', 'planar', 'tempter'],
    'Succubus': ['fiend', 'planar', 'tempter'],
    'Night Hag': ['fiend', 'hag', 'planar'],
    'Sea Hag': ['fey', 'hag', 'coastal'],
    'Green Hag': ['fey', 'hag', 'forest'],
    'Dust Mephit': ['elemental', 'mephit', 'planar'],
    'Ice Mephit': ['elemental', 'mephit', 'planar'],
    'Magma Mephit': ['elemental', 'mephit', 'planar'],
    'Steam Mephit': ['elemental', 'mephit', 'planar'],
    'Magmin': ['elemental', 'planar', 'fire'],
    'Azer Sentinel': ['elemental', 'planar', 'fire'],
    'Djinni': ['elemental', 'genie', 'planar'],
    'Efreeti': ['elemental', 'genie', 'planar'],
    'Salamander': ['elemental', 'planar', 'fire'],
    'Invisible Stalker': ['elemental', 'planar', 'invisibility'],
    'Cloud Giant': ['giant', 'mountain'],
    'Fire Giant': ['giant', 'mountain', 'fire'],
    'Frost Giant': ['giant', 'arctic'],
    'Storm Giant': ['giant', 'coastal', 'aquatic'],
    'Shadow': ['undead', 'crypt', 'underdark'],
    'Wraith': ['undead', 'crypt'],
    'Ghost': ['undead', 'crypt', 'incorporeal'],
    'Ghast': ['undead', 'crypt'],
    'Mummy Lord': ['undead', 'desert', 'crypt', 'legendary'],
    'Vampire Spawn': ['undead', 'crypt', 'urban'],
    'Vampire Familiar': ['undead', 'urban'],
    'Ogre Zombie': ['undead', 'crypt'],
    'Minotaur Skeleton': ['undead', 'crypt'],
    'Warhorse Skeleton': ['undead', 'crypt', 'mount'],
    'Swarm of Crawling Claws': ['undead', 'crypt', 'swarm'],
    'Werebear': ['humanoid', 'shapechanger', 'lycanthrope', 'forest'],
    'Wereboar': ['humanoid', 'shapechanger', 'lycanthrope', 'grassland'],
    'Wererat': ['humanoid', 'shapechanger', 'lycanthrope', 'urban'],
    'Weretiger': ['humanoid', 'shapechanger', 'lycanthrope', 'forest'],
    'Animated Flying Sword': ['construct', 'animated', 'sentry'],
    'Animated Rug of Smothering': ['construct', 'animated', 'sentry'],
    'Clay Golem': ['construct', 'golem', 'sentry'],
    'Flesh Golem': ['construct', 'golem', 'sentry'],
    'Stone Golem': ['construct', 'golem', 'sentry'],
    'Iron Golem': ['construct', 'golem', 'sentry'],
    'Shield Guardian': ['construct', 'sentry', 'bodyguard'],
    'Homunculus': ['construct', 'familiar'],
    'Ankheg': ['monstrosity', 'grassland', 'burrower'],
    'Awakened Shrub': ['plant', 'forest'],
    'Awakened Tree': ['plant', 'forest'],
    'Axe Beak': ['monstrosity', 'grassland'],
    'Behir': ['monstrosity', 'underdark', 'mountain'],
    'Black Pudding': ['ooze', 'underdark'],
    'Blink Dog': ['fey', 'forest', 'teleport'],
    'Bulette': ['monstrosity', 'grassland', 'burrower'],
    'Chimera': ['monstrosity', 'mountain'],
    'Cloaker': ['aberration', 'underdark'],
    'Darkmantle': ['aberration', 'underdark'],
    'Doppelganger': ['monstrosity', 'urban', 'disguise'],
    'Dragon Turtle': ['dragon', 'aquatic', 'coastal'],
    'Drider': ['monstrosity', 'underdark'],
    'Ettercap': ['monstrosity', 'forest'],
    'Gelatinous Cube': ['ooze', 'underdark'],
    'Gibbering Mouther': ['aberration', 'underdark'],
    'Gorgon': ['monstrosity', 'grassland', 'petrify'],
    'Gray Ooze': ['ooze', 'underdark'],
    'Grick': ['monstrosity', 'underdark'],
    'Griffon': ['monstrosity', 'mountain', 'mount'],
    'Grimlock': ['humanoid', 'underdark'],
    'Guardian Naga': ['celestial', 'naga', 'sentry'],
    'Half-Dragon': ['dragon', 'breath weapon'],
    'Hell Hound': ['fiend', 'hell', 'fire'],
    'Hippogriff': ['monstrosity', 'mountain', 'mount'],
    'Kraken': ['monstrosity', 'aquatic'],
    'Lamia': ['monstrosity', 'desert'],
    'Medusa': ['monstrosity', 'petrify'],
    'Mimic': ['monstrosity', 'underdark', 'ambusher'],
    'Minotaur of Baphomet': ['monstrosity', 'labyrinth', 'abyss'],
    'Nightmare': ['fiend', 'planar', 'mount'],
    'Ochre Jelly': ['ooze', 'underdark'],
    'Oni': ['fiend', 'disguise', 'spellcaster'],
    'Pegasus': ['celestial', 'mount'],
    'Phase Spider': ['monstrosity', 'planar', 'ethereal'],
    'Pseudodragon': ['dragon', 'familiar', 'forest'],
    'Purple Worm': ['monstrosity', 'underdark', 'burrower'],
    'Rakshasa': ['fiend', 'urban', 'disguise'],
    'Remorhaz': ['monstrosity', 'arctic', 'burrower'],
    'Roc': ['monstrosity', 'mountain', 'coastal'],
    'Rust Monster': ['monstrosity', 'underdark'],
    'Satyr': ['fey', 'forest'],
    'Seahorse': ['beast', 'aquatic', 'wild shape'],
    'Shambling Mound': ['plant', 'swamp'],
    'Shrieker Fungus': ['plant', 'underdark'],
    'Solar': ['celestial', 'angel', 'planar'],
    'Planetar': ['celestial', 'angel', 'planar'],
    'Deva': ['celestial', 'angel', 'planar'],
    'Sphinx of Lore': ['celestial', 'sphinx', 'sentry'],
    'Sphinx of Valor': ['celestial', 'sphinx', 'sentry'],
    'Sphinx of Wonder': ['celestial', 'sphinx', 'familiar'],
    'Spirit Naga': ['fiend', 'naga', 'underdark'],
    'Sprite': ['fey', 'forest', 'familiar'],
    'Tarrasque': ['monstrosity', 'colossal'],
    'Troll Limb': ['giant', 'regeneration'],
    'Unicorn': ['celestial', 'forest'],
    'Violet Fungus': ['plant', 'underdark'],
    'Winter Wolf': ['monstrosity', 'arctic'],
    'Worg': ['fey', 'forest', 'mount'],
    'Wyvern': ['dragon', 'mountain'],
    'Xorn': ['elemental', 'underdark', 'burrower'],
    'Banshee': ['undead', 'crypt', 'incorporeal'],
    'Pixie': ['fey', 'forest'],
  },
  'animal': {
    'Wolf': ['beast', 'forest', 'grassland', 'wild shape'],
    'Giant Eagle': ['beast', 'mountain', 'wild shape'],
    'Dire Wolf': ['beast', 'forest', 'wild shape'],
    'Tiger': ['beast', 'forest', 'wild shape'],
    'Lion': ['beast', 'grassland', 'wild shape'],
    'Crocodile': ['beast', 'swamp', 'wild shape'],
    'Boar': ['beast', 'forest', 'wild shape'],
    'Mastiff': ['beast', 'companion', 'urban', 'wild shape'],
    'Riding Horse': ['beast', 'mount', 'grassland', 'wild shape'],
    'Cat': ['beast', 'familiar', 'urban', 'wild shape'],
    'Rat': ['beast', 'familiar', 'urban', 'wild shape'],
    'Giant Rat': ['beast', 'urban', 'wild shape'],
    'Hawk': ['beast', 'familiar', 'wild shape'],
    'Eagle': ['beast', 'mountain', 'wild shape'],
    'Owl': ['beast', 'familiar', 'forest', 'wild shape'],
    'Pony': ['beast', 'mount', 'wild shape'],
    'Camel': ['beast', 'mount', 'desert', 'wild shape'],
    'Elephant': ['beast', 'mount', 'grassland'],
    'Ape': ['beast', 'forest', 'wild shape'],
    'Constrictor Snake': ['beast', 'forest', 'swamp', 'wild shape'],
    'Giant Constrictor Snake': ['beast', 'forest', 'swamp'],
    'Frog': ['beast', 'familiar', 'swamp', 'wild shape'],
    'Giant Frog': ['beast', 'swamp', 'wild shape'],
    'Giant Centipede': ['beast', 'underdark', 'wild shape'],
    'Giant Lizard': ['beast', 'mount', 'underdark', 'wild shape'],
    'Polar Bear': ['beast', 'arctic'],
    'Warhorse': ['beast', 'mount', 'wild shape'],
    'Octopus': ['beast', 'familiar', 'aquatic', 'wild shape'],
    'Brown Bear': ['beast', 'forest', 'wild shape'],
    'Tyrannosaurus Rex': ['beast', 'dinosaur'],
    'Triceratops': ['beast', 'dinosaur'],
    'Allosaurus': ['beast', 'dinosaur'],
    'Pteranodon': ['beast', 'dinosaur', 'coastal', 'wild shape'],
    'Plesiosaurus': ['beast', 'dinosaur', 'aquatic'],
    'Mammoth': ['beast', 'arctic'],
    'Rhinoceros': ['beast', 'grassland'],
    'Killer Whale': ['beast', 'aquatic'],
    'Stirge': ['beast', 'underdark', 'wild shape'],
    'Giant Crab': ['beast', 'coastal', 'wild shape'],
    'Giant Octopus': ['beast', 'aquatic', 'wild shape'],
    'Giant Shark': ['beast', 'aquatic'],
    'Hunter Shark': ['beast', 'aquatic'],
    'Reef Shark': ['beast', 'aquatic', 'wild shape'],
    'Quipper': ['beast', 'aquatic', 'wild shape'],
    'Swarm of Bats': ['beast', 'swarm', 'underdark', 'wild shape'],
    'Swarm of Insects': ['beast', 'swarm', 'wild shape'],
    'Swarm of Rats': ['beast', 'swarm', 'urban', 'wild shape'],
    'Swarm of Quippers': ['beast', 'swarm', 'aquatic', 'wild shape'],
    'Vulture': ['beast', 'desert', 'wild shape'],
    'Ankylosaurus': ['beast', 'dinosaur'],
    'Archelon': ['beast', 'dinosaur', 'aquatic'],
    'Baboon': ['beast', 'forest', 'wild shape'],
    'Badger': ['beast', 'forest', 'wild shape'],
    'Bat': ['beast', 'familiar', 'underdark', 'wild shape'],
    'Black Bear': ['beast', 'forest', 'wild shape'],
    'Blood Hawk': ['beast', 'mountain', 'wild shape'],
    'Crab': ['beast', 'coastal', 'wild shape'],
    'Deer': ['beast', 'forest', 'wild shape'],
    'Draft Horse': ['beast', 'mount', 'wild shape'],
    'Elk': ['beast', 'forest', 'grassland', 'wild shape'],
    'Flying Snake': ['beast', 'forest', 'wild shape'],
    'Giant Ape': ['beast', 'forest'],
    'Giant Badger': ['beast', 'forest', 'burrower', 'wild shape'],
    'Giant Bat': ['beast', 'underdark', 'wild shape'],
    'Giant Boar': ['beast', 'forest'],
    'Giant Crocodile': ['beast', 'swamp'],
    'Giant Elk': ['beast', 'forest'],
    'Giant Fire Beetle': ['beast', 'underdark', 'light source', 'wild shape'],
    'Giant Goat': ['beast', 'mountain', 'mount', 'wild shape'],
    'Giant Hyena': ['beast', 'grassland', 'wild shape'],
    'Giant Owl': ['beast', 'forest', 'wild shape'],
    'Giant Scorpion': ['beast', 'desert'],
    'Giant Seahorse': ['beast', 'aquatic', 'mount', 'wild shape'],
    'Giant Spider': ['beast', 'forest', 'underdark', 'wild shape'],
    'Giant Toad': ['beast', 'swamp', 'wild shape'],
    'Giant Venomous Snake': ['beast', 'forest', 'swamp', 'wild shape'],
    'Giant Vulture': ['beast', 'desert', 'wild shape'],
    'Giant Wasp': ['beast', 'forest', 'wild shape'],
    'Giant Weasel': ['beast', 'forest', 'wild shape'],
    'Giant Wolf Spider': ['beast', 'forest', 'wild shape'],
    'Goat': ['beast', 'mountain', 'wild shape'],
    'Hippopotamus': ['beast', 'swamp'],
    'Hyena': ['beast', 'grassland', 'wild shape'],
    'Jackal': ['beast', 'desert', 'wild shape'],
    'Lizard': ['beast', 'familiar', 'wild shape'],
    'Mule': ['beast', 'mount', 'wild shape'],
    'Panther': ['beast', 'forest', 'wild shape'],
    'Piranha': ['beast', 'aquatic', 'wild shape'],
    'Raven': ['beast', 'familiar', 'wild shape'],
    'Saber-Toothed Tiger': ['beast', 'arctic'],
    'Scorpion': ['beast', 'desert', 'wild shape'],
    'Spider': ['beast', 'familiar', 'wild shape'],
    'Venomous Snake': ['beast', 'forest', 'swamp', 'wild shape'],
    'Weasel': ['beast', 'familiar', 'wild shape'],
    'Swarm of Piranhas': ['beast', 'swarm', 'aquatic', 'wild shape'],
    'Swarm of Ravens': ['beast', 'swarm', 'wild shape'],
    'Swarm of Venomous Snakes': ['beast', 'swarm', 'swamp'],
  },
};
