// SRD 5.2.1 Weapons (p. 91 weapons table; properties/masteries on Tier-0
// already; ammunition rows authored in ammunition.dart).
//
// Each row carries every fieldKey from the `weapon` Tier-1 schema in
// content.dart:533-566. References to Tier-0 lookups use `lookup(slug, name)`
// placeholders and are resolved at import time.

import '_helpers.dart';

const _slug = 'weapon';

Map<String, dynamic> _w({
  required String name,
  required String category, // 'Simple' | 'Martial'
  required bool melee,
  required String dice,
  required String dmgType,
  required List<String> properties,
  required String mastery,
  required double costGp,
  required double weightLb,
  int? normalRangeFt,
  int? longRangeFt,
  String? versatileDice,
  String? ammoType, // ammunition row name (e.g. "Arrows")
}) {
  final attrs = <String, dynamic>{
    'category_ref': lookup('weapon-category', category),
    'is_melee': melee,
    'damage_dice': dice,
    'damage_type_ref': lookup('damage-type', dmgType),
    'property_refs':
        properties.map((p) => lookup('weapon-property', p)).toList(),
    'mastery_ref': lookup('weapon-mastery', mastery),
    'cost_gp': costGp,
    'weight_lb': weightLb,
  };
  if (normalRangeFt != null) attrs['normal_range_ft'] = normalRangeFt;
  if (longRangeFt != null) attrs['long_range_ft'] = longRangeFt;
  if (versatileDice != null) attrs['versatile_damage_dice'] = versatileDice;
  if (ammoType != null) {
    attrs['ammunition_type_ref'] = ref('ammunition', ammoType);
  }
  return packEntity(slug: _slug, name: name, attributes: attrs);
}

/// Hand-authored weapon rows from SRD 5.2.1 p. 91 weapons table.
List<Map<String, dynamic>> srdWeapons() => [
      // ── Simple Melee Weapons ──────────────────────────────────────
      _w(name: 'Club', category: 'Simple', melee: true, dice: '1d4',
          dmgType: 'Bludgeoning', properties: ['Light'], mastery: 'Slow',
          costGp: 0.1, weightLb: 2),
      _w(name: 'Dagger', category: 'Simple', melee: true, dice: '1d4',
          dmgType: 'Piercing',
          properties: ['Finesse', 'Light', 'Thrown'], mastery: 'Nick',
          costGp: 2, weightLb: 1, normalRangeFt: 20, longRangeFt: 60),
      _w(name: 'Greatclub', category: 'Simple', melee: true, dice: '1d8',
          dmgType: 'Bludgeoning', properties: ['Two-Handed'], mastery: 'Push',
          costGp: 0.2, weightLb: 10),
      _w(name: 'Handaxe', category: 'Simple', melee: true, dice: '1d6',
          dmgType: 'Slashing', properties: ['Light', 'Thrown'], mastery: 'Vex',
          costGp: 5, weightLb: 2, normalRangeFt: 20, longRangeFt: 60),
      _w(name: 'Javelin', category: 'Simple', melee: true, dice: '1d6',
          dmgType: 'Piercing', properties: ['Thrown'], mastery: 'Slow',
          costGp: 0.5, weightLb: 2, normalRangeFt: 30, longRangeFt: 120),
      _w(name: 'Light Hammer', category: 'Simple', melee: true, dice: '1d4',
          dmgType: 'Bludgeoning',
          properties: ['Light', 'Thrown'], mastery: 'Nick',
          costGp: 2, weightLb: 2, normalRangeFt: 20, longRangeFt: 60),
      _w(name: 'Mace', category: 'Simple', melee: true, dice: '1d6',
          dmgType: 'Bludgeoning', properties: [], mastery: 'Sap',
          costGp: 5, weightLb: 4),
      _w(name: 'Quarterstaff', category: 'Simple', melee: true, dice: '1d6',
          dmgType: 'Bludgeoning', properties: ['Versatile'], mastery: 'Topple',
          costGp: 0.2, weightLb: 4, versatileDice: '1d8'),
      _w(name: 'Sickle', category: 'Simple', melee: true, dice: '1d4',
          dmgType: 'Slashing', properties: ['Light'], mastery: 'Nick',
          costGp: 1, weightLb: 2),
      _w(name: 'Spear', category: 'Simple', melee: true, dice: '1d6',
          dmgType: 'Piercing',
          properties: ['Thrown', 'Versatile'], mastery: 'Sap',
          costGp: 1, weightLb: 3,
          normalRangeFt: 20, longRangeFt: 60, versatileDice: '1d8'),

      // ── Simple Ranged Weapons ─────────────────────────────────────
      _w(name: 'Dart', category: 'Simple', melee: false, dice: '1d4',
          dmgType: 'Piercing',
          properties: ['Finesse', 'Thrown'], mastery: 'Vex',
          costGp: 0.05, weightLb: 0.25,
          normalRangeFt: 20, longRangeFt: 60),
      _w(name: 'Light Crossbow', category: 'Simple', melee: false,
          dice: '1d8', dmgType: 'Piercing',
          properties: ['Ammunition', 'Loading', 'Two-Handed'],
          mastery: 'Slow', costGp: 25, weightLb: 5,
          normalRangeFt: 80, longRangeFt: 320, ammoType: 'Bolts'),
      _w(name: 'Shortbow', category: 'Simple', melee: false, dice: '1d6',
          dmgType: 'Piercing',
          properties: ['Ammunition', 'Two-Handed'], mastery: 'Vex',
          costGp: 25, weightLb: 2,
          normalRangeFt: 80, longRangeFt: 320, ammoType: 'Arrows'),
      _w(name: 'Sling', category: 'Simple', melee: false, dice: '1d4',
          dmgType: 'Bludgeoning', properties: ['Ammunition'], mastery: 'Slow',
          costGp: 0.1, weightLb: 0,
          normalRangeFt: 30, longRangeFt: 120, ammoType: 'Bullets, Sling'),

      // ── Martial Melee Weapons ─────────────────────────────────────
      _w(name: 'Battleaxe', category: 'Martial', melee: true, dice: '1d8',
          dmgType: 'Slashing', properties: ['Versatile'], mastery: 'Topple',
          costGp: 10, weightLb: 4, versatileDice: '1d10'),
      _w(name: 'Flail', category: 'Martial', melee: true, dice: '1d8',
          dmgType: 'Bludgeoning', properties: [], mastery: 'Sap',
          costGp: 10, weightLb: 2),
      _w(name: 'Glaive', category: 'Martial', melee: true, dice: '1d10',
          dmgType: 'Slashing',
          properties: ['Heavy', 'Reach', 'Two-Handed'], mastery: 'Graze',
          costGp: 20, weightLb: 6),
      _w(name: 'Greataxe', category: 'Martial', melee: true, dice: '1d12',
          dmgType: 'Slashing',
          properties: ['Heavy', 'Two-Handed'], mastery: 'Cleave',
          costGp: 30, weightLb: 7),
      _w(name: 'Greatsword', category: 'Martial', melee: true, dice: '2d6',
          dmgType: 'Slashing',
          properties: ['Heavy', 'Two-Handed'], mastery: 'Graze',
          costGp: 50, weightLb: 6),
      _w(name: 'Halberd', category: 'Martial', melee: true, dice: '1d10',
          dmgType: 'Slashing',
          properties: ['Heavy', 'Reach', 'Two-Handed'], mastery: 'Cleave',
          costGp: 20, weightLb: 6),
      _w(name: 'Lance', category: 'Martial', melee: true, dice: '1d10',
          dmgType: 'Piercing',
          properties: ['Heavy', 'Reach', 'Two-Handed'], mastery: 'Topple',
          costGp: 10, weightLb: 6),
      _w(name: 'Longsword', category: 'Martial', melee: true, dice: '1d8',
          dmgType: 'Slashing', properties: ['Versatile'], mastery: 'Sap',
          costGp: 15, weightLb: 3, versatileDice: '1d10'),
      _w(name: 'Maul', category: 'Martial', melee: true, dice: '2d6',
          dmgType: 'Bludgeoning',
          properties: ['Heavy', 'Two-Handed'], mastery: 'Topple',
          costGp: 10, weightLb: 10),
      _w(name: 'Morningstar', category: 'Martial', melee: true, dice: '1d8',
          dmgType: 'Piercing', properties: [], mastery: 'Sap',
          costGp: 15, weightLb: 4),
      _w(name: 'Pike', category: 'Martial', melee: true, dice: '1d10',
          dmgType: 'Piercing',
          properties: ['Heavy', 'Reach', 'Two-Handed'], mastery: 'Push',
          costGp: 5, weightLb: 18),
      _w(name: 'Rapier', category: 'Martial', melee: true, dice: '1d8',
          dmgType: 'Piercing', properties: ['Finesse'], mastery: 'Vex',
          costGp: 25, weightLb: 2),
      _w(name: 'Scimitar', category: 'Martial', melee: true, dice: '1d6',
          dmgType: 'Slashing',
          properties: ['Finesse', 'Light'], mastery: 'Nick',
          costGp: 25, weightLb: 3),
      _w(name: 'Shortsword', category: 'Martial', melee: true, dice: '1d6',
          dmgType: 'Piercing',
          properties: ['Finesse', 'Light'], mastery: 'Vex',
          costGp: 10, weightLb: 2),
      _w(name: 'Trident', category: 'Martial', melee: true, dice: '1d8',
          dmgType: 'Piercing',
          properties: ['Thrown', 'Versatile'], mastery: 'Topple',
          costGp: 5, weightLb: 4,
          normalRangeFt: 20, longRangeFt: 60, versatileDice: '1d10'),
      _w(name: 'Warhammer', category: 'Martial', melee: true, dice: '1d8',
          dmgType: 'Bludgeoning', properties: ['Versatile'], mastery: 'Push',
          costGp: 15, weightLb: 5, versatileDice: '1d10'),
      _w(name: 'War Pick', category: 'Martial', melee: true, dice: '1d8',
          dmgType: 'Piercing', properties: ['Versatile'], mastery: 'Sap',
          costGp: 5, weightLb: 2, versatileDice: '1d10'),
      _w(name: 'Whip', category: 'Martial', melee: true, dice: '1d4',
          dmgType: 'Slashing',
          properties: ['Finesse', 'Reach'], mastery: 'Slow',
          costGp: 2, weightLb: 3),

      // ── Martial Ranged Weapons ────────────────────────────────────
      _w(name: 'Blowgun', category: 'Martial', melee: false, dice: '1',
          dmgType: 'Piercing',
          properties: ['Ammunition', 'Loading'], mastery: 'Vex',
          costGp: 10, weightLb: 1,
          normalRangeFt: 25, longRangeFt: 100, ammoType: 'Needles'),
      _w(name: 'Hand Crossbow', category: 'Martial', melee: false,
          dice: '1d6', dmgType: 'Piercing',
          properties: ['Ammunition', 'Light', 'Loading'], mastery: 'Vex',
          costGp: 75, weightLb: 3,
          normalRangeFt: 30, longRangeFt: 120, ammoType: 'Bolts'),
      _w(name: 'Heavy Crossbow', category: 'Martial', melee: false,
          dice: '1d10', dmgType: 'Piercing',
          properties: ['Ammunition', 'Heavy', 'Loading', 'Two-Handed'],
          mastery: 'Push', costGp: 50, weightLb: 18,
          normalRangeFt: 100, longRangeFt: 400, ammoType: 'Bolts'),
      _w(name: 'Longbow', category: 'Martial', melee: false, dice: '1d8',
          dmgType: 'Piercing',
          properties: ['Ammunition', 'Heavy', 'Two-Handed'],
          mastery: 'Slow', costGp: 50, weightLb: 2,
          normalRangeFt: 150, longRangeFt: 600, ammoType: 'Arrows'),
      _w(name: 'Musket', category: 'Martial', melee: false, dice: '1d12',
          dmgType: 'Piercing',
          properties: ['Ammunition', 'Loading', 'Two-Handed'],
          mastery: 'Slow', costGp: 500, weightLb: 10,
          normalRangeFt: 40, longRangeFt: 120,
          ammoType: 'Bullets, Firearm'),
      _w(name: 'Pistol', category: 'Martial', melee: false, dice: '1d10',
          dmgType: 'Piercing',
          properties: ['Ammunition', 'Loading'], mastery: 'Vex',
          costGp: 250, weightLb: 3,
          normalRangeFt: 30, longRangeFt: 90,
          ammoType: 'Bullets, Firearm'),
    ];
