"""Shared UI sizing and spacing constants for consistent widget layout."""

BUTTON_PADDING = "6px 16px"
INPUT_PADDING = "6px"
GROUP_MARGIN = "8px"
SECTION_SPACING = 12
BORDER_RADIUS_BUTTON = "4px"
BORDER_RADIUS_INPUT = "3px"
FONT_SIZE_BODY = 13
FONT_SIZE_HEADER = 15
ICON_SIZE_TOOLBAR = 24
ICON_SIZE_SIDEBAR = 16
