-- Wrap auth.uid()/current_setting() in RLS policy predicates in (select ...) so
-- Postgres evaluates each once per statement (an InitPlan) instead of once per row --
-- the Supabase-documented RLS perf pattern. Covers USING and WITH CHECK. Predicate-
-- equivalent (row visibility unchanged). Generated by 'pgrls fix --rule PERF001'
-- (pgrls 0.44.0) and verified on Postgres 16 (PERF001 -> 0).

-- [PERF001] Wrap auth function call(s) in policy 'beta_participants self read' on public.beta_participants so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "beta_participants self read" ON public.beta_participants
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'beta_requests self read' on public.beta_requests so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "beta_requests self read" ON public.beta_requests
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'bug_reports self insert' on public.bug_reports so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "bug_reports self insert" ON public.bug_reports
    WITH CHECK ((SELECT auth.uid()) = user_id AND status = CAST('open' AS text) AND admin_note IS NULL);

-- [PERF001] Wrap auth function call(s) in policy 'bug_reports self read' on public.bug_reports so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "bug_reports self read" ON public.bug_reports
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'cloud_backups beta insert' on public.cloud_backups so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "cloud_backups beta insert" ON public.cloud_backups
    WITH CHECK ((SELECT auth.uid()) = user_id AND is_beta_active((SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_backups beta update' on public.cloud_backups so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "cloud_backups beta update" ON public.cloud_backups
    USING ((SELECT auth.uid()) = user_id AND is_beta_active((SELECT auth.uid())))
    WITH CHECK ((SELECT auth.uid()) = user_id AND is_beta_active((SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'cloud_backups self delete' on public.cloud_backups so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "cloud_backups self delete" ON public.cloud_backups
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'cloud_backups self read' on public.cloud_backups so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "cloud_backups self read" ON public.cloud_backups
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'community_assets beta insert' on public.community_assets so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "community_assets beta insert" ON public.community_assets
    WITH CHECK ((SELECT auth.uid()) = uploader_id AND is_beta_active((SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'community_assets owner delete' on public.community_assets so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "community_assets owner delete" ON public.community_assets
    USING ((SELECT auth.uid()) = uploader_id);

-- [PERF001] Wrap auth function call(s) in policy 'community_assets owner update' on public.community_assets so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "community_assets owner update" ON public.community_assets
    USING ((SELECT auth.uid()) = uploader_id)
    WITH CHECK ((SELECT auth.uid()) = uploader_id);

-- [PERF001] Wrap auth function call(s) in policy 'community_assets self read' on public.community_assets so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "community_assets self read" ON public.community_assets
    USING ((SELECT auth.uid()) = uploader_id);

-- [PERF001] Wrap auth function call(s) in policy 'Self-add to conversation' on public.conversation_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Self-add to conversation" ON public.conversation_members
    WITH CHECK ((SELECT auth.uid()) = user_id OR is_conversation_member(conversation_id));

-- [PERF001] Wrap auth function call(s) in policy 'Self-leave conversation' on public.conversation_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Self-leave conversation" ON public.conversation_members
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Conversations: anyone can create' on public.conversations so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Conversations: anyone can create" ON public.conversations
    WITH CHECK ((SELECT auth.uid()) = created_by);

-- [PERF001] Wrap auth function call(s) in policy 'Conversations: members read' on public.conversations so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Conversations: members read" ON public.conversations
    USING (is_conversation_member(id) OR (SELECT auth.uid()) = created_by);

-- [PERF001] Wrap auth function call(s) in policy 'Shares: scoped read' on public.entity_shares so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Shares: scoped read" ON public.entity_shares
    USING (is_world_dm(world_id) OR (is_world_member(world_id) AND (shared_with IS NULL OR shared_with = (SELECT auth.uid()))));

-- [PERF001] Wrap auth function call(s) in policy 'follows self delete' on public.follows so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "follows self delete" ON public.follows
    USING ((SELECT auth.uid()) = follower_id);

-- [PERF001] Wrap auth function call(s) in policy 'follows self insert' on public.follows so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "follows self insert" ON public.follows
    WITH CHECK ((SELECT auth.uid()) = follower_id AND NOT is_online_restricted());

-- [PERF001] Wrap auth function call(s) in policy 'Owner manages own free media' on public.free_media_assets so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner manages own free media" ON public.free_media_assets
    USING ((SELECT auth.uid()) = owner_id)
    WITH CHECK ((SELECT auth.uid()) = owner_id);

-- [PERF001] Wrap auth function call(s) in policy 'Applications: applicant or owner delete' on public.game_listing_applications so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Applications: applicant or owner delete" ON public.game_listing_applications
    USING ((SELECT auth.uid()) = applicant_id OR EXISTS (SELECT 1 FROM game_listings AS gl WHERE gl.id = game_listing_applications.listing_id AND gl.owner_id = auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Applications: applicant or owner read' on public.game_listing_applications so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Applications: applicant or owner read" ON public.game_listing_applications
    USING ((SELECT auth.uid()) = applicant_id OR EXISTS (SELECT 1 FROM game_listings AS gl WHERE gl.id = game_listing_applications.listing_id AND gl.owner_id = auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Applications: apply as self' on public.game_listing_applications so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Applications: apply as self" ON public.game_listing_applications
    WITH CHECK ((SELECT auth.uid()) = applicant_id AND NOT is_online_restricted() AND NOT EXISTS (SELECT 1 FROM game_listings AS gl WHERE gl.id = game_listing_applications.listing_id AND gl.owner_id = auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'game_listings owner insert' on public.game_listings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "game_listings owner insert" ON public.game_listings
    WITH CHECK ((SELECT auth.uid()) = owner_id AND NOT is_online_restricted());

-- [PERF001] Wrap auth function call(s) in policy 'game_listings owner or admin delete' on public.game_listings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "game_listings owner or admin delete" ON public.game_listings
    USING ((SELECT auth.uid()) = owner_id OR is_admin());

-- [PERF001] Wrap auth function call(s) in policy 'game_listings owner update' on public.game_listings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "game_listings owner update" ON public.game_listings
    USING ((SELECT auth.uid()) = owner_id)
    WITH CHECK ((SELECT auth.uid()) = owner_id);

-- [PERF001] Wrap auth function call(s) in policy 'Owner inserts own listings' on public.marketplace_listings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner inserts own listings" ON public.marketplace_listings
    WITH CHECK ((SELECT auth.uid()) = owner_id AND is_beta_active((SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'Owner or admin deletes listings' on public.marketplace_listings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner or admin deletes listings" ON public.marketplace_listings
    USING (is_admin() OR (SELECT auth.uid()) = owner_id);

-- [PERF001] Wrap auth function call(s) in policy 'Owner updates own listings' on public.marketplace_listings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner updates own listings" ON public.marketplace_listings
    USING ((SELECT auth.uid()) = owner_id)
    WITH CHECK ((SELECT auth.uid()) = owner_id);

-- [PERF001] Wrap auth function call(s) in policy 'Messages: author deletes own' on public.messages so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Messages: author deletes own" ON public.messages
    USING ((SELECT auth.uid()) = author_id OR is_admin());

-- [PERF001] Wrap auth function call(s) in policy 'Messages: members write' on public.messages so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Messages: members write" ON public.messages
    WITH CHECK ((SELECT auth.uid()) = author_id AND is_conversation_member(conversation_id) AND NOT is_online_restricted());

-- [PERF001] Wrap auth function call(s) in policy 'notification_dismissals self read' on public.notification_dismissals so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "notification_dismissals self read" ON public.notification_dismissals
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'notification_dismissals self write' on public.notification_dismissals so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "notification_dismissals self write" ON public.notification_dismissals
    WITH CHECK ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'notification_reads self read' on public.notification_reads so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "notification_reads self read" ON public.notification_reads
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'notification_reads self write' on public.notification_reads so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "notification_reads self write" ON public.notification_reads
    WITH CHECK ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'notification_responses read' on public.notification_responses so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "notification_responses read" ON public.notification_responses
    USING ((SELECT auth.uid()) = user_id OR is_admin());

-- [PERF001] Wrap auth function call(s) in policy 'ppe: owner all' on public.personal_package_entities so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "ppe: owner all" ON public.personal_package_entities
    USING (owner_id = (SELECT auth.uid()))
    WITH CHECK (owner_id = (SELECT auth.uid()) AND is_beta_active((SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'personal_packages: owner all' on public.personal_packages so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "personal_packages: owner all" ON public.personal_packages
    USING (owner_id = (SELECT auth.uid()))
    WITH CHECK (owner_id = (SELECT auth.uid()) AND is_beta_active((SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'post_likes self delete' on public.post_likes so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "post_likes self delete" ON public.post_likes
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'post_likes self insert' on public.post_likes so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "post_likes self insert" ON public.post_likes
    WITH CHECK ((SELECT auth.uid()) = user_id AND NOT is_online_restricted());

-- [PERF001] Wrap auth function call(s) in policy 'posts author delete' on public.posts so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "posts author delete" ON public.posts
    USING ((SELECT auth.uid()) = author_id OR is_admin());

-- [PERF001] Wrap auth function call(s) in policy 'posts author insert' on public.posts so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "posts author insert" ON public.posts
    WITH CHECK ((SELECT auth.uid()) = author_id AND NOT is_online_restricted());

-- [PERF001] Wrap auth function call(s) in policy 'posts author update' on public.posts so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "posts author update" ON public.posts
    USING ((SELECT auth.uid()) = author_id)
    WITH CHECK ((SELECT auth.uid()) = author_id);

-- [PERF001] Wrap auth function call(s) in policy 'User manages own profile' on public.profiles so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "User manages own profile" ON public.profiles
    USING ((SELECT auth.uid()) = user_id)
    WITH CHECK ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'transient_shares: dm write' on public.transient_shares so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "transient_shares: dm write" ON public.transient_shares
    USING (is_world_dm(world_id) AND uploader_id = (SELECT auth.uid()))
    WITH CHECK (is_world_dm(world_id) AND uploader_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'BMOps: member insert' on public.world_battlemap_mark_ops so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "BMOps: member insert" ON public.world_battlemap_mark_ops
    WITH CHECK (is_world_member(world_id) AND author_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Chars: insert' on public.world_characters so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Chars: insert" ON public.world_characters
    WITH CHECK ((world_id IS NULL AND owner_id = (SELECT auth.uid()) AND is_beta_active((SELECT auth.uid()))) OR (world_id IS NOT NULL AND is_world_member(world_id) AND (owner_id = (SELECT auth.uid()) OR is_world_dm(world_id))));

-- [PERF001] Wrap auth function call(s) in policy 'Chars: read' on public.world_characters so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Chars: read" ON public.world_characters
    USING ((world_id IS NOT NULL AND is_world_member(world_id)) OR (world_id IS NULL AND owner_id = (SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'Chars: update' on public.world_characters so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Chars: update" ON public.world_characters
    USING (owner_id = (SELECT auth.uid()) OR (world_id IS NOT NULL AND is_world_dm(world_id)))
    WITH CHECK (owner_id = (SELECT auth.uid()) OR (world_id IS NOT NULL AND is_world_dm(world_id)));

-- [PERF001] Wrap auth function call(s) in policy 'Members: self dm insert' on public.world_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Members: self dm insert" ON public.world_members
    WITH CHECK (user_id = (SELECT auth.uid()) AND role = CAST('dm' AS text) AND EXISTS (SELECT 1 FROM worlds AS w WHERE w.id = world_members.world_id AND w.owner_id = auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Members: self leave' on public.world_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Members: self leave" ON public.world_members
    USING ((SELECT auth.uid()) = user_id AND role <> CAST('dm' AS text));

-- [PERF001] Wrap auth function call(s) in policy 'Members: self player insert' on public.world_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Members: self player insert" ON public.world_members
    WITH CHECK (user_id = (SELECT auth.uid()) AND role = CAST('player' AS text));

-- [PERF001] Wrap auth function call(s) in policy 'WP: dm writes' on public.world_packages so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "WP: dm writes" ON public.world_packages
    WITH CHECK (is_world_dm(world_id) AND shared_by = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Worlds: dm update' on public.worlds so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Worlds: dm update" ON public.worlds
    USING (is_world_dm(id) AND is_beta_active((SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'Worlds: owner delete' on public.worlds so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Worlds: owner delete" ON public.worlds
    USING ((SELECT auth.uid()) = owner_id);

-- [PERF001] Wrap auth function call(s) in policy 'Worlds: owner insert' on public.worlds so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Worlds: owner insert" ON public.worlds
    WITH CHECK ((SELECT auth.uid()) = owner_id AND is_beta_active((SELECT auth.uid())));
