import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;
import 'package:shared_preferences/shared_preferences.dart';

import '../../../data/database/app_database.dart';
import '../../../domain/dnd5e/effect/custom_effect_registry.dart';
import '../../../domain/dnd5e/package/conflict_resolution.dart';
import '../../../domain/dnd5e/package/dnd5e_package.dart';
import '../../../domain/dnd5e/package/dnd5e_package_codec.dart';
import '../../../domain/dnd5e/package/import_report.dart';
import '../package/dnd5e_package_importer.dart';

/// Default asset path of the built SRD monolith. Generated by
/// `dart run tool/build_srd_pkg.dart`. Bundled via `pubspec.yaml`.
const String defaultSrdAssetPath = 'assets/packages/srd_core.dnd5e-pkg.json';

/// `shared_preferences` key holding the version string of the SRD package
/// already installed for the active user. When the bundled monolith reports
/// the same version, bootstrap short-circuits.
///
/// User-scoped: `AppDatabase.forUser(userId)` already isolates the catalog
/// rows per user, so a single global flag here is keyed implicitly by the
/// active user via the pre-bootstrap user-switch flow. Multi-user installs
/// that need per-user idempotency should pass a user-specific [versionFlag].
const String defaultSrdInstalledVersionFlag = 'srd_core.installed_version';

sealed class SrdBootstrapOutcome {
  const SrdBootstrapOutcome();

  String get summary;
}

class SrdBootstrapAlreadyInstalled extends SrdBootstrapOutcome {
  final String version;
  const SrdBootstrapAlreadyInstalled(this.version);
  @override
  String get summary => 'SRD $version already installed';
}

class SrdBootstrapInstalled extends SrdBootstrapOutcome {
  final String version;
  final ImportReport report;
  final String contentHash;
  const SrdBootstrapInstalled({
    required this.version,
    required this.report,
    required this.contentHash,
  });
  @override
  String get summary =>
      'SRD $version installed (hash $contentHash, ${report.counts})';
}

class SrdBootstrapError extends SrdBootstrapOutcome {
  final String message;
  const SrdBootstrapError(this.message);
  @override
  String get summary => 'SRD bootstrap failed: $message';
}

/// Doc 15 §"Boot Flow / First-run bootstrap" — loads the built SRD monolith
/// from the app's asset bundle, validates its integrity via the envelope's
/// `contentHash`, and runs [Dnd5ePackageImporter.import] in a per-user
/// transaction. Idempotent: a successful run records the package version in
/// `shared_preferences`, so subsequent launches short-circuit.
///
/// Pure dependencies — no globals. The default `loadAsset` reads from
/// `rootBundle`; tests inject a fixture loader so they don't need a built
/// monolith on disk. The default `prefsLoader` is
/// [SharedPreferences.getInstance].
class SrdBootstrapService {
  final AppDatabase db;
  final CustomEffectRegistry registry;
  final String assetPath;
  final String versionFlag;
  final Future<String> Function(String path) loadAsset;
  final Future<SharedPreferences> Function() prefsLoader;

  SrdBootstrapService({
    required this.db,
    required this.registry,
    this.assetPath = defaultSrdAssetPath,
    this.versionFlag = defaultSrdInstalledVersionFlag,
    Future<String> Function(String path)? loadAsset,
    this.prefsLoader = SharedPreferences.getInstance,
  }) : loadAsset = loadAsset ?? rootBundle.loadString;

  Future<SrdBootstrapOutcome> runIfNeeded() async {
    final Dnd5ePackage pkg;
    final String? expectedHash;
    try {
      final raw = await loadAsset(assetPath);
      final json = (jsonDecode(raw) as Map).cast<String, Object?>();
      expectedHash = json['contentHash'] as String?;
      pkg = const Dnd5ePackageCodec().decode(json);
    } catch (e) {
      return SrdBootstrapError('failed to load monolith from "$assetPath": $e');
    }

    final prefs = await prefsLoader();
    if (prefs.getString(versionFlag) == pkg.version) {
      return SrdBootstrapAlreadyInstalled(pkg.version);
    }

    final importer = Dnd5ePackageImporter(db, registry);
    final result = await importer.import(
      pkg,
      onConflict: ConflictResolution.overwrite,
      expectedContentHash: expectedHash,
    );

    switch (result) {
      case PackageImportError(:final message):
        return SrdBootstrapError(message);
      case PackageImportSuccess(:final report):
        await prefs.setString(versionFlag, pkg.version);
        return SrdBootstrapInstalled(
          version: pkg.version,
          report: report,
          contentHash: expectedHash ?? '<unverified>',
        );
    }
  }
}
